import Link from "next/link";
import {notFound} from "next/navigation";

const pages:Record<string,{eyebrow:string;title:string;lead:string;sections:Array<[string,string]>}>={
 "pricing":{eyebrow:"ACCESS & PRICING",title:"Akses sesuai kebutuhan bisnis Anda.",lead:"Paket Lumaway mengikuti modul, jumlah pengguna, data, token, dan kebutuhan operasional yang digunakan.",sections:[["Pilih berdasarkan kebutuhan","Mulai dari workflow yang ingin diselesaikan, bukan sekadar jumlah menu."],["Biaya yang transparan","Subscription, token AI, dan usage operasional dikelola dari Billing serta Control Center."],["Siap berkembang","Workspace dirancang agar fitur dapat ditambah seiring kebutuhan bisnis dan data Anda."]]},
 "about":{eyebrow:"ABOUT LUMAWAY",title:"Light up the path from data to decision.",lead:"Lumaway adalah Business Intelligence Operating Workspace yang menghubungkan data, analisis, AI insight, dan tindak lanjut.",sections:[["Tujuan","Membantu bisnis mengurangi fragmentasi informasi dan membuat keputusan dengan konteks yang lebih jelas."],["Pendekatan","Data → Understand → Analyze → Decide → Act → Grow."],["Ekosistem","Affiliate, produk, commerce, AI, finance, R&D marketing, dan decision workspace dikembangkan dalam satu arah yang terhubung."]]},
 "security":{eyebrow:"SECURITY & DATA",title:"Akses dan data dipisahkan berdasarkan workspace.",lead:"Lumaway menggunakan autentikasi, database Supabase, role access, dan server-side secret handling untuk menjaga pemisahan akses.",sections:[["Workspace isolation","Data user dan workspace dikontrol melalui membership serta Row Level Security pada tabel yang relevan."],["Server-side secrets","Credential OpenAI, payment, dan provider komunikasi tidak ditampilkan kembali di browser."],["Operational controls","Owner dapat mengatur maintenance, provider health, issue monitoring, dan kontrol perubahan kritis."]]},
 "roadmap":{eyebrow:"PRODUCT ROADMAP",title:"Dibangun dari fondasi intelligence menuju operating workspace.",lead:"Roadmap Lumaway berkembang dari affiliate dan data workspace menuju market, competitor, finance, automation, dan business intelligence yang lebih luas.",sections:[["Fondasi aktif","Affiliate Intelligence, database workspace, AI Analytics, reporting, support, content, dan Control Center."],["Pengembangan","Market Intelligence, Competitor Intelligence, Smart Alerts, otomasi data, dan insight lintas channel."],["Prinsip","Fitur baru harus mempunyai sumber data, definisi, ownership, dan manfaat keputusan yang jelas."]]},
 "resources":{eyebrow:"RESOURCES",title:"Panduan untuk bekerja lebih terstruktur dengan data.",lead:"Gunakan tutorial, Insights, dan Knowledge Lumaway untuk memahami fitur dan praktik analisis.",sections:[["Insights","Artikel dan framework analisis untuk data, affiliate, marketing, produk, dan AI."],["Tutorial","Video dan panduan penggunaan tersedia di dashboard user dan progress dapat ditandai per user."],["Help Desk","Luma membantu pertanyaan khusus Lumaway dan dapat meneruskan kasus yang belum selesai ke support."]]},
 "privacy":{eyebrow:"PRIVACY",title:"Privasi dan penggunaan data Lumaway.",lead:"Data workspace digunakan untuk menjalankan fitur yang diminta pengguna. Tracking pemasaran mengikuti consent yang tersedia.",sections:[["Workspace data","Data bisnis dipisahkan berdasarkan workspace dan hak akses."],["Analytics","Event publik untuk analisis audience dan retargeting dicatat ketika consent analytics tersedia."],["Provider","Data minimum yang dibutuhkan dapat diteruskan ke provider seperti OpenAI, payment gateway, atau WhatsApp untuk menjalankan fitur terkait."]]},
 "terms":{eyebrow:"TERMS",title:"Ketentuan penggunaan Lumaway.",lead:"Penggunaan Lumaway mengikuti paket, akses, dan ketentuan layanan yang berlaku pada akun atau perjanjian Anda.",sections:[["Akses","Hak akses bergantung pada subscription, role, workspace, dan fitur yang diaktifkan."],["Data","Pengguna bertanggung jawab atas legalitas dan akurasi data yang diunggah."],["AI","Output AI merupakan alat bantu analisis dan perlu ditinjau sebelum digunakan sebagai keputusan bisnis."]]},
 "cookies":{eyebrow:"COOKIES & ANALYTICS",title:"Kontrol analytics pada website Lumaway.",lead:"Website dapat menggunakan penyimpanan lokal dan analytics untuk memahami penggunaan ketika consent diberikan.",sections:[["Essential","Fungsi autentikasi dan aplikasi dapat membutuhkan penyimpanan teknis."],["Analytics","Page view, referrer, UTM, dan event konten dapat dicatat untuk evaluasi performa."],["Preference","Pilihan consent disimpan agar pengalaman tidak harus diatur ulang setiap kunjungan."]]},
 "affiliate-intelligence":{eyebrow:"LUMAWAY MODULE",title:"Affiliate Intelligence",lead:"Satukan creator, GMV, order, produk, komisi, dan dukungan program dalam konteks yang lebih mudah dianalisis.",sections:[["Creator 360","Lihat identitas dan performa creator dalam periode dan platform yang dipilih."],["Performance Analysis","Gunakan data upload untuk membaca kontribusi, tren, dan rekomendasi."],["Action","Ubah temuan menjadi prioritas creator, produk, dan pekerjaan berikutnya."]]},
 "product-intelligence":{eyebrow:"LUMAWAY MODULE",title:"Product Intelligence",lead:"Hubungkan master SKU, harga, HPP, dan performa penjualan untuk memahami kontribusi produk.",sections:[["Master Data","Pertahankan identitas SKU dan produk yang konsisten."],["HPP Guardrail","Simulasikan fee, promo, ads, labor, overhead, dan margin."],["Analysis","Baca peluang produk bersama konteks creator dan campaign."]]},
 "commerce-intelligence":{eyebrow:"LUMAWAY MODULE",title:"Commerce Intelligence",lead:"Gunakan laporan transaksi dan performa untuk membaca penjualan lintas sumber dengan definisi yang konsisten.",sections:[["Sales","Bandingkan order, quantity, GMV, dan biaya sesuai sumber."],["Database","Simpan histori import dengan deduplication dan audit trail."],["Financial context","Hubungkan sales dengan biaya operasional, API, cashflow, margin, dan laba/rugi."]]},
 "ai-insights":{eyebrow:"LUMAWAY MODULE",title:"AI Insights",lead:"AI membantu merangkum data, pola, risiko, anomali, dan rekomendasi dengan konteks workspace.",sections:[["Grounded analysis","Prompt menggunakan data yang tersedia dan tidak seharusnya mengarang angka yang tidak ada."],["Model & cost","Owner dapat melihat model, token, dan estimasi biaya USD/IDR."],["Failover","Routing dapat berpindah ke model partner ketika layanan utama mengalami gangguan."]]},
 "decision-workspace":{eyebrow:"LUMAWAY MODULE",title:"Decision Workspace",lead:"Jaga agar insight tidak berhenti sebagai laporan dengan workflow tindakan dan prioritas.",sections:[["Kanban","Ubah temuan menjadi task dan status pekerjaan."],["Document history","Simpan analysis dan report agar dapat ditinjau kembali."],["Notification","Surface update penting, issue, tutorial, dan creator signals pada user."]]},
 "market-intelligence":{eyebrow:"DEVELOPMENT DIRECTION",title:"Market Intelligence",lead:"Arah pengembangan untuk membaca kategori, permintaan, produk, dan sinyal pasar dari sumber yang diizinkan.",sections:[["Research","Kumpulkan pertanyaan, bukti, dan pola yang relevan."],["Context","Bedakan data aktual, estimasi, dan hipotesis."],["Action","Gunakan temuan untuk eksperimen produk dan marketing."]]},
 "competitor-intelligence":{eyebrow:"DEVELOPMENT DIRECTION",title:"Competitor Intelligence",lead:"Arah pengembangan untuk benchmarking harga, produk, positioning, dan aktivitas kompetitor.",sections:[["Monitoring","Susun perubahan penting dari sumber yang legal dan dapat ditelusuri."],["Comparison","Bandingkan atribut dengan konteks periode dan sumber."],["Alerts","Notifikasi perubahan akan dikembangkan untuk sinyal yang relevan."]]},
 "marketing-intelligence":{eyebrow:"DEVELOPMENT DIRECTION",title:"Marketing Intelligence",lead:"Satukan riset, hipotesis campaign, eksperimen, dan pembelajaran marketing dalam satu alur.",sections:[["Research","Mulai dari problem dan evidence."],["Experiment","Uji satu perubahan utama dengan indikator yang jelas."],["Learn","Simpan hasil termasuk eksperimen yang belum memberikan jawaban pasti."]]},
 "smart-alerts":{eyebrow:"DEVELOPMENT DIRECTION",title:"Smart Alerts",lead:"Notifikasi berbasis perubahan penting agar tim tahu kapan data membutuhkan perhatian.",sections:[["Signals","Creator on fire, issue, provider, subscription, dan data update."],["Priority","Bedakan informasi, warning, dan kondisi kritis."],["Action","Hubungkan alert ke halaman atau tindakan yang relevan."]]},
 "solutions/brand-owner":{eyebrow:"SOLUTION",title:"Untuk Brand Owner",lead:"Lihat kondisi bisnis dari ringkasan menuju detail tanpa menyusun konteks dari awal setiap kali.",sections:[["Visibility","Pantau sales, creator, produk, biaya, dan issue."],["Decision","Gunakan report dan insight untuk menentukan prioritas."],["Control","Control Center memisahkan monitoring dari operasi user."]]},
 "solutions/marketing-team":{eyebrow:"SOLUTION",title:"Untuk Marketing Team",lead:"Hubungkan performa, creator, konten, campaign, dan pembelajaran ke workflow yang lebih terstruktur.",sections:[["Analyze","Baca performance, trend, anomaly, dan recommendation."],["Execute","Ubah rekomendasi menjadi task dan campaign follow-up."],["Learn","Gunakan blog, tutorial, dan knowledge sebagai dokumentasi pembelajaran."]]},
 "solutions/product-rnd":{eyebrow:"SOLUTION",title:"Untuk Product & R&D",lead:"Hubungkan data produk, HPP, market signal, dan eksperimen sebelum menentukan pengembangan berikutnya.",sections:[["Evidence","Mulai dari data, feedback, dan problem yang jelas."],["Economics","Periksa HPP, margin, promo, labor, dan overhead."],["Iteration","Catat hipotesis, tindakan, hasil, dan perbaikan berikutnya."]]},
 "solutions":{eyebrow:"SOLUTIONS",title:"Lumaway untuk tim yang bergerak dengan data.",lead:"Gunakan modul sesuai peran dan kebutuhan keputusan, tanpa memaksa semua tim bekerja dengan tampilan yang sama.",sections:[["Owner","Monitoring dan control."],["Marketing","Affiliate, campaign, insight, dan action."],["Product","Master data, HPP, R&D, dan market context."]]}
};

function normalize(parts:string[]){return parts.join("/").replace(/^\/+|\/+$/g,"")}

export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){
 const {slug}=await params;const key=normalize(slug);const page=pages[key];
 if(!page)return {title:"Lumaway"};
 return {title:`${page.title} | Lumaway`,description:page.lead,alternates:{canonical:`https://www.lumaway.online/web/${key}`}};
}

export default async function PublicMarketingPage({params,searchParams}:{params:Promise<{slug:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {slug}=await params;const query=await searchParams;const key=normalize(slug);
 if(key==="contact"){
   const demo=query.type==="demo";
   return <Shell><section className="lw-generic-hero"><span className="lw-eyebrow">CONTACT LUMAWAY</span><h1>{demo?"Minta demo Lumaway.":"Diskusikan kebutuhan Anda."}</h1><p>Ceritakan kebutuhan workspace, data, jumlah user, dan modul yang ingin digunakan. Tim Lumaway dapat melanjutkan proses melalui channel support yang tersedia.</p><div className="lw-actions"><Link className="lw-button" href="/app.lumaway/register">Buat Akun →</Link><Link className="lw-text-link" href="/app.lumaway/login">Sudah punya akun? Login</Link></div></section></Shell>;
 }
 const page=pages[key];if(!page)notFound();
 return <Shell><section className="lw-generic-hero"><span className="lw-eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.lead}</p><div className="lw-actions"><Link className="lw-button" href="/app.lumaway/register">Mulai dengan Lumaway →</Link><Link className="lw-text-link" href="/web/home">Kembali ke Home</Link></div></section><section className="lw-generic-grid">{page.sections.map(([title,body])=><article key={title}><span>◆</span><h2>{title}</h2><p>{body}</p></article>)}</section></Shell>;
}

function Shell({children}:{children:React.ReactNode}){
 return <main><header className="lw-nav"><Link href="/web/home" className="lw-brand"><img src="/luma-mark.png" alt=""/><strong>LUMAWAY<span>.</span></strong></Link><nav><Link href="/web/home">Home</Link><Link href="/web/insights">Insights</Link><Link href="/web/pricing">Pricing</Link><Link href="/app.lumaway/login">Login</Link><Link className="lw-primary-link" href="/app.lumaway/register">Buat Akun</Link></nav></header>{children}<footer className="lw-footer"><div className="lw-brand"><img src="/luma-mark.png" alt=""/><strong>LUMAWAY<span>.</span></strong></div><div><Link href="/web/about">About</Link><Link href="/web/security">Security</Link><Link href="/web/privacy">Privacy</Link><Link href="/web/terms">Terms</Link></div><small>© {new Date().getFullYear()} Lumaway</small></footer></main>
}
