import {notFound} from 'next/navigation';
import Link from 'next/link';
import {articles} from '@/content/articles';
import {metadata as meta} from '@/lib/seo';
import {JsonLd,FinalCta} from '@/components/ui';
import {site} from '@/lib/config';
import {getPublishedBlog,getPublishedBlogs} from '@/lib/lumaway-data';
import MarketingContentTracker from '@/components/content-tracker';

function youtubeEmbed(url:string){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return 'https://www.youtube.com/embed/'+u.pathname.replace('/','');if(u.hostname.includes('youtube.com')){const v=u.searchParams.get('v');if(v)return 'https://www.youtube.com/embed/'+v;if(u.pathname.includes('/embed/'))return url}}catch{}return ''}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const db=await getPublishedBlog(slug);if(db)return {...meta(db.seo_title||db.title,db.seo_description||db.excerpt||'',`/insights/${db.slug}`),openGraph:{type:'article' as const,title:db.title,description:db.excerpt||'',publishedTime:db.published_at||undefined,modifiedTime:db.updated_at,url:`${site.url}/insights/${db.slug}`,images:db.cover_image_url?[db.cover_image_url]:[`${site.url}/opengraph-image`]}};const a=articles.find(a=>a.slug===slug);return a?{...meta(a.title,a.description,`/insights/${a.slug}`),openGraph:{type:'article' as const,title:a.title,description:a.description,publishedTime:a.date,modifiedTime:a.date,url:`${site.url}/insights/${a.slug}`,images:[`${site.url}/opengraph-image`]}}:{}}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const db=await getPublishedBlog(slug);
 if(db){const related=(await getPublishedBlogs(8)).filter(x=>x.id!==db.id).slice(0,4);const embed=db.video_embed_url?youtubeEmbed(db.video_embed_url):'';return <><MarketingContentTracker contentId={db.id}/><article className="container"><header className="inner-hero article-header"><nav className="breadcrumb"><Link href="/home">Beranda</Link><span>/</span><Link href="/insights">Wawasan</Link></nav><span className="eyebrow">{db.category}</span><h1>{db.title}</h1><p>{db.excerpt}</p><div className="article-meta"><span>Posted by {db.author_name||'Lumaway'}</span>{db.published_at&&<time>{new Date(db.published_at).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</time>}</div>{db.cover_image_url&&<img className="article-cover-db" src={db.cover_image_url} alt={db.image_alt||db.title}/>}</header><div className="article-layout"><div className="article-body"><div dangerouslySetInnerHTML={{__html:db.content_html||''}}/>{embed&&<div className="article-video"><iframe src={embed} title={db.title} allowFullScreen/></div>}{db.video_embed_url&&!embed&&<p><a href={db.video_embed_url} target="_blank" rel="noreferrer">Lihat video terkait ↗</a></p>}{db.external_dofollow_url&&<p className="context-note">Referensi terkait: <a href={db.external_dofollow_url} target="_blank" rel="noreferrer">{db.external_dofollow_url}</a></p>}<div className="related-links">{related.map(r=><Link href={`/insights/${r.slug}`} key={r.id}>{r.title} ↗</Link>)}</div></div><aside className="article-aside"><span>ARTIKEL LUMAWAY</span><b>{db.category}</b><small>Posted by {db.author_name||'Lumaway'}</small></aside></div></article><FinalCta/><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:db.title,description:db.excerpt,datePublished:db.published_at,dateModified:db.updated_at,author:{'@type':'Organization',name:db.author_name||'Lumaway'},publisher:{'@type':'Organization',name:'Lumaway'},mainEntityOfPage:`${site.url}/insights/${db.slug}`,image:db.cover_image_url||`${site.url}/opengraph-image`}}/></>}
 const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <><article className="container"><header className="inner-hero article-header"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/home">Beranda</Link><span>/</span><Link href="/insights">Wawasan</Link></nav><span className="eyebrow">{a.category}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><span>Posted by Lumaway</span><time dateTime={a.date}>16 September 2026</time><span>{a.readTime} baca</span></div></header><div className="article-layout"><div className="article-body">{a.sections.map((s,i)=><section key={s.title} id={`bagian-${i}`}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}</div></div></article><FinalCta/></>;
}
