import {notFound} from 'next/navigation';
import Link from 'next/link';
import {articles} from '@/content/articles';
import {metadata as meta} from '@/lib/seo';
import {JsonLd,FinalCta} from '@/components/ui';
import {site} from '@/lib/config';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);return a?{...meta(a.title,a.description,`/insights/${a.slug}`),openGraph:{type:'article' as const,title:a.title,description:a.description,publishedTime:a.date,modifiedTime:a.date,url:`${site.url}/insights/${a.slug}`,images:[`${site.url}/opengraph-image`]}}:{}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <><article className="container"><header className="inner-hero article-header"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/home">Beranda</Link><span>/</span><Link href="/insights">Wawasan</Link></nav><span className="eyebrow">{a.category}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><span>Tim Lumaway</span><time dateTime={a.date}>16 September 2026</time><span>{a.readTime} baca</span></div></header><div className="article-layout"><div className="article-body">{a.sections.map((s,i)=><section key={s.title} id={`bagian-${i}`}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<div className="context-note">Gunakan kerangka ini sebagai bahan diskusi. Sesuaikan sumber, periode, dan indikator dengan kondisi bisnis Anda.</div><div className="related-links">{articles.filter(x=>x.slug!==a.slug).map(r=><Link href={`/insights/${r.slug}`} key={r.slug}>{r.title} ↗</Link>)}</div></div><aside className="article-aside"><span>DALAM ARTIKEL INI</span>{a.sections.map((s,i)=><a key={s.title} href={`#bagian-${i}`}>{s.title}</a>)}</aside></div></article><FinalCta/><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:a.date,dateModified:a.date,author:{'@type':'Organization',name:'Tim Lumaway'},publisher:{'@type':'Organization',name:'Lumaway'},mainEntityOfPage:`${site.url}/insights/${a.slug}`,image:`${site.url}/opengraph-image`}}/><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Beranda',item:site.homeUrl},{'@type':'ListItem',position:2,name:'Wawasan',item:`${site.url}/insights`},{'@type':'ListItem',position:3,name:a.title,item:`${site.url}/insights/${a.slug}`}]}}/></>}
