import {NextRequest,NextResponse} from "next/server";
import {getServerContext} from "../../../../lib/server-auth";
import {getServerSecret} from "../../../../lib/server-secrets";
import {openAIResponsesWithFailover} from "../../../../lib/openai-router";
export const runtime="nodejs";
function outputText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const i of data?.output||[])for(const x of i?.content||[])if(x?.type==="output_text"&&x?.text)return x.text;return ""}
const schema={type:"object",additionalProperties:false,properties:{summary:{type:"string"},risk_level:{type:"string",enum:["LOW","MEDIUM","HIGH"]},findings:{type:"array",items:{type:"string"}},recommendations:{type:"array",items:{type:"string"}}},required:["summary","risk_level","findings","recommendations"]};
export async function POST(req:NextRequest){try{const b=await req.json();const ctx=await getServerContext(String(b.workspace_id||""));if(!ctx.platformAdmin)return NextResponse.json({ok:false,error:"Owner access required."},{status:403});const m=b.metrics||{};const n=(k:string)=>Math.max(0,Number(m[k]||0));const selling=n("selling_price"),discount=selling*n("discount_pct")/100,marketplace=selling*n("marketplace_fee_pct")/100,affiliate=selling*n("affiliate_commission_pct")/100,tax=selling*n("tax_pct")/100;const netRevenue=Math.max(0,selling-discount);const product=n("product_cost"),pack=n("packaging"),shipping=n("shipping_subsidy"),ads=n("ads_per_order"),labor=n("labor_per_order"),overhead=n("overhead_per_order"),other=n("other_cost")+marketplace+affiliate+tax;const totalCost=product+pack+shipping+ads+labor+overhead+other;const margin=netRevenue-totalCost;const marginPct=netRevenue?margin/netRevenue*100:0;const breakEvenPrice=(totalCost)/(Math.max(.01,1-(n("discount_pct")+n("marketplace_fee_pct")+n("affiliate_commission_pct")+n("tax_pct"))/100));const result={selling_price:selling,net_revenue:netRevenue,total_cost:totalCost,contribution_margin:margin,margin_pct:marginPct,break_even_price:breakEvenPrice,is_loss:margin<0,promo_discount:discount,marketplace_fee:marketplace,affiliate_commission:affiliate,tax};
 const key=await getServerSecret(ctx.admin,"luma_openai_api_key");if(!key)return NextResponse.json({ok:false,error:"OpenAI integration belum dikonfigurasi."},{status:503});const routed=await openAIResponsesWithFailover(ctx.admin,key,{instructions:"Anda adalah cost analyst Lumaway. Gunakan hanya metrik dan hasil kalkulasi. Jelaskan risiko promo/HPP tanpa mengarang angka. Fokus menjaga contribution margin positif dan biaya operasional realistis.",input:JSON.stringify({name:b.name,sku:b.sku,product_name:b.product_name,metrics:m,result}),text:{format:{type:"json_schema",name:"lumaway_hpp_guardrail",schema,strict:true}},store:false},"gpt-5.6-sol");const insight=JSON.parse(outputText(routed.raw));const {data,error}=await ctx.admin.from("luma_hpp_scenarios").insert({name:String(b.name||"HPP Scenario"),sku:b.sku||null,product_name:b.product_name||null,metrics:m,result,ai_insight:insight,model:routed.model,created_by:ctx.user.id}).select("*").single();if(error)throw error;const u=routed.raw?.usage||{};await ctx.admin.from("luma_api_usage_events").insert({workspace_id:String(b.workspace_id||""),user_id:ctx.user.id,provider:"openai",service:"hpp_analysis",request_type:"cost_guardrail",model:routed.model,input_tokens:Number(u.input_tokens||0),output_tokens:Number(u.output_tokens||0),total_tokens:Number(u.total_tokens||0),cost_usd:routed.cost.cost_usd,cost_idr:routed.cost.cost_idr,status:"success",reference:String(data.id),metadata:{fallback_used:routed.fallback_used}});return NextResponse.json({ok:true,scenario:data,result,insight,model:routed.model})}catch(error:any){return NextResponse.json({ok:false,error:error?.message||"Gagal menghitung HPP."},{status:400})}}
