import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Search,Files,MessagesSquare,ChartNoAxesCombined,Check,Minus} from 'lucide-react';
import {LightPath,ProductStories,UseCases,Workflow} from '@/components/experience';
import {ButtonLink,SectionHeading,CapabilityList,ArticleCards,Faq,FinalCta,JsonLd} from '@/components/ui';
import {metadata as meta} from '@/lib/seo';
import {site,publishedProof} from '@/lib/config';
export const metadata=meta('Dari data, menuju keputusan yang lebih jelas','Kenali Lumaway: workspace intelligence untuk affiliate, produk, AI, dan arah pengembangan riset pasar serta R&D marketing.');
export default function Home(){return <>
 <section className="container hero"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line"/> BUSINESS INTELLIGENCE OPERATING WORKSPACE</span><h1>Data berlimpah.<br/>Saatnya punya<br/><span className="underlined">arah yang jelas.</span></h1><p>Hubungkan data, temukan maknanya, dan ubah insight menjadi langkah berikutnya untuk bisnis Anda.</p><div className="hero-actions"><ButtonLink href="#kenali" event="hero_cta_click">Jelajahi Lumaway</ButtonLink><Link href="#cara-kerja" className="text-link" data-event="hero_cta_click">Lihat cara kerjanya<ArrowRight size={17}/></Link></div><div className="hero-footnote"><span>DATA</span><span className="mini-line"/><span>PEMAHAMAN</span><span className="mini-line"/><span>KEPUTUSAN</span></div></div><LightPath/></section>
 <div className="container audience-strip"><span>DIRANCANG UNTUK TIM YANG BERGERAK DENGAN DATA</span><div><b>Brand owner</b><b>Marketplace</b><b>Marketing</b><b>Affiliate</b><b>Produk & R&D</b><b>Agency</b></div></div>
 {publishedProof.length>0&&<section className="container proof">{publishedProof.map(p=><blockquote key={p.name}>{p.quote}<cite>{p.name} · {p.company}</cite></blockquote>)}</section>}
 <section className="section container problem" id="masalah"><div className="problem-intro"><SectionHeading eyebrow="01 / TANTANGAN BISNIS" title="Banyak laporan. Belum tentu banyak kejelasan."/><p>Data marketplace di satu tempat. Performa affiliate di tempat lain. Hasil riset tersimpan di spreadsheet dan chat. Saat waktunya mengambil keputusan, tim harus menyusun konteks dari awal.</p><Link href="/insights/dari-data-ke-keputusan" className="text-link">Kenali persoalannya<ArrowUpRight size={17}/></Link></div><div className="problem-list">{[[Files,'Informasi tersebar','Waktu habis untuk menggabungkan laporan.'],[Search,'Konteks belum utuh','Angka berubah, tetapi penyebabnya belum jelas.'],[MessagesSquare,'Insight berhenti di diskusi','Temuan belum menjadi tindakan yang terukur.']].map(([Icon,title,description],i)=>{const I=Icon as typeof Files;return <div className="problem-item" key={i}><I size={23}/><div><h3>{title as string}</h3><p>{description as string}</p></div><span>0{i+1}</span></div>})}</div></section>
 <section className="transform-band"><div className="container transform"><div><span className="eyebrow">DARI INFORMASI YANG TERPISAH</span><div className="source-tags"><span>Laporan</span><span>Riset</span><span>Spreadsheet</span><span>Catatan tim</span></div></div><ArrowRight className="transform-arrow"/><div className="transform-core"><span>LUMAWAY</span><strong>Konteks yang terhubung</strong></div><ArrowRight className="transform-arrow"/><div><span className="eyebrow">MENJADI ALUR KEPUTUSAN</span><p>Pahami. Prioritaskan.<br/><strong>Tentukan langkah.</strong></p></div></div></section>
 <section className="section container" id="kenali"><div className="split-heading"><SectionHeading eyebrow="02 / KENALI LUMAWAY" title="Satu ruang kerja. Perspektif yang lebih utuh."/><p>Lumaway dirancang sebagai Business Intelligence Operating Workspace: tempat data, analisis, dan tindak lanjut bertemu. Mulai dari fondasi affiliate dan produk, menuju pemahaman pasar yang lebih luas.</p></div><ProductStories/></section>
 <section className="section ecosystem-section"><div className="container ecosystem-layout"><div className="ecosystem-intro"><SectionHeading eyebrow="EKOSISTEM INTELLIGENCE" title="Terhubung dengan keputusan yang Anda buat." description="Jelajahi fondasi produk dan arah pengembangannya."/><p className="small-copy"><b>Beta</b>: implementasi tersedia pada source, akses mengikuti kesiapan workspace.<br/><b>Direncanakan</b>: arah pengembangan, belum tersedia.</p><Link href="/roadmap" className="text-link">Lihat arah pengembangan<ArrowUpRight size={17}/></Link></div><CapabilityList/></div></section>
 <section className="section container" id="cara-kerja"><div className="split-heading"><SectionHeading eyebrow="03 / CARA KERJA" title="Dari sinyal pertama, sampai langkah berikutnya."/><p>Alur intelligence yang baik tidak berhenti pada visualisasi. Setiap tahap memberi konteks untuk tahap berikutnya.</p></div><Workflow/></section>
 <section className="rnd-section"><div className="container rnd-layout"><div><span className="eyebrow">MARKETING & PRODUCT R&D</span><h2>Riset yang punya<br/>arah. Strategi yang<br/>bisa dipelajari.</h2><p>Temukan pertanyaan yang tepat. Bangun hipotesis dari bukti. Jalankan eksperimen, lalu pelajari hasilnya bersama tim.</p><Link href="/solutions/product-rnd" className="text-link light-link">Jelajahi pendekatan R&D<ArrowUpRight size={17}/></Link></div><div className="rnd-cycle">{[['01','Riset & bukti','Apa yang perlu kita pahami?'],['02','Hipotesis','Apa yang ingin kita uji?'],['03','Eksperimen','Tindakan apa yang akan dijalankan?'],['04','Evaluasi & perbaikan','Apa yang kita pelajari?']].map(([n,t,p])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div><ArrowUpRight size={20}/></div>)}<span className="rnd-caption">KERANGKA KERJA • PLAN → DO → REVIEW → IMPROVE</span></div></div></section>
 <section className="section container"><SectionHeading eyebrow="04 / RELEVAN UNTUK TIM ANDA" title="Beda peran. Satu kebutuhan akan kejelasan."/><UseCases/></section>
 <section className="section comparison-section"><div className="container"><div className="split-heading"><SectionHeading eyebrow="CARA PANDANG YANG LEBIH LENGKAP" title="Laporan menjelaskan kondisi. Konteks membantu menentukan arah."/><p>Lumaway menambahkan ruang untuk memahami dan menindaklanjuti informasi, dengan cakupan yang mengikuti kemampuan setiap modul.</p></div><div className="comparison-table"><table><caption>Perbandingan pendekatan kerja</caption><thead><tr><th>Alur kerja</th><th>Proses manual</th><th>Pendekatan Lumaway</th></tr></thead><tbody>{[['Analisis affiliate','Menyusun ulang file dan catatan','Laporan unggahan & Creator 360 · Beta'],['Konteks produk','Pencocokan SKU secara terpisah','Master produk & analisis data · Beta'],['Penyusunan insight','Merangkum laporan secara manual','AI Analytics dengan validasi tim · Beta'],['Tindak lanjut','Berpindah dari laporan ke catatan tugas','Kanban untuk pengelolaan pekerjaan · Beta'],['Riset pasar & kompetitor','Pengamatan dan pencatatan terpisah','Market & Competitor Intelligence · Direncanakan']].map(row=><tr key={row[0]}>{row.map((x,i)=>i===0?<th key={i}>{x}</th>:<td key={i}>{x}</td>)}</tr>)}</tbody></table></div></div></section>
 <section className="section container"><div className="heading-with-link"><SectionHeading eyebrow="LUMAWAY INSIGHTS" title="Perspektif untuk keputusan yang lebih baik."/><Link href="/insights" className="text-link">Semua wawasan<ArrowUpRight size={17}/></Link></div><ArticleCards/></section>
 <section className="container pricing-preview"><div><span className="eyebrow">AKSES SESUAI KEBUTUHAN</span><h2>Mulai dari kebutuhan bisnis Anda.</h2><p>Diskusikan modul, jumlah pengguna, dan kebutuhan data sebelum menentukan akses yang sesuai.</p></div><ButtonLink href="/pricing" secondary event="pricing_plan_click">Lihat informasi akses</ButtonLink></section>
 <section className="section container faq-section"><SectionHeading eyebrow="PERTANYAAN UMUM" title="Kenali sebelum memulai."/><Faq/></section><FinalCta/>
 <JsonLd data={{'@context':'https://schema.org','@type':'Organization',name:'Lumaway',url:site.homeUrl,logo:`${site.url}/brand/luma-mark.png`,slogan:site.tagline}}/><JsonLd data={{'@context':'https://schema.org','@type':'SoftwareApplication',name:'Lumaway',applicationCategory:'BusinessApplication',operatingSystem:'Web',url:site.homeUrl,description:'Business Intelligence Operating Workspace dengan fondasi analisis affiliate, produk, AI, dan pengelolaan pekerjaan.'}}/>
 </>}
