"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
import {LumaLoadingMotion} from "./LumaMotionState";
type Row=Record<string,any>;
const blank={id:null as number|null,topic:"",audience:"pemilik bisnis dan marketer Indonesia",objective:"edukasi",title:"",slug:"",excerpt:"",category:"Insight",seo_title:"",seo_description:"",seo_keywords:[] as string[],content_html:"",image_prompt:"",cover_image_url:"",image_alt:"",external_dofollow_url:"",video_embed_url:"",author_name:"Lumaway"};

export default function AdminBlog({workspaceId}:{workspaceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [form,setForm]=useState<any>(blank);const [posts,setPosts]=useState<Row[]>([]);const [events,setEvents]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
 async function load(){const [p,e]=await Promise.all([supabase.from("luma_blog_posts").select("*").order("created_at",{ascending:false}).limit(200),supabase.from("luma_content_events").select("content_id,event_type,visitor_id,user_id,referrer,created_at").eq("content_type","blog").order("created_at",{ascending:false}).limit(10000)]);setPosts((p.data||[]) as Row[]);setEvents((e.data||[]) as Row[])}
 useEffect(()=>{void load()},[workspaceId]);
 async function request(action:string,payload:any){setBusy(true);try{const r=await fetch("/api/admin/blog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Blog request failed");return d}catch(e:any){setStatus(e?.message||"Blog request failed");return null}finally{setBusy(false)}}
 async function generateImage(prompt?:string){const p=String(prompt||form.image_prompt||"").trim();if(!p)return null;const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"generate_image",image_prompt:`Editorial Lumaway blog cover. ${p}`})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Image generation failed");return d.image_url as string}
 async function generate(){if(!form.topic.trim())return setStatus("Topik artikel wajib diisi.");setBusy(true);setStatus("AI menyusun artikel, SEO, image concept, dan visual...");try{const r=await fetch("/api/admin/blog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"generate",...form})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Generate article failed");let imageUrl="";try{imageUrl=await generateImage(d.result.image_prompt)}catch{}setForm((x:any)=>({...x,...d.result,cover_image_url:imageUrl||x.cover_image_url,image_alt:d.result.title||x.image_alt,author_name:"Lumaway"}));setStatus(imageUrl?"Draft AI + visual siap direview.":"Draft AI siap; visual dapat di-generate ulang manual.")}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function image(){setBusy(true);try{const url=await generateImage();if(url)setForm((x:any)=>({...x,cover_image_url:url}));setStatus("Cover image siap dan dapat diedit/generate ulang.")}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function publish(){const d=await request("publish",form);if(d){setStatus(d.updated?"Artikel berhasil diperbarui.":"Artikel dipublikasikan oleh Lumaway.");setForm(blank);await load()}}
 async function unpublish(id:number){const {error}=await supabase.from("luma_blog_posts").update({status:"draft",updated_at:new Date().toISOString()}).eq("id",id);if(error)setStatus(error.message);else{setStatus("Artikel dikembalikan ke draft.");await load()}}
 function edit(row:Row){setForm({...blank,...row,seo_keywords:Array.isArray(row.seo_keywords)?row.seo_keywords:[]});setStatus("Mode edit artikel aktif.");window.scrollTo({top:0,behavior:"smooth"})}
 const metric=(id:number)=>{const e=events.filter(x=>Number(x.content_id)===id);const unique=new Set(e.map(x=>x.visitor_id||x.user_id).filter(Boolean));const refs=new Set(e.map(x=>x.referrer).filter((x:any)=>x&&String(x)!=="null"));return {views:e.filter(x=>x.event_type==="page_view").length,clicks:e.filter(x=>x.event_type==="content_click").length,visitors:unique.size,referrers:refs.size}};
 return <div className="admin-blog-grid"><div className="card"><div className="section-head"><div><h3>AI SEO Blog Studio</h3><p className="muted">Generate artikel + SEO + visual, edit artikel published, dan embed video YouTube/TikTok/social media.</p></div>{form.id&&<button className="secondary" onClick={()=>setForm(blank)}>New Article</button>}</div><div className="grid"><label>Topik<input value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} placeholder="Contoh: Cara membaca GMV affiliate dengan benar"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Insight</option><option>Marketing</option><option>Affiliate</option><option>SEO</option><option>AI</option><option>Business</option><option>Tutorial</option></select></label></div><label>Target Audience<input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><label>Objective<input value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/></label><label>External reference / backlink source<input value={form.external_dofollow_url||""} onChange={e=>setForm({...form,external_dofollow_url:e.target.value})} placeholder="https://..."/></label><button className="secondary" disabled={busy||!form.topic} onClick={()=>void generate()}>✦ Generate SEO Article + Visual</button>{busy&&<LumaLoadingMotion compact label="AI SEO Blog sedang membuat konten" detail="Artikel, meta SEO, image concept, dan cover visual sedang disiapkan."/>}
 <div className="admin-blog-divider"/><div className="grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label></div><label>Excerpt<textarea value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><div className="grid"><label>SEO Title<input value={form.seo_title} onChange={e=>setForm({...form,seo_title:e.target.value})}/></label><label>SEO Description<input value={form.seo_description} onChange={e=>setForm({...form,seo_description:e.target.value})}/></label></div><label>Keywords<input value={(form.seo_keywords||[]).join(", ")} onChange={e=>setForm({...form,seo_keywords:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Article HTML<textarea className="code-textarea" value={form.content_html} onChange={e=>setForm({...form,content_html:e.target.value})}/></label><label>Embed Video URL<input value={form.video_embed_url||""} onChange={e=>setForm({...form,video_embed_url:e.target.value})} placeholder="YouTube, TikTok, Instagram, atau social video URL"/></label><label>Cover image concept<textarea value={form.image_prompt} onChange={e=>setForm({...form,image_prompt:e.target.value})}/></label><div className="grid"><label>Cover Image URL<input value={form.cover_image_url||""} onChange={e=>setForm({...form,cover_image_url:e.target.value})}/></label><label>Image Alt<input value={form.image_alt||""} onChange={e=>setForm({...form,image_alt:e.target.value})}/></label></div><div className="button-row"><button className="secondary" disabled={busy||!form.image_prompt} onClick={()=>void image()}>Generate / Replace Cover</button><button className="primary" disabled={busy||!form.title||!form.content_html} onClick={()=>void publish()}>{form.id?"Update Published Blog":"Publish Blog"}</button></div>{status&&<div className="flash success">{status}</div>}</div>
 <div className="card admin-blog-preview"><h3>Preview</h3>{form.cover_image_url&&<img src={form.cover_image_url} alt={form.image_alt||form.title||"Blog cover"}/>}<small>{form.category} · Posted by Lumaway</small><h2>{form.title||"Article title"}</h2><p>{form.excerpt||"Article excerpt"}</p>{form.video_embed_url&&<a href={form.video_embed_url} target="_blank" rel="noreferrer">Embedded video/source ↗</a>}<div className="blog-html-preview" dangerouslySetInnerHTML={{__html:form.content_html||"<p>Article content preview.</p>"}}/></div>
 <div className="card admin-blog-history"><div className="section-head"><div><h3>Blog Library & Metrics</h3><p className="muted">Page view, click, unique visitor, dan referring source disimpan sebagai raw event untuk analisis audience dan retargeting consent-based.</p></div></div><div className="scroll"><table><thead><tr><th>Title</th><th>Author</th><th>Status</th><th>Views</th><th>Clicks</th><th>Visitors</th><th>Referrers</th><th>Published</th><th></th></tr></thead><tbody>{posts.map(x=>{const m=metric(Number(x.id));return <tr key={x.id}><td><a href={`/web/insights/${x.slug}`} target="_blank">{x.title}</a></td><td>{x.author_name||"Lumaway"}</td><td>{x.status}</td><td>{m.views}</td><td>{m.clicks}</td><td>{m.visitors}</td><td>{m.referrers}</td><td>{x.published_at?new Date(x.published_at).toLocaleString("id-ID"):"-"}</td><td><div className="button-row"><button onClick={()=>edit(x)}>Edit</button><button disabled={x.status!=="published"} onClick={()=>void unpublish(Number(x.id))}>Unpublish</button></div></td></tr>})}</tbody></table></div></div></div>;
}
