"use client";

import { useEffect, useState } from "react";
import { createClient } from "../../lib/supabase-browser";

type Row=Record<string,any>;
const blank={topic:"",audience:"pemilik bisnis dan marketer Indonesia",objective:"edukasi",title:"",slug:"",excerpt:"",category:"Insight",seo_title:"",seo_description:"",seo_keywords:[] as string[],content_html:"",image_prompt:"",cover_image_url:"",external_dofollow_url:""};

export default function AdminBlog({workspaceId}:{workspaceId:string}){
  const supabase=createClient();const [form,setForm]=useState(blank);const [posts,setPosts]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
  async function load(){const {data}=await supabase.from("luma_blog_posts").select("id,slug,title,category,status,published_at,created_at,cover_image_url").order("created_at",{ascending:false}).limit(100);setPosts((data||[]) as Row[])}useEffect(()=>{void load()},[workspaceId]);
  async function request(action:string,payload:any){setBusy(true);try{const r=await fetch("/api/admin/blog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Blog request failed");return d}catch(e:any){setStatus(e?.message||"Blog request failed");return null}finally{setBusy(false)}}
  async function generate(){if(!form.topic.trim())return setStatus("Topik artikel wajib diisi.");setStatus("AI menyusun artikel + SEO...");const d=await request("generate",form);if(d){setForm(f=>({...f,...d.result}));setStatus("Draft AI siap direview sebelum publish.")}}
  async function image(){if(!form.image_prompt.trim())return;setBusy(true);try{const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"generate_image",image_prompt:`Editorial blog cover. ${form.image_prompt}`})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Image generation failed");setForm(f=>({...f,cover_image_url:d.image_url}));setStatus("Cover image siap.")}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
  async function publish(){const d=await request("publish",form);if(d){setStatus(`Artikel dipublikasikan: /blog/${d.slug}`);setForm(blank);await load()}}
  async function unpublish(id:number){const {error}=await supabase.from("luma_blog_posts").update({status:"draft",updated_at:new Date().toISOString()}).eq("id",id);if(error)setStatus(error.message);else{setStatus("Artikel dikembalikan ke draft.");await load()}}

  return <div className="admin-blog-grid"><div className="card"><h3>AI SEO Blog Studio</h3><div className="grid"><label>Topik<input value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} placeholder="Contoh: Cara membaca GMV affiliate dengan benar"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Insight</option><option>Marketing</option><option>Affiliate</option><option>SEO</option><option>AI</option><option>Business</option><option>Tutorial</option></select></label></div><label>Target Audience<input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><label>Objective<input value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/></label><label>External reference / dofollow link (opsional)<input value={form.external_dofollow_url} onChange={e=>setForm({...form,external_dofollow_url:e.target.value})} placeholder="https://..."/></label><button className="secondary" disabled={busy||!form.topic} onClick={generate}>✦ Generate SEO Article</button>
    <div className="admin-blog-divider"/><div className="grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label></div><label>Excerpt<textarea value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><div className="grid"><label>SEO Title<input value={form.seo_title} onChange={e=>setForm({...form,seo_title:e.target.value})}/></label><label>SEO Description<input value={form.seo_description} onChange={e=>setForm({...form,seo_description:e.target.value})}/></label></div><label>Keywords<input value={form.seo_keywords.join(", ")} onChange={e=>setForm({...form,seo_keywords:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Article HTML<textarea className="code-textarea" value={form.content_html} onChange={e=>setForm({...form,content_html:e.target.value})}/></label><label>Cover image concept<textarea value={form.image_prompt} onChange={e=>setForm({...form,image_prompt:e.target.value})}/></label><div className="button-row"><button className="secondary" disabled={busy||!form.image_prompt} onClick={image}>Generate Cover</button><button className="primary" disabled={busy||!form.title||!form.content_html} onClick={publish}>Publish Blog</button></div>{status&&<div className="flash success">{status}</div>}</div>
    <div className="card admin-blog-preview"><h3>Preview</h3>{form.cover_image_url&&<img src={form.cover_image_url} alt="Blog cover"/>}<small>{form.category}</small><h2>{form.title||"Article title"}</h2><p>{form.excerpt||"Article excerpt"}</p><div className="blog-html-preview" dangerouslySetInnerHTML={{__html:form.content_html||"<p>Article content preview.</p>"}}/></div>
    <div className="card admin-blog-history"><h3>Blog Library</h3><div className="scroll"><table><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Published</th><th></th></tr></thead><tbody>{posts.map(x=><tr key={x.id}><td><a href={`/blog/${x.slug}`} target="_blank">{x.title}</a></td><td>{x.category}</td><td>{x.status}</td><td>{x.published_at?new Date(x.published_at).toLocaleString("id-ID"):"-"}</td><td><button disabled={x.status!=="published"} onClick={()=>unpublish(x.id)}>Unpublish</button></td></tr>)}</tbody></table></div></div>
  </div>;
}
