"use client";
import {useEffect,useMemo,useState} from "react";import {createClient} from "../../lib/supabase-browser";import OwnerMonitoring360 from "./OwnerMonitoring360";import OwnerFinanceControl from "./OwnerFinanceControl";import OwnerSubscriptionPromo from "./OwnerSubscriptionPromo";import OwnerPlatformHealth from "./OwnerPlatformHealth";import OwnerTutorialControl from "./OwnerTutorialControl";import OwnerSupportDesk from "./OwnerSupportDesk";import AdminBroadcast from "./AdminBroadcast";import AdminBlog from "./AdminBlog";import AdminSocialModeration from "./AdminSocialModeration";import OpenAIIntegration from "./OpenAIIntegration";import XenditIntegration from "./XenditIntegration";import WhatsAppIntegration from "./WhatsAppIntegration";import GoogleCloudIntegration from "./GoogleCloudIntegration";import OwnerCommandCenterSummary from "./OwnerCommandCenterSummary";import OwnerProviderAccounts from "./OwnerProviderAccounts";import OwnerFinancialReports from "./OwnerFinancialReports";import OwnerHppCalculator from "./OwnerHppCalculator";import OwnerKnowledgeVault from "./OwnerKnowledgeVault";import OwnerSystemControl from "./OwnerSystemControl";import MayarIntegration from "./MayarIntegration";import PaymentGatewayControl from "./PaymentGatewayControl";
type Row=Record<string,any>;const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));type NavEvent=CustomEvent<{tab?:string;section?:string}>;
export default function AdminDashboardV3({workspaceId}:{workspaceId:string}){const supabase=useMemo(()=>createClient(),[]);const [tab,setTab]=useState("overview"),[summary,setSummary]=useState<Row>({}),[busy,setBusy]=useState(false);async function load(){setBusy(true);const {data}=await supabase.rpc("get_owner_monitoring_summary");setSummary((data||{}) as Row);setBusy(false)}useEffect(()=>{void load()},[workspaceId]);useEffect(()=>{const handler=(event:Event)=>{const e=event as NavEvent;setTab(e.detail?.tab||"overview");if(e.detail?.section)setTimeout(()=>document.getElementById(e.detail!.section!)?.scrollIntoView({behavior:"smooth",block:"start"}),120)};window.addEventListener("luma-owner-nav",handler as EventListener);return()=>window.removeEventListener("luma-owner-nav",handler as EventListener)},[]);return <section id="administration" className="legacy-page-anchor owner-console"><header className="owner-console-header"><div><span className="owner-kicker">LUMAWAY CONTROL CENTER</span><h1>Business Control Center</h1><p>Command Center menampilkan ringkasan. Pengelolaan detail dipisahkan ke menu sidebar agar fungsi Control Center lebih jelas dan tidak bertumpuk.</p></div><div className="owner-header-actions"><span className="owner-live"><i/>Production</span><button className="secondary" disabled={busy} onClick={()=>load()}>{busy?"Refreshing...":"Refresh"}</button></div></header><div className="owner-health-strip"><Metric label="Users" value={fmt(summary.users)} sub={`${fmt(summary.active_users)} active`}/><Metric label="Workspaces" value={fmt(summary.workspaces)} sub="customer databases"/><Metric label="Creators" value={fmt(summary.creators)} sub={`${fmt(summary.stores)} stores`}/><Metric label="GMV Monitored" value={money(summary.gmv)} sub={`${fmt(summary.orders)} orders`}/><Metric label="API Tokens" value={fmt(summary.api_total_tokens)} sub={`${fmt(summary.api_requests)} calls`}/><Metric label="Open Issues" value={fmt(summary.open_issues)} sub="production"/></div>
 {tab==="overview"&&<OwnerCommandCenterSummary workspaceId={workspaceId}/>}
 {tab==="monitoring"&&<OwnerMonitoring360/>}
 {tab==="support"&&<OwnerSupportDesk workspaceId={workspaceId}/>}
 {tab==="finance"&&<div className="owner-section-stack"><OwnerSubscriptionPromo/><OwnerFinanceControl/></div>}
 {tab==="referral"&&<OwnerFinanceControl/>}
 {tab==="ai"&&<div className="owner-section-stack"><PaymentGatewayControl workspaceId={workspaceId}/><section className="owner-panel"><div className="owner-panel-head"><div><span className="owner-kicker">API KEY</span><h3>Environment Variables</h3><p>Credential server-side untuk provider API. Secret tidak pernah ditampilkan kembali ke browser.</p></div></div><MayarIntegration workspaceId={workspaceId}/></section><OwnerPlatformHealth mode="api"/></div>}
 {tab==="broadcast"&&<AdminBroadcast workspaceId={workspaceId}/>}
 {tab==="content"&&<div className="owner-section-stack"><AdminBlog workspaceId={workspaceId}/><OwnerTutorialControl workspaceId={workspaceId}/></div>}
 {tab==="social"&&<AdminSocialModeration/>}
 {tab==="financial"&&<OwnerFinancialReports workspaceId={workspaceId}/>}
 {tab==="hpp"&&<OwnerHppCalculator workspaceId={workspaceId}/>}
 {tab==="providers"&&<OwnerProviderAccounts/>}
 {tab==="knowledge"&&<OwnerKnowledgeVault/>}
 {tab==="integrations"&&<div className="integrations-stack"><div className="owner-section-title"><div><span className="owner-kicker">PLATFORM CONNECTIONS</span><h2>Integrations</h2><p>Credential sensitif tetap server-side. Operational balance dan renewal berada di Provider Accounts.</p></div></div><PaymentGatewayControl workspaceId={workspaceId}/><GoogleCloudIntegration/><div id="owner-integration-openai"><OpenAIIntegration workspaceId={workspaceId}/></div><div id="owner-integration-xendit"><XenditIntegration workspaceId={workspaceId}/></div><div id="owner-integration-mayar"><MayarIntegration workspaceId={workspaceId}/></div><div id="owner-integration-whatsapp"><WhatsAppIntegration workspaceId={workspaceId}/></div></div>}
 {tab==="system"&&<div className="owner-section-stack"><OwnerSystemControl workspaceId={workspaceId}/><OwnerPlatformHealth mode="system"/></div>}
 </section>}
function Metric({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="owner-metric"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
