"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";

type Props={workspaceId:string;creatorId:number|null;startDate:string;endDate:string;onClose:()=>void};
type Row=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const num=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));

export default function Creator360Modal({workspaceId,creatorId,startDate,endDate,onClose}:Props){
  const supabase=useMemo(()=>createClient(),[]);
  const [data,setData]=useState<Row|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [expanded,setExpanded]=useState(false);const [minimized,setMinimized]=useState(false);const [tab,setTab]=useState("overview");
  const [manual,setManual]=useState<Row>({favorite:false,rating:0,program_status:"Not Joined",top_creator:false,ads_support:0,target_sales:0,target_live:0,target_video:0,video_links:["","",""]});
  useEffect(()=>{if(!creatorId)return;void load()},[creatorId,startDate,endDate,workspaceId]);
  async function load(){setBusy(true);setError("");const {data:d,error:e}=await supabase.rpc("get_creator_360",{p_workspace_id:workspaceId,p_creator_id:creatorId,p_start_date:startDate||null,p_end_date:endDate||null});setBusy(false);if(e)return setError(e.message);const row=Array.isArray(d)?d[0]:d;setData(row||null);if(row?.manual_profile)setManual({...manual,...row.manual_profile,video_links:Array.isArray(row.manual_profile.video_links)?row.manual_profile.video_links:["","",""]});}
  async function saveManual(){if(!creatorId)return;setBusy(true);const {error:e}=await supabase.from("creator_360_profiles").upsert({workspace_id:workspaceId,creator_id:creatorId,favorite:Boolean(manual.favorite),rating:Number(manual.rating||0),program_status:manual.program_status||"Not Joined",top_creator:Boolean(manual.top_creator),ads_support:Number(manual.ads_support||0),target_sales:Number(manual.target_sales||0),target_live:Number(manual.target_live||0),target_video:Number(manual.target_video||0),video_links:(manual.video_links||[]).slice(0,3),updated_at:new Date().toISOString()},{onConflict:"workspace_id,creator_id"});setBusy(false);if(e)return setError(e.message);await load();}
  if(!creatorId)return null;
  const k=data?.kpi||{};const spend=Number(k.product_value_sent||0)+Number(k.shipping_cost||0)+Number(k.commission||0)+Number(manual.ads_support||0);const roi=spend>0?Number(k.gmv||0)/spend:0;
  return <div className={`c360-shell ${expanded?"expanded":""} ${minimized?"minimized":""}`} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
    <div className="c360-window"><div className="c360-bar"><div><strong>Customer 360 · {data?.creator?.name||data?.creator?.username||"Creator"}</strong><small>{startDate||"All data"} → {endDate||"All data"}</small></div><div className="button-row"><button onClick={()=>setMinimized(v=>!v)}>{minimized?"▣":"—"}</button><button onClick={()=>setExpanded(v=>!v)}>{expanded?"↙":"↗"}</button><button onClick={onClose}>×</button></div></div>{!minimized&&<div className="c360-body">
      {busy&&!data?<div className="empty-state"><strong>Loading Customer 360...</strong></div>:error?<div className="flash error">{error}</div>:data&&<>
        <div className="c360-head"><div><div className="c360-avatar">{String(data.creator?.name||"C").slice(0,1).toUpperCase()}</div><div><h2>{data.creator?.name||"-"}</h2><p>@{data.creator?.username||"-"} · {data.creator?.platform||"-"}</p></div></div><button className={manual.favorite?"primary":"secondary"} onClick={()=>setManual({...manual,favorite:!manual.favorite})}>{manual.favorite?"★ Favorite":"☆ Favorite"}</button></div>
        <div className="c360-tabs">{[["overview","Overview"],["sales","Sales & ROI"],["products","Products"],["support","Support"],["stores","Stores"],["profile","Profile & Notes"]].map(([x,l])=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{l}</button>)}</div>
        {tab==="overview"&&<><div className="c360-kpis"><div><span>GMV</span><b>{money(k.gmv)}</b></div><div><span>Orders</span><b>{num(k.orders)}</b></div><div><span>Qty</span><b>{num(k.qty)}</b></div><div><span>Commission</span><b>{money(k.commission)}</b></div><div><span>Spend</span><b>{money(spend)}</b></div><div><span>ROI</span><b>{roi.toFixed(2)}x</b></div><div><span>Points</span><b>{num(k.points)}</b></div><div><span>Samples</span><b>{num(k.samples_sent)}</b></div></div><div className="grid"><div className="card"><h3>Status</h3><p>Top Creator: <b>{manual.top_creator?"Yes":"No"}</b></p><p>Agreement: <b>{data.agreement?.status||"Not Active"}</b></p><p>Program: <b>{manual.program_status||"Not Joined"}</b></p><p>Rating: <b>{Number(manual.rating||0).toFixed(1)}/5</b></p></div><div className="card"><h3>Target</h3><p>Sales: <b>{money(manual.target_sales)}</b></p><p>Live: <b>{num(manual.target_live)}</b></p><p>Video: <b>{num(manual.target_video)}</b></p><p>Top category: <b>{data.top_category||"-"}</b></p></div></div></>}
        {tab==="sales"&&<><div className="c360-kpis"><div><span>GMV</span><b>{money(k.gmv)}</b></div><div><span>Live GMV</span><b>{money(k.live_gmv)}</b></div><div><span>Video GMV</span><b>{money(k.video_gmv)}</b></div><div><span>Showcase GMV</span><b>{money(k.showcase_gmv)}</b></div><div><span>Refund</span><b>{money(k.refund)}</b></div><div><span>Ads Support</span><b>{money(manual.ads_support)}</b></div></div><div className="card"><h3>Cost Composition</h3><p>Value barang dikirim: <b>{money(k.product_value_sent)}</b></p><p>Ongkir: <b>{money(k.shipping_cost)}</b></p><p>Komisi: <b>{money(k.commission)}</b></p><p>Support Ads (manual): <b>{money(manual.ads_support)}</b></p><p>Total Spend: <b>{money(spend)}</b></p><p>ROI = GMV ÷ Spend: <b>{roi.toFixed(2)}x</b></p></div></>}
        {tab==="products"&&<div className="card"><h3>Top Products</h3><Table rows={data.top_products||[]} cols={["product_name","sku","qty","orders","gmv","commission","points"]}/></div>}
        {tab==="support"&&<><div className="card"><h3>Samples & Shipping</h3><Table rows={data.samples||[]} cols={["sent_date","product_name","sku","qty","product_value","sample_status","tracking"]}/></div><div className="card"><h3>Last 3 Video Links</h3>{[0,1,2].map(i=><label key={i}>Video {i+1}<input value={(manual.video_links||[])[i]||""} onChange={e=>{const links=[...(manual.video_links||[])];links[i]=e.target.value;setManual({...manual,video_links:links})}} placeholder="https://..."/></label>)}</div></>}
        {tab==="stores"&&<div className="card"><h3>Affiliated Stores</h3><Table rows={data.stores||[]} cols={["store_name","platform","status","gmv","orders","qty","spend","roi"]}/></div>}
        {tab==="profile"&&<div className="grid"><div className="card"><h3>Creator Profile</h3><p>Phone: <b>{data.creator?.phone||"-"}</b></p><p>Address: <b>{data.creator?.address||"-"}</b></p><p>Social/Profile: {data.creator?.profile_url?<a href={data.creator.profile_url} target="_blank" rel="noreferrer">Open Profile</a>:"-"}</p><p>Payment type: <b>{data.creator?.payment_type||"-"}</b></p><p>Ratecard: <b>{money(data.creator?.ratecard)}</b></p><p>Notes: {data.creator?.notes||"-"}</p></div><div className="card"><h3>Manual Management</h3><label>Rating<select value={manual.rating||0} onChange={e=>setManual({...manual,rating:Number(e.target.value)})}>{[0,1,2,3,4,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Program Status<select value={manual.program_status||"Not Joined"} onChange={e=>setManual({...manual,program_status:e.target.value})}><option>Not Joined</option><option>Invited</option><option>Active</option><option>Paused</option><option>Completed</option></select></label><label className="inline-check"><input type="checkbox" checked={Boolean(manual.top_creator)} onChange={e=>setManual({...manual,top_creator:e.target.checked})}/>Mark as Top Creator</label><label>Ads Support<input type="number" value={manual.ads_support||0} onChange={e=>setManual({...manual,ads_support:e.target.value})}/></label><label>Target Sales<input type="number" value={manual.target_sales||0} onChange={e=>setManual({...manual,target_sales:e.target.value})}/></label><div className="grid"><label>Target Live<input type="number" value={manual.target_live||0} onChange={e=>setManual({...manual,target_live:e.target.value})}/></label><label>Target Video<input type="number" value={manual.target_video||0} onChange={e=>setManual({...manual,target_video:e.target.value})}/></label></div></div></div>}
        <div className="c360-save"><button className="primary" disabled={busy} onClick={saveManual}>Save Customer 360</button></div>
      </>}
    </div>}</div>
  </div>
}
function Table({rows,cols}:{rows:Row[];cols:string[]}){return rows.length?<div className="scroll"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==="gmv"||c==="commission"||c==="spend"||c==="product_value"?money(r[c]):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div>:<div className="empty-state"><strong>Belum ada data.</strong></div>}
