"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";
import Creator360Modal from "./Creator360Modal";

type Props={workspaceId:string};
type KPI={total_creators:number;total_sales_records:number;total_qty:number;total_orders:number;total_gmv:number;total_commission:number;total_products:number;total_cost_product:number;total_shipping:number;total_ads_spend:number;total_spend:number;roi:number;aov:number;avg_daily_creator_sales:number;referral_commission:number};
type RankRow={rank:number;creator_id:number;creator_code:string|null;creator_name:string|null;username:string|null;platform:string|null;qty:number;orders:number;gmv:number;commission:number;total_rows:number};
type StoreRow={store_name:string;platform:string;total_affiliates:number;active_affiliates:number;inactive_affiliates:number;gmv:number;orders:number;qty:number;spend:number;roi:number};
const zero:KPI={total_creators:0,total_sales_records:0,total_qty:0,total_orders:0,total_gmv:0,total_commission:0,total_products:0,total_cost_product:0,total_shipping:0,total_ads_spend:0,total_spend:0,roi:0,aov:0,avg_daily_creator_sales:0,referral_commission:0};
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const number=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
function previousRange(start:string,end:string){if(!start||!end)return {start:"",end:""};const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`);const days=Math.round((e.getTime()-s.getTime())/86400000)+1;const pe=new Date(s);pe.setDate(pe.getDate()-1);const ps=new Date(pe);ps.setDate(ps.getDate()-days+1);return {start:ps.toISOString().slice(0,10),end:pe.toISOString().slice(0,10)}}
function delta(current:any,previous:any){const c=Number(current||0),p=Number(previous||0);if(!p)return c>0?100:0;return ((c-p)/Math.abs(p))*100}
function sortRows<T extends Record<string,any>>(rows:T[],key:string,asc:boolean){return [...rows].sort((a,b)=>{const av=a?.[key],bv=b?.[key];const an=Number(av),bn=Number(bv);if(av!==""&&bv!==""&&Number.isFinite(an)&&Number.isFinite(bn))return(an-bn)*(asc?1:-1);return String(av??"").localeCompare(String(bv??""),"id",{numeric:true,sensitivity:"base"})*(asc?1:-1)})}

export default function LegacyDashboard({workspaceId}:Props){
 const supabase=createClient();const [start,setStart]=useState("");const [end,setEnd]=useState("");const [platform,setPlatform]=useState("");
 const [kpi,setKpi]=useState<KPI>(zero);const [prev,setPrev]=useState<KPI|null>(null);const [ranking,setRanking]=useState<RankRow[]>([]);const [stores,setStores]=useState<StoreRow[]>([]);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [selectedCreator,setSelectedCreator]=useState<number|null>(null);const [rankSort,setRankSort]=useState({key:"rank",asc:true});const [storeSort,setStoreSort]=useState({key:"gmv",asc:false});
 async function load(targetPage=1){setBusy(true);setError("");try{if(start&&end&&start>end)throw new Error("Start Date tidak boleh melewati End Date.");const pr=previousRange(start,end);const calls:any[]=[supabase.rpc("get_dashboard_metrics_v2",{p_workspace_id:workspaceId,p_start_date:start||null,p_end_date:end||null,p_platform:platform||null}),supabase.rpc("get_creator_ranking",{p_workspace_id:workspaceId,p_start_date:start||null,p_end_date:end||null,p_platform:platform||null,p_creator_id:null,p_search:null,p_page:targetPage,p_page_size:50}),supabase.rpc("get_store_dashboard",{p_workspace_id:workspaceId,p_start_date:start||null,p_end_date:end||null,p_platform:platform||null})];if(pr.start)calls.push(supabase.rpc("get_dashboard_metrics_v2",{p_workspace_id:workspaceId,p_start_date:pr.start,p_end_date:pr.end,p_platform:platform||null}));const res=await Promise.all(calls);if(res[0].error)throw res[0].error;if(res[1].error)throw res[1].error;if(res[2].error)throw res[2].error;setKpi((res[0].data?.[0]||zero) as KPI);const rr=(res[1].data||[]) as RankRow[];setRanking(rr);setTotal(rr.length?Number(rr[0].total_rows||0):0);setStores((res[2].data||[]) as StoreRow[]);setPrev(pr.start?((res[3]?.data?.[0]||zero) as KPI):null);setPage(targetPage)}catch(e:any){setError(e?.message||"Gagal memuat dashboard")}finally{setBusy(false)}}
 useEffect(()=>{void load(1)},[workspaceId]);const pages=Math.max(1,Math.ceil(total/50));const sortedRanking=useMemo(()=>sortRows(ranking,rankSort.key,rankSort.asc),[ranking,rankSort]);const sortedStores=useMemo(()=>sortRows(stores,storeSort.key,storeSort.asc),[stores,storeSort]);const toggleRankSort=(key:string)=>setRankSort(v=>({key,asc:v.key===key?!v.asc:true}));const toggleStoreSort=(key:string)=>setStoreSort(v=>({key,asc:v.key===key?!v.asc:true}));
 const cards:[string,keyof KPI,"money"|"number"|"ratio"][]=[
  ["Creator Aktif","total_creators","number"],
  ["GMV","total_gmv","money"],
  ["Orders","total_orders","number"],
  ["Qty Paid","total_qty","number"],
  ["Total Produk","total_products","number"],
  ["Komisi Creator","total_commission","money"],
  ["Spend Budget","total_spend","money"],
  ["ROI","roi","ratio"],
  ["AOV Creator","aov","money"],
  ["Average Sales / Creator / Hari","avg_daily_creator_sales","money"],
  ["Komisi Referral","referral_commission","money"],
  ["Sales Records","total_sales_records","number"]
 ];
 return <section id="dashboard" className="legacy-page-anchor dashboard-page">
  <div className="eyebrow">LUMA AFFILIATE INTELLIGENCE</div><h1>Dashboard Affiliate Specialist & KOL</h1><p className="muted dashboard-intro">Filter periode berlaku ke semua KPI, ranking creator, toko dan Customer 360. Jika Start–End dipilih, KPI otomatis dibandingkan dengan periode sebelumnya dengan panjang hari yang sama.</p>
  <div className="filters"><label>Start <span className="field-note">Opsional</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End <span className="field-note">Opsional</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">All</option><option>TikTok</option><option>Shopee</option><option>Instagram</option></select></label><button className="primary" onClick={()=>load(1)} disabled={busy}>{busy?"Loading...":"Apply"}</button><button className="secondary" onClick={()=>{setStart("");setEnd("");setPlatform("");setPrev(null);setTimeout(()=>load(1),0)}}>Reset</button></div>
  {error&&<div className="flash error">{error}</div>}
  <div className="dashboard-metric-head"><div><h2>Performance Metrics</h2><p>12 KPI utama affiliate performance.</p></div>{prev&&<span>Compared with previous period</span>}</div>
  <div className="dashboard-kpi-grid">{cards.map(([label,key,kind])=><KpiCard key={String(key)} label={label} value={kpi[key]} previous={prev?.[key]} kind={kind}/>)}</div>
  <div className="cost-note">Spend Budget = HPP produk + ongkir + ads + komisi creator. ROI = GMV ÷ Spend Budget.</div>
  <div className="grid dashboard-grid"><div className="card"><div className="section-head"><div><h3>Ranking Creator</h3><p className="muted">Maksimal 50 row / halaman · klik nama atau username creator untuk membuka Customer 360.</p></div></div><div className="scroll"><table><thead><tr>{[["rank","Rank"],["creator_name","Creator"],["platform","Platform"],["qty","Qty"],["orders","Orders"],["gmv","GMV"],["commission","Commission"]].map(([key,label])=><th key={key}><button className="table-sort" onClick={()=>toggleRankSort(key)}>{label}<span>{rankSort.key===key?(rankSort.asc?"↑":"↓"):"↕"}</span></button></th>)}<th></th></tr></thead><tbody>{sortedRanking.map(x=><tr className="creator-rank-row" key={x.creator_id}><td>{x.rank}</td><td><button className="creator-link" onClick={()=>setSelectedCreator(x.creator_id)}><b>{x.creator_name||x.username||"-"}</b><small>{x.creator_code||""}</small></button></td><td>{x.platform||"-"}</td><td>{number(x.qty)}</td><td>{number(x.orders)}</td><td>{money(x.gmv)}</td><td>{money(x.commission)}</td><td><button className="secondary compact" onClick={()=>setSelectedCreator(x.creator_id)}>360°</button></td></tr>)}{!ranking.length&&<tr><td colSpan={8}>Tidak ada data.</td></tr>}</tbody></table></div><div className="pager"><span className="pager-info">Page {page}/{pages} · {number(total)} creator</span><div className="button-row"><button className="secondary" disabled={page<=1||busy} onClick={()=>load(page-1)}>Previous</button><button className="secondary" disabled={page>=pages||busy} onClick={()=>load(page+1)}>Next</button></div></div></div><div className="card"><h3>Cost Breakdown</h3><div className="dashboard-cost-list"><span><em>HPP Produk</em><b>{money(kpi.total_cost_product)}</b></span><span><em>Ongkir</em><b>{money(kpi.total_shipping)}</b></span><span><em>Ads Spend</em><b>{money(kpi.total_ads_spend)}</b></span><span><em>Komisi Creator</em><b>{money(kpi.total_commission)}</b></span><span className="total"><em>Total Spend</em><b>{money(kpi.total_spend)}</b></span></div></div></div>
  <div className="card store-dashboard-card"><div className="section-head"><div><h3>Store Intelligence</h3><p className="muted">Daftar toko dibentuk otomatis dari data upload yang memiliki Store/Shop/Nama Toko.</p></div><span className="role-badge">{stores.length} stores</span></div>{stores.length?<div className="scroll"><table><thead><tr>{[["store_name","Store"],["platform","Platform"],["total_affiliates","Affiliate Total"],["active_affiliates","Active"],["inactive_affiliates","Inactive"],["gmv","GMV"],["orders","Orders"],["qty","Qty"],["spend","Spend"],["roi","ROI"]].map(([key,label])=><th key={key}><button className="table-sort" onClick={()=>toggleStoreSort(key)}>{label}<span>{storeSort.key===key?(storeSort.asc?"↑":"↓"):"↕"}</span></button></th>)}</tr></thead><tbody>{sortedStores.map((x,i)=><tr key={`${x.platform}-${x.store_name}-${i}`}><td><b>{x.store_name}</b></td><td>{x.platform}</td><td>{number(x.total_affiliates)}</td><td>{number(x.active_affiliates)}</td><td>{number(x.inactive_affiliates)}</td><td>{money(x.gmv)}</td><td>{number(x.orders)}</td><td>{number(x.qty)}</td><td>{money(x.spend)}</td><td><b>{Number(x.roi||0).toFixed(2)}x</b></td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>Belum ada nama toko pada data upload.</strong><span>Upload file yang memiliki kolom Store Name, Shop Name, Nama Toko, Toko, Seller Name atau Store ID.</span></div>}</div>
  {selectedCreator&&<Creator360Modal workspaceId={workspaceId} creatorId={selectedCreator} startDate={start} endDate={end} onClose={()=>setSelectedCreator(null)}/>} 
 </section>
}

function KpiCard({label,value,previous,kind}:{label:string;value:any;previous:any;kind:"money"|"number"|"ratio"}){const d=previous===undefined?null:delta(value,previous);const rendered=kind==="money"?money(value):kind==="ratio"?`${Number(value||0).toFixed(2)}x`:number(value);return <div className="dashboard-kpi-card"><small>{label}</small><b>{rendered}</b>{d!==null&&<span className={`kpi-delta ${d>0?"up":d<0?"down":"flat"}`}>{d>0?"↑":d<0?"↓":"→"} {Math.abs(d).toFixed(1)}% <i>vs prev.</i></span>}</div>}
