"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
declare global{interface Window{XLSX?:any}}
type Row=Record<string,any>;
const targets=[["host_username","Host Username"],["host_name","Host Name"],["session_title","Session Title"],["metric_date","Date"],["hour","Hour"],["gmv","GMV"],["orders","Orders"],["qty","Qty"],["active_viewers","Active Viewers"],["peak_viewers","Peak Viewers"],["avg_viewers","Avg Viewers"],["clicks","Clicks"],["impressions","Impressions"],["ctr","CTR"],["cvr","CVR"],["duration_minutes","Duration Minutes"],["campaign_name","Campaign"],["gimmick","Gimmick"]];
async function loadXlsx(){if(window.XLSX)return window.XLSX;await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Parser XLSX gagal dimuat."));document.head.appendChild(s)});return window.XLSX}
async function hash(buffer:ArrayBuffer){const h=await crypto.subtle.digest("SHA-256",buffer);return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const headers=(lines.shift()||"").split(",").map(x=>x.replace(/^"|"$/g,"").trim());return lines.map(line=>{const cells=line.split(",").map(x=>x.replace(/^"|"$/g,"").trim());return Object.fromEntries(headers.map((h,i)=>[h,cells[i]??""]))})}
export default function LiveUploadPanel({workspaceId}:{workspaceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [file,setFile]=useState<File|null>(null),[rows,setRows]=useState<Row[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[history,setHistory]=useState<any[]>([]);
 const headers=Object.keys(rows[0]||{});
 async function loadHistory(){const x=await supabase.from("live_imports").select("*").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(20);setHistory(x.data||[])}
 useEffect(()=>{void loadHistory()},[workspaceId]);
 async function choose(f:File){setFile(f);setMsg("Membaca file...");const buffer=await f.arrayBuffer();let data:Row[]=[];if(f.name.toLowerCase().endsWith(".csv"))data=parseCsv(new TextDecoder().decode(buffer));else{const XLSX=await loadXlsx();const wb=XLSX.read(buffer,{type:"array",cellDates:true});data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:"",raw:true,dateNF:"yyyy-mm-dd"})}setRows(data);const lower=Object.fromEntries(Object.keys(data[0]||{}).map(h=>[h.toLowerCase().replace(/[^a-z0-9]/g,""),h]));const auto:Record<string,string>={};for(const [key,label] of targets){const token=label.toLowerCase().replace(/[^a-z0-9]/g,"");auto[key]=lower[token]||Object.entries(lower).find(([k])=>k.includes(token)||token.includes(k))?.[1]||""}setMapping(auto);setMsg(data.length?data.length+" row siap dipetakan.":"File kosong.")}
 async function submit(){if(!file||!rows.length)return;setBusy(true);setMsg("Mengimport Live Streaming...");try{const buffer=await file.arrayBuffer();const r=await fetch("/api/live/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,filename:file.name,file_hash:await hash(buffer),platform:"TikTok",mapping_overrides:mapping,rows})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Import gagal");setMsg("Import selesai · "+Number(j.persisted_rows||0).toLocaleString("id-ID")+" row tersimpan · "+j.period_start+" s.d. "+j.period_end);setRows([]);setFile(null);await loadHistory();window.dispatchEvent(new CustomEvent("lumaway-live-updated"))}catch(e:any){setMsg(e.message||"Import gagal")}finally{setBusy(false)}}
 return <div className="live-upload-panel">
  <div className="live-upload-hero"><div><span>LIVE DATA PIPELINE</span><h2>Upload Performance Live</h2><p>Upload XLSX/CSV dengan alur File → Mapping → Preview → Import. Data masuk khusus ke Live Streaming, bukan Affiliate.</p></div><label className="live-drop"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&void choose(e.target.files[0])}/><strong>{file?file.name:"Pilih file XLSX/CSV"}</strong><small>GMV, Orders, Viewer, Duration, Campaign, Gimmick</small></label></div>
  {msg&&<div className="live-upload-msg">{msg}</div>}
  {rows.length>0&&<><section className="live-mapping"><header><span>STEP 02</span><h3>Mapping kolom</h3></header><div>{targets.map(([key,label])=><label key={key}>{label}<select value={mapping[key]||""} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Tidak dipetakan</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div></section>
   <section className="live-preview"><header><span>STEP 03</span><h3>Preview 5 baris</h3></header><div className="scroll"><table><thead><tr>{headers.slice(0,8).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((r,i)=><tr key={i}>{headers.slice(0,8).map(h=><td key={h}>{String(r[h]??"")}</td>)}</tr>)}</tbody></table></div><button disabled={busy} onClick={()=>void submit()}>{busy?"Mengimport...":"Import ke Live Streaming"}</button></section></>}
  <section className="live-import-history"><header><span>IMPORT HISTORY</span><h3>Upload Live terbaru</h3></header>{history.length?history.map(x=><article key={x.id}><div><strong>{x.filename}</strong><small>{x.import_id} · {new Date(x.created_at).toLocaleString("id-ID")}</small></div><div><b>{x.persisted_rows} row</b><span className={"status-"+x.status}>{x.status}</span></div></article>):<div className="live-empty">Belum ada upload Live Streaming.</div>}</section>
 </div>
}
