"use client";
import { useEffect,useState } from "react";
type Props={profile:{email:string|null;full_name:string|null;role:string};workspace:{name:string;slug:string;status:string};onLogout:()=>void;};
type Theme="light"|"dark";
const aiNav=[["performance","Performance Analysis"],["creator","Creator Analysis"],["product","Product Analysis"],["trend","Trend Analysis"],["anomaly","Anomaly Detection"],["recommendation","Recommendations"]];
const masterNav=[["#product-master","PD","Product Master"],["#listings","LS","Listings"],["#shipping","SH","Shipping"],["#creator-samples","CS","Creator Samples"],["#ratecard","RC","Ratecard Master"]];
const ownerNav=[["overview","OV","Command Center"],["support","HD","Support Desk"],["finance","FN","Payments & Token"],["referral","RF","Referral & Payout"],["ai","AI","AI & API Usage"],["broadcast","BC","Broadcast & Promo"],["content","CT","Blog & Tutorial"],["social","SM","Social Moderation"],["system","SY","System & Issues"]];
const integrationNav=[["owner-integration-google","GC","Google Cloud"],["owner-integration-openai","OA","OpenAI"],["owner-integration-xendit","XD","Xendit"],["owner-integration-whatsapp","WA","WhatsApp CRM & OTP"]];
function Group({icon,label,children,open=false}:{icon:string;label:string;children:any;open?:boolean}){return <details className="side-group" open={open}><summary><span><span className="nav-ico">{icon}</span><span className="nav-label">{label}</span></span><span className="chevron">⌄</span></summary><div className="side-subnav">{children}</div></details>}
export default function LumaSidebar({profile,workspace,onLogout}:Props){
 const isOwner=profile.role==="admin";const [activeHash,setActiveHash]=useState(isOwner?"#administration":"#dashboard");const [ownerTab,setOwnerTab]=useState("overview");const [collapsed,setCollapsed]=useState(false);const [mobileOpen,setMobileOpen]=useState(false);const [theme,setTheme]=useState<Theme>("light");
 useEffect(()=>{const savedTheme=window.localStorage.getItem("lumaway_theme");const nextTheme:Theme=savedTheme==="dark"||savedTheme==="light"?savedTheme:(window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light");setTheme(nextTheme);document.documentElement.dataset.theme=nextTheme;setCollapsed(window.localStorage.getItem("lumaway_sidebar_collapsed")==="1")},[]);
 useEffect(()=>{const sync=()=>{if(isOwner&&window.location.hash!=="#administration")window.history.replaceState(null,"","#administration");setActiveHash(window.location.hash||(isOwner?"#administration":"#dashboard"));setMobileOpen(false)};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[isOwner]);
 function openAi(type:string){if(window.location.hash!=="#ai-analytics")window.location.hash="ai-analytics";const index=aiNav.findIndex(([key])=>key===type);setTimeout(()=>document.querySelectorAll<HTMLButtonElement>(".ai-type-grid .ai-type-card")[index]?.click(),60);setMobileOpen(false)}
 function openOwner(tab:string,section?:string){const actualTab=tab==="referral"?"finance":tab;setOwnerTab(tab);if(window.location.hash!=="#administration")window.location.hash="administration";setTimeout(()=>window.dispatchEvent(new CustomEvent("luma-owner-nav",{detail:{tab:actualTab,section}})),50);setMobileOpen(false)}
 function toggleTheme(){const next:Theme=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;window.localStorage.setItem("lumaway_theme",next)}
 function toggleCollapsed(){const next=!collapsed;setCollapsed(next);window.localStorage.setItem("lumaway_sidebar_collapsed",next?"1":"0")}
 const closeOnMobile=()=>{if(window.innerWidth<=1024)setMobileOpen(false)};
 return <>
  <button type="button" className="mobile-sidebar-trigger" aria-label="Buka menu Lumaway" onClick={()=>setMobileOpen(true)}><span></span><span></span><span></span></button>
  {mobileOpen&&<button type="button" className="mobile-sidebar-backdrop" aria-label="Tutup menu" onClick={()=>setMobileOpen(false)}/>} 
  <aside className={`sidebar ${isOwner?"owner-sidebar":""} ${collapsed?"is-collapsed":""} ${mobileOpen?"mobile-open":""}`} id="sidebar">
   <div className="brand"><img src="/luma-mark.png" alt="Lumaway" className="brand-mark"/><div className="brand-wordmark"><strong>LUMAWAY<span className="brand-dot">.</span></strong><small>{isOwner?"Owner Control":"Light Up Your Potential."}</small></div></div>
   <div className="sidebar-controls"><button type="button" className="theme-toggle" onClick={toggleTheme} title={theme==="dark"?"Gunakan light mode":"Gunakan night mode"}>{theme==="dark"?"☀":"☾"}<span className="nav-label">{theme==="dark"?"Light":"Night"}</span></button><button type="button" className="sidebar-collapse" onClick={toggleCollapsed} title={collapsed?"Expand sidebar":"Minimize sidebar"}>{collapsed?"›":"‹"}</button><button type="button" className="sidebar-mobile-close" onClick={()=>setMobileOpen(false)} aria-label="Tutup menu">×</button></div>
   {isOwner?<><div className="sidebar-label">OWNER CONTROL</div><nav className="side-nav owner-nav" onClick={closeOnMobile}>{ownerNav.map(([tab,icon,label])=><button type="button" key={tab} className={ownerTab===tab?"active":""} onClick={()=>openOwner(tab,tab==="referral"?"owner-referral-payout":undefined)}><span className="nav-ico owner-nav-ico">{icon}</span><span className="nav-label">{label}</span></button>)}<details className="side-group" open><summary><span><span className="nav-ico owner-nav-ico">IN</span><span className="nav-label">Integrations</span></span><span className="chevron">⌄</span></summary><div className="side-subnav owner-subnav">{integrationNav.map(([section,icon,label])=><button type="button" key={section} onClick={()=>openOwner("integrations",section)}><span>{icon}</span><span>{label}</span></button>)}</div></details></nav></>:<><div className="sidebar-label">WORKSPACE</div><nav className="side-nav user-grouped-nav" onClick={closeOnMobile}><a className={activeHash==="#dashboard"?"active":""} href="#dashboard"><span className="nav-ico">DB</span><span className="nav-label">Dashboard</span></a><Group icon="DS" label="Data & Sync" open><a href="#upload">Upload Center</a><a href="#excel-sync">Excel Sync</a><a href="#database">Database</a></Group><Group icon="CM" label="Creator Management"><a href="#agreements">Agreement</a><a href="#affiliate-support">Affiliate Support</a></Group><details className="side-group" open><summary className={activeHash==="#ai-analytics"?"active":""}><span><span className="nav-ico">AI</span><span className="nav-label">AI Analytics</span></span><span className="chevron">⌄</span></summary><div className="side-subnav">{aiNav.map(([key,label])=><button type="button" key={key} onClick={()=>openAi(key)}>{label}</button>)}</div></details><a href="#promo-studio"><span className="nav-ico">PS</span><span className="nav-label">AI Promo Studio</span></a><a href="#kanban"><span className="nav-ico">KB</span><span className="nav-label">Kanban</span></a><Group icon="TK" label="Tiket Bantuan"><a href="#support-tickets">Status & Riwayat Tiket</a></Group><Group icon="BL" label="Billing & Affiliate"><a href="#billing">Billing & Token</a><a href="#luma-affiliate">Luma Affiliate</a></Group><Group icon="CO" label="Content & Community"><a href="#content-hub">Insight & Blog</a><a href="#social-lumaway">Social Lumaway</a></Group><Group icon="MD" label="Master Data">{masterNav.map(([href,icon,label])=><a key={href} href={href}><span>{icon}</span><span>{label}</span></a>)}</Group></nav></>}
   <div className="sidebar-bottom"><a href={isOwner?"#administration":"#profile"} className="user-chip sidebar-profile-link" onClick={closeOnMobile}><div className="avatar">{(profile.full_name||profile.email||"U").slice(0,1).toUpperCase()}</div><div className="sidebar-user-copy"><strong>{profile.full_name||profile.email}</strong><small>{isOwner?"Owner · Lumaway":"My Profile · "+workspace.name}</small></div></a><button className="logout" onClick={onLogout}><span className="logout-icon">↪</span><span className="nav-label">Logout</span></button></div>
  </aside>
 </>
}
