"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";

type Row=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));

export default function OwnerFinanceControl(){
  const supabase=useMemo(()=>createClient(),[]);
  const [orders,setOrders]=useState<Row[]>([]),[withdrawals,setWithdrawals]=useState<Row[]>([]),[packages,setPackages]=useState<Row[]>([]),[msg,setMsg]=useState("");
  async function load(){const [o,w,p]=await Promise.all([supabase.from("luma_topup_orders").select("*").order("created_at",{ascending:false}).limit(1000),supabase.from("referral_withdrawals").select("*").order("requested_at",{ascending:false}).limit(1000),supabase.from("luma_token_packages").select("*").order("sort_order",{ascending:true})]);setOrders((o.data||[]) as Row[]);setWithdrawals((w.data||[]) as Row[]);setPackages((p.data||[]) as Row[])}
  useEffect(()=>{void load()},[]);
  const revenue=orders.filter(x=>String(x.status).toLowerCase()==="paid").reduce((a,x)=>a+Number(x.amount||0),0);
  const pending=withdrawals.filter(x=>["pending","processing"].includes(String(x.status).toLowerCase()));
  async function savePackage(pkg:Row){const {error}=await supabase.from("luma_token_packages").update({label:String(pkg.label||"").trim(),tokens:Math.max(1,Number(pkg.tokens||1)),price:Math.max(0,Number(pkg.price||0)),status:pkg.status,sort_order:Number(pkg.sort_order||0),updated_at:new Date().toISOString()}).eq("id",pkg.id);setMsg(error?error.message:"Token package diperbarui secara global untuk seluruh user.");if(!error){window.dispatchEvent(new Event("luma-pricing-updated"));await load()}}
  async function payout(row:Row,status:string){const id=Number(row.id);const {error}=await supabase.from("referral_withdrawals").update({status,provider_fee:Number(row.provider_fee||0),processed_at:["paid","failed","rejected"].includes(status)?new Date().toISOString():null}).eq("id",id);if(!error&&status==="paid"&&Number(row.provider_fee||0)>0){const {data:{user}}=await supabase.auth.getUser();await supabase.from("luma_api_usage_events").insert({workspace_id:row.workspace_id,user_id:user?.id||row.user_id,provider:row.provider||"xendit",service:"payout_fee",request_type:"referral_withdrawal_fee",status:"success",reference:String(id),cost_idr:Number(row.provider_fee||0),cost_usd:0,metadata:{withdrawal_user_id:row.user_id,amount:Number(row.amount||0)}})}setMsg(error?error.message:`Withdrawal #${id} → ${status}`);if(!error)await load()}
  return <div className="owner-section-stack">
    <div className="owner-kpi-row"><Metric label="Captured Revenue" value={money(revenue)} sub={`${fmt(orders.length)} top-up orders`}/><Metric label="Pending Payment" value={fmt(orders.filter(x=>x.status==="pending").length)}/><Metric label="Payout Queue" value={fmt(pending.length)} sub={money(pending.reduce((a,x)=>a+Number(x.amount||0),0))}/><Metric label="Paid Payout" value={money(withdrawals.filter(x=>x.status==="paid").reduce((a,x)=>a+Number(x.amount||0),0))}/></div>
    {msg&&<div className="owner-inline-note">{msg}</div>}
    <section id="owner-finance" className="owner-panel"><div className="owner-panel-head"><div><h3>Token Packages · Global Pricing</h3><p>Harga, jumlah token, status, dan urutan paket diambil langsung oleh Billing & Token seluruh user.</p></div><span className="priority-badge p-high">GLOBAL</span></div><div className="owner-package-table owner-package-editor">{packages.map((pkg,i)=><div className="owner-package-row" key={pkg.id}><label>Nama Paket<input value={pkg.label||""} onChange={e=>setPackages(p=>p.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/></label><label>Token<input type="number" min="1" value={pkg.tokens||0} onChange={e=>setPackages(p=>p.map((x,j)=>j===i?{...x,tokens:e.target.value}:x))}/></label><label>Harga (Rp)<input type="number" min="0" step="1000" value={pkg.price||0} onChange={e=>setPackages(p=>p.map((x,j)=>j===i?{...x,price:e.target.value}:x))}/></label><label>Status<select value={pkg.status||"draft"} onChange={e=>setPackages(p=>p.map((x,j)=>j===i?{...x,status:e.target.value}:x))}><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Urutan<input type="number" value={pkg.sort_order||0} onChange={e=>setPackages(p=>p.map((x,j)=>j===i?{...x,sort_order:e.target.value}:x))}/></label><button className="primary" onClick={()=>void savePackage(pkg)}>Save Global</button><small>{fmt(pkg.tokens)} token · {money(pkg.price)}</small></div>)}</div></section>
    <Table title="Payment History" rows={orders} cols={["order_code","user_id","package_tokens","amount","payment_method","payment_provider","status","created_at"]}/>
    <section id="owner-referral-payout" className="owner-panel"><div className="owner-panel-head"><div><h3>Referral Withdrawals</h3><p>Perubahan status diteruskan sebagai notifikasi personal ke user.</p></div></div><div className="owner-table-wrap"><table><thead><tr><th>ID</th><th>User</th><th>Amount</th><th>Channel</th><th>Account</th><th>Provider Fee</th><th>Status</th><th>Action</th></tr></thead><tbody>{withdrawals.map(x=><tr key={x.id}><td>#{x.id}</td><td>{x.user_id}</td><td>{money(x.amount)}</td><td>{x.channel_code||x.payout_method}</td><td>{x.account_number}<small>{x.account_name}</small></td><td><input className="compact-fee-input" type="number" min="0" value={x.provider_fee||0} onChange={e=>setWithdrawals(rows=>rows.map(r=>r.id===x.id?{...r,provider_fee:e.target.value}:r))}/><small>{x.provider||"xendit"}</small></td><td>{x.status}</td><td><div className="button-row"><button disabled={x.status!=="pending"} onClick={()=>payout(x,"processing")}>Process</button><button disabled={!["pending","processing"].includes(x.status)} onClick={()=>payout(x,"paid")}>Paid</button><button disabled={!["pending","processing"].includes(x.status)} onClick={()=>payout(x,"failed")}>Failed</button></div></td></tr>)}</tbody></table></div></section>
  </div>;
}
function Metric({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="owner-metric"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function Table({title,rows,cols}:{title:string;rows:Row[];cols:string[]}){return <section className="owner-panel"><div className="owner-panel-head"><div><h3>{title}</h3><p>{fmt(rows.length)} records</p></div></div><div className="owner-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==="amount"?money(r[c]):c==="created_at"&&r[c]?new Date(r[c]).toLocaleString("id-ID"):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div></section>}
