"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";
import Creator360Modal from "./Creator360Modal";

type Row=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const bytes=(v:any)=>{const n=Number(v||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`};

export default function OwnerMonitoring360(){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<Row>({});const [storage,setStorage]=useState<Row>({});const [stores,setStores]=useState<Row[]>([]);const [creators,setCreators]=useState<Row[]>([]);const [users,setUsers]=useState<Row[]>([]);const [wallets,setWallets]=useState<Row[]>([]);const [apiUsage,setApiUsage]=useState<Row[]>([]);const [monthly,setMonthly]=useState<Row[]>([]);const [tab,setTab]=useState("overview");const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [creatorModal,setCreatorModal]=useState<{workspaceId:string;creatorId:number}|null>(null);const [selectedUser,setSelectedUser]=useState<Row|null>(null);const [user360,setUser360]=useState<Row|null>(null);
 async function load(){setBusy(true);setMsg("");const [s,st,so,cr,u,w,a,m]=await Promise.all([supabase.rpc("get_owner_monitoring_summary"),supabase.rpc("get_owner_storage_summary"),supabase.rpc("get_owner_store_monitoring"),supabase.rpc("get_owner_creator_monitoring",{p_limit:1000}),supabase.from("profiles").select("id,email,full_name,active,position_title,phone,phone_verified_at,created_at").order("created_at",{ascending:false}).limit(2000),supabase.from("luma_token_wallets").select("user_id,month,monthly_limit,used_tokens,bonus_tokens,workspace_id,updated_at").order("updated_at",{ascending:false}).limit(5000),supabase.from("luma_api_usage_events").select("provider,service,request_type,model,input_tokens,output_tokens,total_tokens,status,user_id,workspace_id,created_at").order("created_at",{ascending:false}).limit(1000),supabase.rpc("get_owner_workspace_monthly_preview",{p_limit:100})]);setBusy(false);if(s.error)return setMsg(s.error.message);setSummary(s.data||{});setStorage(st.data||{});setStores((so.data||[]) as Row[]);setCreators((cr.data||[]) as Row[]);setUsers((u.data||[]) as Row[]);setWallets((w.data||[]) as Row[]);setApiUsage((a.data||[]) as Row[]);setMonthly((m.data||[]) as Row[])}
 useEffect(()=>{void load()},[]);const userMap=useMemo(()=>Object.fromEntries(users.map(x=>[x.id,x])),[users]);const latestMonth=monthly[0]?.month||"-";const monthPreview=monthly.filter(x=>x.month===latestMonth).slice(0,10);const avgDb=Number(summary.users||0)>0?Number(storage.database_bytes||0)/Number(summary.users):0;
 async function openUser(u:Row){setSelectedUser(u);setUser360(null);const {data,error}=await supabase.rpc("get_owner_user_360",{p_user_id:u.id});if(error)setMsg(error.message);else setUser360(data||{})}
 const tabs=[["overview","Monitoring"],["stores","Stores"],["creators","Creators"],["users","User 360"],["tokens","Tokens"],["api","API Usage"]];
 return <div className="owner-monitoring-360"><div className="section-head"><div><h2>Owner Monitoring 360</h2><p className="muted">Monitoring seluruh database Lumaway, workspace, creator, toko, token, API dan kapasitas data.</p></div><button className="secondary" disabled={busy} onClick={()=>load()}>{busy?"Refreshing...":"Refresh"}</button></div><div className="admin-tabs owner-monitor-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>{msg&&<div className="flash error">{msg}</div>}
 {tab==="overview"&&<><div className="owner-kpi-grid"><Metric label="Users" value={fmt(summary.users)} sub={`${fmt(summary.active_users)} active`}/><Metric label="Workspaces" value={fmt(summary.workspaces)} sub="customer databases"/><Metric label="Creators" value={fmt(summary.creators)} sub={`${fmt(summary.stores)} stores`}/><Metric label="Sales Rows" value={fmt(summary.sales_rows)} sub={`${fmt(summary.imports)} imports`}/><Metric label="GMV" value={money(summary.gmv)} sub={`${fmt(summary.orders)} orders`}/><Metric label="Database" value={bytes(storage.database_bytes)} sub={`${bytes(avgDb)} avg / user`}/><Metric label="Top Up Revenue" value={money(summary.topup_revenue)}/><Metric label="Referral Commission" value={money(summary.referral_commission_total)}/><Metric label="LUMA Tokens" value={fmt(summary.wallet_available)} sub={`${fmt(summary.wallet_used)} used`}/><Metric label="API Tokens" value={fmt(summary.api_total_tokens)} sub={`${fmt(summary.api_requests)} calls`}/></div><div className="card"><div className="section-head"><div><h3>Monthly Workspace KPI · {latestMonth}</h3><p className="muted">Preview maksimal 10 workspace/user berdasarkan GMV bulan terbaru yang tersedia.</p></div></div><MiniTable rows={monthPreview} cols={["workspace_name","user_email","gmv","orders","qty","commission","creators","products"]}/></div></>}
 {tab==="stores"&&<div className="card"><h3>All Affiliated Stores</h3><MiniTable rows={stores} cols={["workspace_name","store_name","platform","total_affiliates","active_affiliates","inactive_affiliates","gmv","orders","qty","spend","roi"]}/></div>}
 {tab==="creators"&&<div className="card"><div className="section-head"><div><h3>All Creator Database</h3><p className="muted">Klik nama/username creator untuk membuka Customer 360.</p></div></div><div className="scroll"><table><thead><tr><th>Workspace</th><th>Creator</th><th>Platform</th><th>Rating</th><th>Program</th><th>GMV</th><th>Orders</th><th>Commission</th><th>Spend</th><th>ROI</th><th>Points</th><th>Stores</th></tr></thead><tbody>{creators.map(x=><tr key={`${x.workspace_id}-${x.creator_id}`}><td>{x.workspace_name}</td><td><button className="creator-link owner-creator-link" onClick={()=>setCreatorModal({workspaceId:x.workspace_id,creatorId:Number(x.creator_id)})}><b>{x.creator_name||x.username||"-"}</b><small>{x.username&&x.username!==x.creator_name?`@${x.username} · `:""}{x.creator_code||""}</small></button></td><td>{x.platform}</td><td>{Number(x.rating||0).toFixed(1)}</td><td>{x.program_status}</td><td>{money(x.gmv)}</td><td>{fmt(x.orders)}</td><td>{money(x.commission)}</td><td>{money(x.spend)}</td><td>{Number(x.roi||0).toFixed(2)}x</td><td>{fmt(x.points)}</td><td>{fmt(x.store_count)}</td></tr>)}</tbody></table></div></div>}
 {tab==="users"&&<div className="card"><h3>Customer 360 · LUMA Users</h3><div className="scroll"><table><thead><tr><th>User</th><th>Email</th><th>Status</th><th>Phone</th><th>Joined</th><th></th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><b>{x.full_name||"-"}</b><small>{x.position_title||"-"}</small></td><td>{x.email}</td><td>{x.active?"Active":"Inactive"}</td><td>{x.phone_verified_at?"Verified":"-"}</td><td>{x.created_at?new Date(x.created_at).toLocaleDateString("id-ID"):"-"}</td><td><button className="secondary compact" onClick={()=>openUser(x)}>360°</button></td></tr>)}</tbody></table></div></div>}
 {tab==="tokens"&&<div className="card"><h3>Token per User</h3><div className="scroll"><table><thead><tr><th>User</th><th>Month</th><th>Quota</th><th>Used</th><th>Bonus</th><th>Available</th></tr></thead><tbody>{wallets.map((x,i)=>{const u=userMap[x.user_id]||{};const available=Math.max(Number(x.monthly_limit||0)-Number(x.used_tokens||0),0)+Number(x.bonus_tokens||0);return <tr key={`${x.user_id}-${x.month}-${i}`}><td><b>{u.full_name||u.email||x.user_id}</b><small>{u.email||""}</small></td><td>{x.month}</td><td>{fmt(x.monthly_limit)}</td><td>{fmt(x.used_tokens)}</td><td>{fmt(x.bonus_tokens)}</td><td><b>{fmt(available)}</b></td></tr>})}</tbody></table></div></div>}
 {tab==="api"&&<div className="card"><h3>API Usage Monitoring</h3><div className="owner-kpi-grid small"><Metric label="Requests" value={fmt(summary.api_requests)}/><Metric label="Input Tokens" value={fmt(summary.api_input_tokens)}/><Metric label="Output Tokens" value={fmt(summary.api_output_tokens)}/><Metric label="Total Tokens" value={fmt(summary.api_total_tokens)}/></div><MiniTable rows={apiUsage.slice(0,100)} cols={["created_at","provider","service","request_type","model","input_tokens","output_tokens","total_tokens","status"]}/></div>}
 {creatorModal&&<Creator360Modal workspaceId={creatorModal.workspaceId} creatorId={creatorModal.creatorId} startDate="" endDate="" onClose={()=>setCreatorModal(null)}/>} {selectedUser&&<User360Modal user={selectedUser} data={user360} onClose={()=>{setSelectedUser(null);setUser360(null)}}/>}</div>
}
function Metric({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="owner-metric"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function MiniTable({rows,cols}:{rows:Row[];cols:string[]}){return rows.length?<div className="scroll"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{["gmv","commission","spend"].includes(c)?money(r[c]):c==="created_at"&&r[c]?new Date(r[c]).toLocaleString("id-ID"):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div>:<div className="empty-state"><strong>Belum ada data.</strong></div>}
function User360Modal({user,data,onClose}:{user:Row;data:Row|null;onClose:()=>void}){const [expanded,setExpanded]=useState(false);const [min,setMin]=useState(false);const wallets=data?.wallets||[];const available=wallets.reduce((a:number,x:Row)=>a+Math.max(Number(x.monthly_limit||0)-Number(x.used_tokens||0),0)+Number(x.bonus_tokens||0),0);return <div className={`c360-shell owner-user360 ${expanded?"expanded":""} ${min?"minimized":""}`}><div className="c360-window"><div className="c360-bar"><div><strong>User 360 · {user.full_name||user.email}</strong><small>{user.email}</small></div><div className="button-row"><button onClick={()=>setMin(v=>!v)}>{min?"▣":"—"}</button><button onClick={()=>setExpanded(v=>!v)}>{expanded?"↙":"↗"}</button><button onClick={onClose}>×</button></div></div>{!min&&<div className="c360-body">{!data?<div className="empty-state"><strong>Loading user 360...</strong></div>:<><div className="c360-kpis"><div><span>Workspaces</span><b>{fmt((data.workspaces||[]).length)}</b></div><div><span>Token Available</span><b>{fmt(available)}</b></div><div><span>AI Runs</span><b>{fmt(data.ai_runs)}</b></div><div><span>Referral Earned</span><b>{money(data.referral_earned)}</b></div><div><span>API Requests</span><b>{fmt(data.api_usage?.requests)}</b></div><div><span>API Tokens</span><b>{fmt(data.api_usage?.total_tokens)}</b></div></div><div className="grid"><div className="card"><h3>Profile</h3><p>Name: <b>{data.profile?.full_name||"-"}</b></p><p>Email: <b>{data.profile?.email||"-"}</b></p><p>Phone: <b>{data.profile?.phone||"-"}</b></p><p>Position: <b>{data.profile?.position_title||"-"}</b></p><p>Status: <b>{data.profile?.active?"Active":"Inactive"}</b></p></div><div className="card"><h3>Workspace Access</h3>{(data.workspaces||[]).map((x:Row)=><p key={x.id}><b>{x.name}</b> · {x.membership_role}</p>)}</div></div></>}</div>}</div></div>}
