"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
type Row=Record<string,any>;
const blank={id:null,title:"",source_path:"",tags:"",content_markdown:"",status:"active"};
export default function OwnerKnowledgeVault(){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState<any>(blank);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const {data,error}=await supabase.from("luma_knowledge_documents").select("*").order("updated_at",{ascending:false}).limit(300);if(error)setMsg(error.message);else setRows((data||[]) as Row[])}
 useEffect(()=>{void load()},[]);
 async function readFile(file:File|null){if(!file)return;if(!/\.(md|markdown|txt)$/i.test(file.name))return setMsg("Gunakan file Markdown (.md/.markdown) atau .txt dari Obsidian.");const text=await file.text();setForm((x:any)=>({...x,title:x.title||file.name.replace(/\.(md|markdown|txt)$/i,""),source_path:file.name,content_markdown:text}));setMsg("File Obsidian/Markdown dimuat. Review lalu Save Knowledge.")}
 async function save(){if(!form.title.trim()||!form.content_markdown.trim())return setMsg("Title dan isi Markdown wajib diisi.");setBusy(true);const {data:{user}}=await supabase.auth.getUser();const payload={source_type:"obsidian",source_path:form.source_path||null,title:form.title.trim(),content_markdown:form.content_markdown,tags:String(form.tags||"").split(",").map((x:string)=>x.trim()).filter(Boolean),status:form.status||"active",created_by:user?.id||null,updated_at:new Date().toISOString()};let error:any=null;if(form.id){({error}=await supabase.from("luma_knowledge_documents").update(payload).eq("id",form.id))}else{({error}=await supabase.from("luma_knowledge_documents").upsert(payload,{onConflict:"source_type,source_path"}))}setBusy(false);setMsg(error?error.message:"Knowledge Lumaway tersimpan. Luma Support akan menggunakan materi aktif ini sebagai sumber produk/tutorial.");if(!error){setForm(blank);await load()}}
 async function remove(id:number){if(!confirm("Arsipkan knowledge ini?"))return;const {error}=await supabase.from("luma_knowledge_documents").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",id);setMsg(error?error.message:"Knowledge diarsipkan.");if(!error)await load()}
 function edit(row:Row){setForm({id:row.id,title:row.title||"",source_path:row.source_path||"",tags:(row.tags||[]).join(", "),content_markdown:row.content_markdown||"",status:row.status||"active"});window.scrollTo({top:0,behavior:"smooth"})}
 return <div className="owner-section-stack"><section className="owner-panel knowledge-vault"><div className="owner-panel-head"><div><h3>Obsidian-Compatible Lumaway Knowledge Vault</h3><p>Upload Markdown dari Obsidian untuk product knowledge, tutorial, SOP, FAQ, dan troubleshooting. AI Support dibatasi pada knowledge aktif Lumaway.</p></div><span className="priority-badge p-high">{rows.filter(x=>x.status==="active").length} active</span></div><div className="knowledge-import-row"><label className="knowledge-file">Import .md dari Obsidian<input type="file" accept=".md,.markdown,.txt,text/markdown,text/plain" onChange={e=>void readFile(e.target.files?.[0]||null)}/></label><span>Format standar Markdown Obsidian dapat digunakan; attachment lokal tidak otomatis tersinkron.</span></div><div className="grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Vault Path / File<input value={form.source_path} onChange={e=>setForm({...form,source_path:e.target.value})} placeholder="Lumaway/Product/AI Analytics.md"/></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="product, tutorial, billing"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label></div><label>Markdown<textarea className="knowledge-markdown" value={form.content_markdown} onChange={e=>setForm({...form,content_markdown:e.target.value})} placeholder="# Lumaway Product Knowledge\n..."/></label><div className="button-row"><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?"Saving...":form.id?"Update Knowledge":"Save Knowledge"}</button>{form.id&&<button className="secondary" onClick={()=>setForm(blank)}>Cancel Edit</button>}</div>{msg&&<div className="owner-inline-note">{msg}</div>}</section><section className="owner-panel"><div className="owner-panel-head"><div><h3>Knowledge Library</h3><p>Hanya status Active yang masuk ke konteks Luma Support.</p></div></div><div className="owner-table-wrap"><table><thead><tr><th>Title</th><th>Path</th><th>Tags</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.source_path||"-"}</td><td>{(x.tags||[]).join(", ")}</td><td>{x.status}</td><td>{x.updated_at?new Date(x.updated_at).toLocaleString("id-ID"):"-"}</td><td><div className="button-row"><button onClick={()=>edit(x)}>Edit</button><button disabled={x.status==="archived"} onClick={()=>void remove(Number(x.id))}>Archive</button></div></td></tr>)}</tbody></table></div></section></div>;
}
