"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
type Row=Record<string,any>;
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
export default function OwnerCommandCenterSummary({workspaceId}:{workspaceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<Row>({});const [system,setSystem]=useState<Row>({});const [providers,setProviders]=useState<Row[]>([]);const [issues,setIssues]=useState<Row[]>([]);const [busy,setBusy]=useState(false);
 async function load(){setBusy(true);const [s,sys,p,i]=await Promise.all([supabase.rpc("get_owner_monitoring_summary"),supabase.from("luma_system_controls").select("*").eq("id",1).maybeSingle(),supabase.from("luma_provider_accounts").select("*").order("provider"),supabase.from("luma_issue_logs").select("id,severity,title,status,created_at").neq("status","resolved").order("created_at",{ascending:false}).limit(8)]);setSummary(s.data||{});setSystem(sys.data||{});setProviders((p.data||[]) as Row[]);setIssues((i.data||[]) as Row[]);setBusy(false)}
 useEffect(()=>{void load()},[workspaceId]);
 const now=Date.now();const providerAlerts=providers.filter(x=>x.status!=="active"||(x.renewal_at&&new Date(x.renewal_at).getTime()-now<7*86400000)||(Number(x.alert_threshold_idr||0)>0&&Number(x.balance_idr||0)<=Number(x.alert_threshold_idr)));
 const open=(tab:string,section?:string)=>window.dispatchEvent(new CustomEvent("luma-owner-nav",{detail:{tab,section}}));
 return <div className="owner-command-summary"><div className="section-head"><div><h2>Command Center</h2><p className="muted">Ringkasan kondisi bisnis dan operasional. Detail lengkap tersedia melalui menu sidebar.</p></div><button className="secondary" disabled={busy} onClick={()=>void load()}>{busy?"Refreshing...":"Refresh Summary"}</button></div>
 <div className="owner-kpi-grid"><Metric label="Users" value={fmt(summary.users)} sub={fmt(summary.active_users)+" active"}/><Metric label="Workspaces" value={fmt(summary.workspaces)} sub="customer databases"/><Metric label="Creators" value={fmt(summary.creators)} sub={fmt(summary.stores)+" stores"}/><Metric label="GMV Monitored" value={money(summary.gmv)} sub={fmt(summary.orders)+" orders"}/><Metric label="API Tokens" value={fmt(summary.api_total_tokens)} sub={fmt(summary.api_requests)+" calls"}/><Metric label="Open Issues" value={fmt(summary.open_issues)} sub="production"/></div>
 <div className="owner-command-grid">
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Platform Status</h3><p>Status global yang dilihat seluruh user.</p></div><span className={`integration-badge ${system.mode==="normal"?"connected":"disconnected"}`}>{String(system.mode||"normal").toUpperCase()}</span></div><strong>{system.title||"Lumaway berjalan normal"}</strong><p className="muted">{system.message||"Semua layanan utama tersedia."}</p><button className="secondary" onClick={()=>open("system","owner-system-control")}>Buka System & Issues</button></section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Needs Attention</h3><p>Provider, renewal, saldo, dan issue yang perlu ditinjau.</p></div><span className="priority-badge p-high">{providerAlerts.length+issues.length}</span></div>{providerAlerts.slice(0,4).map(x=><div className="owner-attention-row" key={x.id}><b>{x.display_name}</b><span>{x.status} · {x.renewal_at?"renew "+new Date(x.renewal_at).toLocaleDateString("id-ID"):"no renewal date"}</span></div>)}{issues.slice(0,4).map(x=><div className="owner-attention-row" key={"i-"+x.id}><b>{x.title}</b><span>{x.severity} · system issue</span></div>)}{!providerAlerts.length&&!issues.length&&<div className="empty-state"><strong>Tidak ada alert kritis.</strong></div>}<div className="button-row"><button className="secondary" onClick={()=>open("providers")}>Provider Accounts</button><button className="secondary" onClick={()=>open("system")}>Issues</button></div></section>
  <section className="owner-panel"><h3>Quick Access</h3><div className="owner-quick-grid"><button onClick={()=>open("monitoring")}>Monitoring 360<span>User, creator, store, token</span></button><button onClick={()=>open("finance")}>Payments & Subscription<span>Pricing, payment, promo</span></button><button onClick={()=>open("ai")}>AI & API Usage<span>Model, token, cost, provider</span></button><button onClick={()=>open("financial")}>Financial Reports<span>Sales, cashflow, margin, P&L</span></button><button onClick={()=>open("hpp")}>HPP Calculator<span>Cost & promo guardrail</span></button><button onClick={()=>open("knowledge")}>Knowledge Vault<span>Product knowledge & tutorial</span></button></div></section>
 </div></div>;
}
function Metric({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="owner-metric"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
