"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";

type Row=Record<string,any>;
export default function OwnerTutorialControl({workspaceId}:{workspaceId:string}){
  const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]),[progress,setProgress]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[msg,setMsg]=useState("");const [form,setForm]=useState({title:"",category:"Getting Started",description:"",youtube_url:"",sort_order:0});
  async function load(){const [t,p,e]=await Promise.all([supabase.from("tutorials").select("*").eq("workspace_id",workspaceId).order("sort_order",{ascending:true}).limit(300),supabase.from("luma_tutorial_progress").select("tutorial_id,user_id,completed,watched_at").eq("workspace_id",workspaceId).eq("completed",true),supabase.from("luma_content_events").select("content_id,event_type,user_id,visitor_id,created_at").eq("content_type","tutorial").eq("workspace_id",workspaceId).limit(10000)]);if(t.error)setMsg(t.error.message);else setRows((t.data||[]) as Row[]);setProgress((p.data||[]) as Row[]);setEvents((e.data||[]) as Row[])}
  useEffect(()=>{void load()},[workspaceId]);
  async function add(){if(!form.title)return setMsg("Title wajib diisi.");const embed=form.youtube_url.replace("watch?v=","embed/").replace("youtu.be/","youtube.com/embed/");const {error}=await supabase.from("tutorials").insert({workspace_id:workspaceId,title:form.title,category:form.category,description:form.description,youtube_url:form.youtube_url||null,embed_url:embed||null,status:"Published",sort_order:Number(form.sort_order||0)});if(error)return setMsg(error.message);setForm({title:"",category:"Getting Started",description:"",youtube_url:"",sort_order:0});setMsg("Tutorial published.");await load()}
  async function remove(id:number){if(!confirm("Hapus tutorial ini?"))return;const {error}=await supabase.from("tutorials").delete().eq("id",id);if(error)return setMsg(error.message);await load()}
  return <section className="owner-panel"><div className="owner-panel-head"><div><h3>Tutorial Library</h3><p>Materi onboarding dan product education yang tampil di user Content Hub.</p></div></div><div className="owner-form-grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>YouTube URL<input value={form.youtube_url} onChange={e=>setForm({...form,youtube_url:e.target.value})}/></label><label>Sort Order<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary" onClick={add}>Publish Tutorial</button>{msg&&<div className="owner-inline-note">{msg}</div>}<div className="owner-table-wrap" style={{marginTop:16}}><table><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Watched Users</th><th>Clicks/Events</th><th>Order</th><th>URL</th><th></th></tr></thead><tbody>{rows.map(x=>{const watched=new Set(progress.filter(p=>Number(p.tutorial_id)===Number(x.id)).map(p=>p.user_id)).size;const clicks=events.filter(e=>Number(e.content_id)===Number(x.id)).length;return <tr key={x.id}><td><b>{x.title}</b><small>{x.description}</small></td><td>{x.category}</td><td>{x.status}</td><td>{watched}</td><td>{clicks}</td><td>{x.sort_order}</td><td>{x.youtube_url||"-"}</td><td><button onClick={()=>remove(x.id)}>Delete</button></td></tr>})}</tbody></table></div></section>;
}
