"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
import {LumaLoadingMotion} from "./LumaMotionState";
type Row=Record<string,any>;
const money=(v:any,c="IDR")=>new Intl.NumberFormat("id-ID",{style:"currency",currency:c,maximumFractionDigits:c==="USD"?4:0}).format(Number(v||0));
export default function OwnerFinancialReports({workspaceId}:{workspaceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [start,setStart]=useState("");const [end,setEnd]=useState("");const [type,setType]=useState("profit_loss");const [reports,setReports]=useState<Row[]>([]);const [expenses,setExpenses]=useState<Row[]>([]);const [expense,setExpense]=useState({expense_date:new Date().toISOString().slice(0,10),category:"operational",vendor:"",description:"",amount:"",currency:"IDR",recurring:false,notes:""});const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [latest,setLatest]=useState<any>(null);
 async function load(){const [r,e]=await Promise.all([supabase.from("luma_financial_reports").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("luma_expense_records").select("*").order("expense_date",{ascending:false}).limit(300)]);setReports((r.data||[]) as Row[]);setExpenses((e.data||[]) as Row[])}
 useEffect(()=>{void load()},[]);
 async function addExpense(){if(!expense.description||!expense.amount)return setMsg("Deskripsi dan amount wajib diisi.");const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("luma_expense_records").insert({...expense,amount:Number(expense.amount),created_by:user?.id||null});setMsg(error?error.message:"Pengeluaran tersimpan.");if(!error){setExpense({...expense,vendor:"",description:"",amount:"",notes:""});await load()}}
 async function removeExpense(id:number){const {error}=await supabase.from("luma_expense_records").delete().eq("id",id);setMsg(error?error.message:"Pengeluaran dihapus.");if(!error)await load()}
 async function generate(){setBusy(true);setMsg("GPT-5.6 Sol menyusun laporan berdasarkan data aktual...");try{const r=await fetch("/api/admin/financial-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"generate",report_type:type,start_date:start,end_date:end})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal membuat report");setLatest(d);setMsg("Laporan selesai dan tersimpan.");await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function download(id:number){const r=await fetch("/api/admin/financial-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"download",id})});if(!r.ok)return setMsg("PDF gagal dibuat.");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`lumaway-financial-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const labels:any={sales:"Total Penjualan",api_cost:"Total Usage API",cashflow:"Cashflow",margin:"Margin",profit_loss:"Laba & Rugi"};
 return <div className="owner-section-stack"><section className="owner-panel"><div className="owner-panel-head"><div><h3>Financial & Sales Reports</h3><p>Laporan penjualan, biaya API, cashflow, margin, dan laba/rugi dengan kalkulasi deterministic + insight GPT-5.6 Sol.</p></div></div><div className="financial-report-tabs">{Object.entries(labels).map(([k,l])=><button key={k} className={type===k?"active":""} onClick={()=>setType(k)}>{String(l)}</button>)}</div><div className="grid"><label>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="primary" disabled={busy} onClick={()=>void generate()}>{busy?"Generating...":"Generate "+labels[type]}</button>{busy&&<LumaLoadingMotion compact label="Menyusun laporan keuangan" detail="Menggabungkan sales, HPP, ongkir, ads, komisi, biaya API, dan expense lalu menyusun insight."/>}{latest&&<div className="financial-snapshot"><div><span>Sales / GMV</span><b>{money(latest.metrics?.sales)}</b></div><div><span>Direct Cost</span><b>{money(latest.metrics?.direct_cost)}</b></div><div><span>API Cost</span><b>{money(latest.metrics?.api_cost_idr)}</b><small>{money(latest.metrics?.api_cost_usd,"USD")}</small></div><div><span>Margin</span><b>{Number(latest.metrics?.margin_pct||0).toFixed(2)}%</b></div><div><span>Profit / Loss</span><b>{money(latest.metrics?.profit_loss)}</b></div></div>}{latest?.insight&&<div className="card financial-ai-insight"><h4>AI Insight</h4><p>{latest.insight.executive_summary}</p><ul>{(latest.insight.key_findings||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>}{msg&&<div className="owner-inline-note">{msg}</div>}</section>
 <section className="owner-panel"><div className="owner-panel-head"><div><h3>Expense Ledger</h3><p>Tambahkan pengeluaran operasional yang belum otomatis terbaca dari database/API.</p></div></div><div className="expense-form"><label>Tanggal<input type="date" value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})}/></label><label>Kategori<input value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}/></label><label>Vendor<input value={expense.vendor} onChange={e=>setExpense({...expense,vendor:e.target.value})}/></label><label>Deskripsi<input value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})}/></label><label>Amount<input type="number" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Currency<select value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value})}><option>IDR</option><option>USD</option></select></label><label className="inline-check"><input type="checkbox" checked={expense.recurring} onChange={e=>setExpense({...expense,recurring:e.target.checked})}/>Recurring</label><label>Notes<input value={expense.notes} onChange={e=>setExpense({...expense,notes:e.target.value})}/></label><button className="primary" onClick={()=>void addExpense()}>Save Expense</button></div><div className="owner-table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Vendor</th><th>Description</th><th>Amount</th><th>Notes</th><th></th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{x.expense_date}</td><td>{x.category}</td><td>{x.vendor||"-"}</td><td>{x.description}</td><td>{money(x.amount,x.currency||"IDR")}</td><td>{x.notes||"-"}</td><td><button onClick={()=>void removeExpense(Number(x.id))}>Delete</button></td></tr>)}</tbody></table></div></section>
 <section className="owner-panel"><h3>Report History</h3><div className="owner-table-wrap"><table><thead><tr><th>Type</th><th>Period</th><th>Model</th><th>Created</th><th></th></tr></thead><tbody>{reports.map(x=><tr key={x.id}><td>{labels[x.report_type]||x.report_type}</td><td>{x.period_start||"All"} → {x.period_end||"All"}</td><td>{x.model||"-"}</td><td>{new Date(x.created_at).toLocaleString("id-ID")}</td><td><button onClick={()=>void download(Number(x.id))}>Download PDF</button></td></tr>)}</tbody></table></div></section></div>;
}
