"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase-browser";

type Row=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const bytes=(v:any)=>{const n=Number(v||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`};

export default function OwnerMonitoring360(){
  const supabase=useMemo(()=>createClient(),[]);
  const [summary,setSummary]=useState<Row>({});const [storage,setStorage]=useState<Row>({});const [stores,setStores]=useState<Row[]>([]);const [creators,setCreators]=useState<Row[]>([]);const [users,setUsers]=useState<Row[]>([]);const [wallets,setWallets]=useState<Row[]>([]);const [apiUsage,setApiUsage]=useState<Row[]>([]);const [services,setServices]=useState<Row[]>([]);const [selectedUser,setSelectedUser]=useState<Row|null>(null);const [user360,setUser360]=useState<Row|null>(null);const [tab,setTab]=useState("overview");const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
  const [serviceForm,setServiceForm]=useState({provider:"",service_name:"",category:"SaaS",plan_name:"",billing_cycle:"monthly",amount:"",currency:"IDR",next_billing_date:"",status:"active",notes:""});

  async function load(){setBusy(true);setMsg("");const [s,st,so,cr,u,w,a,sv]=await Promise.all([
    supabase.rpc("get_owner_monitoring_summary"),supabase.rpc("get_owner_storage_summary"),supabase.rpc("get_owner_store_monitoring"),supabase.rpc("get_owner_creator_monitoring",{p_limit:1000}),
    supabase.from("profiles").select("id,email,full_name,active,position_title,phone,phone_verified_at,created_at").order("created_at",{ascending:false}).limit(2000),
    supabase.from("luma_token_wallets").select("user_id,month,monthly_limit,used_tokens,bonus_tokens,workspace_id,updated_at").order("updated_at",{ascending:false}).limit(5000),
    supabase.from("luma_api_usage_events").select("provider,service,request_type,model,input_tokens,output_tokens,total_tokens,status,user_id,workspace_id,created_at").order("created_at",{ascending:false}).limit(1000),
    supabase.from("owner_service_subscriptions").select("*").order("next_billing_date",{ascending:true}),
  ]);setBusy(false);
    if(s.error)return setMsg(s.error.message);setSummary(s.data||{});setStorage(st.data||{});setStores((so.data||[]) as Row[]);setCreators((cr.data||[]) as Row[]);setUsers((u.data||[]) as Row[]);setWallets((w.data||[]) as Row[]);setApiUsage((a.data||[]) as Row[]);setServices((sv.data||[]) as Row[]);
  }
  useEffect(()=>{void load()},[]);
  const userMap=useMemo(()=>Object.fromEntries(users.map(x=>[x.id,x])),[users]);
  const monthlyServices=services.filter(x=>x.status==="active").reduce((sum,x)=>sum+(x.billing_cycle==="yearly"?Number(x.amount||0)/12:Number(x.amount||0)),0);
  async function openUser(u:Row){setSelectedUser(u);setUser360(null);const {data,error}=await supabase.rpc("get_owner_user_360",{p_user_id:u.id});if(error)setMsg(error.message);else setUser360(data||{})}
  async function addService(){if(!serviceForm.provider||!serviceForm.service_name)return setMsg("Provider dan service wajib diisi.");const {error}=await supabase.from("owner_service_subscriptions").insert({...serviceForm,amount:Number(serviceForm.amount||0),next_billing_date:serviceForm.next_billing_date||null});if(error)return setMsg(error.message);setServiceForm({provider:"",service_name:"",category:"SaaS",plan_name:"",billing_cycle:"monthly",amount:"",currency:"IDR",next_billing_date:"",status:"active",notes:""});setMsg("Langganan ditambahkan.");await load()}
  async function deleteService(id:number){if(!confirm("Hapus data langganan ini?"))return;await supabase.from("owner_service_subscriptions").delete().eq("id",id);await load()}
  const tabs=[["overview","Monitoring"],["stores","Stores"],["creators","Creators"],["users","User 360"],["tokens","Tokens"],["api","API Usage"],["services","Subscriptions"]];

  return <div className="owner-monitoring-360">
    <div className="section-head"><div><h2>Owner Monitoring 360</h2><p className="muted">Monitoring seluruh database Lumaway, workspace user, creator, toko, token, API, referral, storage, dan biaya layanan.</p></div><button className="secondary" disabled={busy} onClick={()=>load()}>{busy?"Refreshing...":"Refresh"}</button></div>
    <div className="admin-tabs owner-monitor-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>
    {msg&&<div className="flash error">{msg}</div>}
    {tab==="overview"&&<>
      <div className="owner-kpi-grid"><Metric label="Users" value={fmt(summary.users)} sub={`${fmt(summary.active_users)} active`}/><Metric label="Workspaces" value={fmt(summary.workspaces)} sub="customer databases"/><Metric label="Creators" value={fmt(summary.creators)} sub={`${fmt(summary.stores)} stores`}/><Metric label="Sales Rows" value={fmt(summary.sales_rows)} sub={`${fmt(summary.imports)} imports`}/><Metric label="GMV" value={money(summary.gmv)} sub={`${fmt(summary.orders)} orders`}/><Metric label="Top Up Revenue" value={money(summary.topup_revenue)} sub={`${fmt(summary.topup_paid)} paid`}/><Metric label="Referral Commission" value={money(summary.referral_commission_total)} sub={`${fmt(summary.withdraw_pending_count)} pending payout`}/><Metric label="LUMA Tokens" value={fmt(summary.wallet_available)} sub={`${fmt(summary.wallet_used)} used`}/><Metric label="AI/API" value={fmt(summary.api_total_tokens)} sub={`${fmt(summary.api_requests)} API calls`}/><Metric label="Open Issues" value={fmt(summary.open_issues)} sub={`${fmt(summary.ai_error)} AI errors`}/></div>
      <div className="grid"><div className="card"><h3>Database & Storage</h3><div className="owner-stat-list"><span><b>{bytes(storage.database_bytes)}</b> PostgreSQL database</span><span><b>{bytes(storage.storage_bytes)}</b> Storage objects</span><span><b>{fmt(storage.storage_objects)}</b> uploaded objects</span><span><b>{fmt(summary.agreements)}</b> agreements</span><span><b>{fmt(summary.samples)}</b> creator samples</span><span><b>{fmt(summary.notifications)}</b> broadcasts</span><span><b>{fmt(summary.blog_posts)}</b> blog posts</span><span><b>{fmt(summary.social_posts)}</b> social posts</span></div></div><div className="card"><h3>Referral & Payout</h3><div className="owner-stat-list"><span><b>{money(summary.referral_commission_confirmed)}</b> confirmed commission</span><span><b>{money(summary.withdraw_pending_amount)}</b> pending / processing</span><span><b>{money(summary.withdraw_paid_amount)}</b> paid payout</span><span><b>{fmt(summary.withdraw_failed_count)}</b> failed / rejected tickets</span><span><b>{money(monthlyServices)}</b> estimated monthly platform cost</span></div></div></div>
    </>}
    {tab==="stores"&&<div className="card"><h3>All Affiliated Stores</h3><div className="scroll"><table><thead><tr><th>Workspace</th><th>Store</th><th>Platform</th><th>Affiliates</th><th>Active</th><th>GMV</th><th>Orders</th><th>Qty</th><th>Spend</th><th>ROI</th></tr></thead><tbody>{stores.map((x,i)=><tr key={i}><td>{x.workspace_name}</td><td><b>{x.store_name}</b></td><td>{x.platform}</td><td>{fmt(x.total_affiliates)}</td><td>{fmt(x.active_affiliates)}</td><td>{money(x.gmv)}</td><td>{fmt(x.orders)}</td><td>{fmt(x.qty)}</td><td>{money(x.spend)}</td><td>{Number(x.roi||0).toFixed(2)}x</td></tr>)}</tbody></table></div>{!stores.length&&<div className="empty-state"><strong>Store akan muncul setelah file upload memiliki nama toko.</strong></div>}</div>}
    {tab==="creators"&&<div className="card"><h3>All Creator Database</h3><div className="scroll"><table><thead><tr><th>Workspace</th><th>Creator</th><th>Platform</th><th>Rating</th><th>Program</th><th>GMV</th><th>Orders</th><th>Commission</th><th>Spend</th><th>ROI</th><th>Points</th><th>Stores</th></tr></thead><tbody>{creators.map(x=><tr key={`${x.workspace_name}-${x.creator_id}`}><td>{x.workspace_name}</td><td><b>{x.creator_name||x.username}</b><br/><small>{x.creator_code}</small></td><td>{x.platform}</td><td>{Number(x.rating||0).toFixed(1)}</td><td>{x.program_status}</td><td>{money(x.gmv)}</td><td>{fmt(x.orders)}</td><td>{money(x.commission)}</td><td>{money(x.spend)}</td><td>{Number(x.roi||0).toFixed(2)}x</td><td>{fmt(x.points)}</td><td>{fmt(x.store_count)}</td></tr>)}</tbody></table></div></div>}
    {tab==="users"&&<div className="card"><h3>Customer 360 · LUMA Users</h3><div className="scroll"><table><thead><tr><th>User</th><th>Email</th><th>Status</th><th>Phone</th><th>Joined</th><th></th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><b>{x.full_name||"-"}</b><br/><small>{x.position_title||"-"}</small></td><td>{x.email}</td><td>{x.active?"Active":"Inactive"}</td><td>{x.phone_verified_at?"Verified":"-"}</td><td>{x.created_at?new Date(x.created_at).toLocaleDateString("id-ID"):"-"}</td><td><button className="secondary compact" onClick={()=>openUser(x)}>360°</button></td></tr>)}</tbody></table></div></div>}
    {tab==="tokens"&&<div className="card"><h3>Token per User</h3><div className="scroll"><table><thead><tr><th>User</th><th>Month</th><th>Quota</th><th>Used</th><th>Bonus</th><th>Available</th></tr></thead><tbody>{wallets.map((x,i)=>{const u=userMap[x.user_id]||{};const available=Math.max(Number(x.monthly_limit||0)-Number(x.used_tokens||0),0)+Number(x.bonus_tokens||0);return <tr key={`${x.user_id}-${x.month}-${i}`}><td><b>{u.full_name||u.email||x.user_id}</b><br/><small>{u.email||""}</small></td><td>{x.month}</td><td>{fmt(x.monthly_limit)}</td><td>{fmt(x.used_tokens)}</td><td>{fmt(x.bonus_tokens)}</td><td><b>{fmt(available)}</b></td></tr>})}</tbody></table></div></div>}
    {tab==="api"&&<div className="card"><h3>API Usage Monitoring</h3><div className="owner-kpi-grid small"><Metric label="Requests" value={fmt(summary.api_requests)}/><Metric label="Input Tokens" value={fmt(summary.api_input_tokens)}/><Metric label="Output Tokens" value={fmt(summary.api_output_tokens)}/><Metric label="Total Tokens" value={fmt(summary.api_total_tokens)}/></div><div className="scroll"><table><thead><tr><th>Date</th><th>Provider</th><th>Service</th><th>Type</th><th>Model</th><th>Input</th><th>Output</th><th>Total</th><th>Status</th></tr></thead><tbody>{apiUsage.map((x,i)=><tr key={i}><td>{new Date(x.created_at).toLocaleString("id-ID")}</td><td>{x.provider}</td><td>{x.service}</td><td>{x.request_type||"-"}</td><td>{x.model||"-"}</td><td>{fmt(x.input_tokens)}</td><td>{fmt(x.output_tokens)}</td><td>{fmt(x.total_tokens)}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>}
    {tab==="services"&&<><div className="card"><h3>Paid Services / Infrastructure</h3><p className="muted">Catat biaya Supabase, OpenAI, domain, hosting, VPS, Vercel, WhatsApp, atau layanan lain untuk monitoring bisnis.</p><div className="grid"><label>Provider<input value={serviceForm.provider} onChange={e=>setServiceForm({...serviceForm,provider:e.target.value})} placeholder="Supabase / OpenAI / Vercel"/></label><label>Service<input value={serviceForm.service_name} onChange={e=>setServiceForm({...serviceForm,service_name:e.target.value})} placeholder="Database Pro / API / Domain"/></label><label>Category<select value={serviceForm.category} onChange={e=>setServiceForm({...serviceForm,category:e.target.value})}><option>SaaS</option><option>AI</option><option>Database</option><option>Domain</option><option>Hosting</option><option>VPS</option><option>Messaging</option><option>Other</option></select></label><label>Plan<input value={serviceForm.plan_name} onChange={e=>setServiceForm({...serviceForm,plan_name:e.target.value})}/></label><label>Billing Cycle<select value={serviceForm.billing_cycle} onChange={e=>setServiceForm({...serviceForm,billing_cycle:e.target.value})}><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="one_time">One Time</option></select></label><label>Amount<input type="number" value={serviceForm.amount} onChange={e=>setServiceForm({...serviceForm,amount:e.target.value})}/></label><label>Next Billing<input type="date" value={serviceForm.next_billing_date} onChange={e=>setServiceForm({...serviceForm,next_billing_date:e.target.value})}/></label><label>Status<select value={serviceForm.status} onChange={e=>setServiceForm({...serviceForm,status:e.target.value})}><option>active</option><option>paused</option><option>cancelled</option></select></label></div><label>Notes<textarea value={serviceForm.notes} onChange={e=>setServiceForm({...serviceForm,notes:e.target.value})}/></label><button className="primary" onClick={addService}>+ Add Subscription</button></div><div className="card"><div className="section-head"><h3>Subscription Cost</h3><b>{money(monthlyServices)} / estimated month</b></div><div className="scroll"><table><thead><tr><th>Provider</th><th>Service</th><th>Category</th><th>Plan</th><th>Cycle</th><th>Amount</th><th>Next Billing</th><th>Status</th><th></th></tr></thead><tbody>{services.map(x=><tr key={x.id}><td>{x.provider}</td><td>{x.service_name}</td><td>{x.category}</td><td>{x.plan_name||"-"}</td><td>{x.billing_cycle}</td><td>{money(x.amount)}</td><td>{x.next_billing_date||"-"}</td><td>{x.status}</td><td><button onClick={()=>deleteService(x.id)}>Delete</button></td></tr>)}</tbody></table></div></div></>}
    {selectedUser&&<User360Modal user={selectedUser} data={user360} onClose={()=>{setSelectedUser(null);setUser360(null)}}/>}
  </div>
}

function Metric({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="owner-metric"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function User360Modal({user,data,onClose}:{user:Row;data:Row|null;onClose:()=>void}){const [expanded,setExpanded]=useState(false);const [min,setMin]=useState(false);const wallets=data?.wallets||[];const available=wallets.reduce((a:number,x:Row)=>a+Math.max(Number(x.monthly_limit||0)-Number(x.used_tokens||0),0)+Number(x.bonus_tokens||0),0);return <div className={`c360-shell owner-user360 ${expanded?"expanded":""} ${min?"minimized":""}`}><div className="c360-window"><div className="c360-bar"><div><strong>User 360 · {user.full_name||user.email}</strong><small>{user.email}</small></div><div className="button-row"><button onClick={()=>setMin(v=>!v)}>{min?"▣":"—"}</button><button onClick={()=>setExpanded(v=>!v)}>{expanded?"↙":"↗"}</button><button onClick={onClose}>×</button></div></div>{!min&&<div className="c360-body">{!data?<div className="empty-state"><strong>Loading user 360...</strong></div>:<><div className="c360-kpis"><div><span>Workspaces</span><b>{fmt((data.workspaces||[]).length)}</b></div><div><span>Token Available</span><b>{fmt(available)}</b></div><div><span>AI Runs</span><b>{fmt(data.ai_runs)}</b></div><div><span>Referral Earned</span><b>{money(data.referral_earned)}</b></div><div><span>API Requests</span><b>{fmt(data.api_usage?.requests)}</b></div><div><span>API Tokens</span><b>{fmt(data.api_usage?.total_tokens)}</b></div><div><span>Withdrawals</span><b>{fmt((data.withdrawals||[]).length)}</b></div><div><span>Topups</span><b>{fmt((data.topups||[]).length)}</b></div></div><div className="grid"><div className="card"><h3>Profile</h3><p>Name: <b>{data.profile?.full_name||"-"}</b></p><p>Email: <b>{data.profile?.email||"-"}</b></p><p>Phone: <b>{data.profile?.phone||"-"}</b></p><p>Position: <b>{data.profile?.position_title||"-"}</b></p><p>Status: <b>{data.profile?.active?"Active":"Inactive"}</b></p></div><div className="card"><h3>Workspace Access</h3>{(data.workspaces||[]).map((x:Row)=><p key={x.id}><b>{x.name}</b> · {x.membership_role}</p>)}</div></div><div className="card"><h3>Top Up History</h3><MiniTable rows={(data.topups||[]).slice(0,20)} cols={["order_code","package_tokens","amount","status","payment_provider","created_at"]}/></div><div className="card"><h3>Referral Withdrawal</h3><MiniTable rows={(data.withdrawals||[]).slice(0,20)} cols={["amount","channel_code","status","requested_at","processed_at"]}/></div></>}</div>}</div></div>}
function MiniTable({rows,cols}:{rows:Row[];cols:string[]}){return rows.length?<div className="scroll"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{c==="amount"?money(r[c]):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div>:<div className="empty-state"><strong>Belum ada data.</strong></div>}
