"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
import {LumaLoadingMotion} from "./LumaMotionState";
type Row=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const fields=[["selling_price","Harga Jual"],["product_cost","HPP Produk"],["packaging","Packaging"],["shipping_subsidy","Subsidi Ongkir"],["marketplace_fee_pct","Marketplace Fee %"],["affiliate_commission_pct","Affiliate Commission %"],["ads_per_order","Ads / Order"],["labor_per_order","Tenaga Kerja / Order"],["overhead_per_order","Overhead / Order"],["discount_pct","Diskon Promo %"],["tax_pct","Tax %"],["other_cost","Biaya Lain"]];
export default function OwnerHppCalculator({workspaceId}:{workspaceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const [form,setForm]=useState<any>({name:"Scenario Baru",sku:"",product_name:"",metrics:Object.fromEntries(fields.map(([k])=>[k,0]))});const [rows,setRows]=useState<Row[]>([]);const [result,setResult]=useState<any>(null);const [insight,setInsight]=useState<any>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 async function load(){const {data}=await supabase.from("luma_hpp_scenarios").select("*").order("created_at",{ascending:false}).limit(50);setRows((data||[]) as Row[])}useEffect(()=>{void load()},[]);
 async function calculate(){setBusy(true);setMsg("");try{const r=await fetch("/api/admin/hpp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,...form})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal menghitung HPP.");setResult(d.result);setInsight(d.insight);setMsg("Scenario tersimpan dan dianalisis.");await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const edit=(k:string,v:any)=>setForm({...form,metrics:{...form.metrics,[k]:v}});
 return <div className="owner-section-stack"><section className="owner-panel hpp-calculator"><div className="owner-panel-head"><div><h3>AI HPP & Promo Guardrail</h3><p>Editable cost model untuk memastikan harga jual dan promo tetap mempertahankan contribution margin setelah fee, komisi, ads, tenaga kerja, dan overhead.</p></div></div><div className="grid"><label>Scenario<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>SKU<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Product<input value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/></label></div><div className="hpp-field-grid">{fields.map(([k,l])=><label key={k}>{l}<input type="number" step=".01" value={form.metrics[k]} onChange={e=>edit(k,e.target.value)}/></label>)}</div><button className="primary" disabled={busy} onClick={()=>void calculate()}>{busy?"Analyzing...":"Hitung HPP + Analisis AI"}</button>{busy&&<LumaLoadingMotion compact label="Menghitung HPP dan risiko promo" detail="Kalkulasi matematika dilakukan lebih dulu, lalu GPT-5.6 Sol menjelaskan risiko dan rekomendasi."/>}{result&&<div className="hpp-result-grid"><div><span>Net Revenue</span><b>{money(result.net_revenue)}</b></div><div><span>Total Cost</span><b>{money(result.total_cost)}</b></div><div className={result.is_loss?"loss":"profit"}><span>Contribution Margin</span><b>{money(result.contribution_margin)}</b></div><div><span>Margin %</span><b>{Number(result.margin_pct||0).toFixed(2)}%</b></div><div><span>Break-even Price</span><b>{money(result.break_even_price)}</b></div></div>}{insight&&<div className={`card hpp-ai-insight risk-${String(insight.risk_level||"").toLowerCase()}`}><h4>AI Risk · {insight.risk_level}</h4><p>{insight.summary}</p><ul>{(insight.recommendations||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>}{msg&&<div className="owner-inline-note">{msg}</div>}</section><section className="owner-panel"><h3>Saved Scenarios</h3><div className="owner-table-wrap"><table><thead><tr><th>Name</th><th>SKU</th><th>Margin</th><th>Risk</th><th>Model</th><th>Date</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.sku||"-"}</td><td>{money(x.result?.contribution_margin)} · {Number(x.result?.margin_pct||0).toFixed(2)}%</td><td>{x.ai_insight?.risk_level||"-"}</td><td>{x.model||"-"}</td><td>{new Date(x.created_at).toLocaleString("id-ID")}</td></tr>)}</tbody></table></div></section></div>;
}
