"use client";
import {useEffect,useState} from "react";
type State={mode:string;status_code:number;title:string;message:string;block_user_access:boolean};
const normal:State={mode:"normal",status_code:200,title:"Lumaway berjalan normal",message:"Semua layanan utama tersedia.",block_user_access:false};
export default function OwnerSystemControl({workspaceId}:{workspaceId:string}){
 const [state,setState]=useState<State>(normal);const [password,setPassword]=useState("");const [passwordConfigured,setPasswordConfigured]=useState(false);const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [notify,setNotify]=useState(true);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 async function load(){try{const r=await fetch(`/api/system/status?workspace_id=${encodeURIComponent(workspaceId)}`,{cache:"no-store"});const d=await r.json();if(d.ok){setState({...normal,...d.state});setPasswordConfigured(Boolean(d.password_configured))}}catch{}}
 useEffect(()=>{void load()},[workspaceId]);
 async function setControlPassword(){setBusy(true);setMsg("");try{const r=await fetch("/api/system/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"set_password",current_password:currentPassword,new_password:newPassword})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal menyimpan password.");setPasswordConfigured(true);setCurrentPassword("");setNewPassword("");setMsg("Password kontrol sistem tersimpan aman.")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setMsg("");try{const r=await fetch("/api/system/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,action:"update_state",...state,password,notify_users:notify})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal memperbarui status.");setState({...normal,...d.state});setPassword("");setMsg("Status global Lumaway diperbarui dan notifikasi user diproses.")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <section className="owner-panel system-control-panel"><div className="owner-panel-head"><div><h3>Global System Control</h3><p>Maintenance, degraded service, outage, dan pemulihan untuk seluruh akun user. Perubahan kritis wajib password control.</p></div><span className={`integration-badge ${state.mode==="normal"?"connected":"disconnected"}`}>{state.mode.toUpperCase()}</span></div>
 {!passwordConfigured?<div className="system-password-setup"><h4>Buat Password Control</h4><p>Password ini terpisah dari login dan dibutuhkan setiap kali mengubah status platform.</p><div className="grid"><label>Password Baru<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Minimal 8 karakter"/></label></div><button className="primary" disabled={busy||newPassword.length<8} onClick={()=>void setControlPassword()}>Simpan Password Control</button></div>:<div className="system-control-grid"><label>Mode<select value={state.mode} onChange={e=>{const mode=e.target.value;setState({...state,mode,status_code:mode==="normal"?200:mode==="degraded"?200:503,block_user_access:mode==="maintenance"||mode==="outage"})}}><option value="normal">Normal</option><option value="maintenance">Maintenance</option><option value="degraded">Degraded / Partial Error</option><option value="outage">Outage</option></select></label><label>HTTP Status<input type="number" value={state.status_code} onChange={e=>setState({...state,status_code:Number(e.target.value)})}/></label><label className="system-wide">Judul<input value={state.title} onChange={e=>setState({...state,title:e.target.value})}/></label><label className="system-wide">Penjelasan<textarea value={state.message||""} onChange={e=>setState({...state,message:e.target.value})} placeholder="Contoh: Maintenance database sampai 23:00 WIB. Data user tetap aman."/></label><label className="inline-check"><input type="checkbox" checked={state.block_user_access} onChange={e=>setState({...state,block_user_access:e.target.checked})}/>Hentikan sementara akses user</label><label className="inline-check"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/>Kirim notifikasi ke semua user</label><label className="system-wide">Password Control<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Wajib untuk menerapkan perubahan"/></label><div className="button-row system-wide"><button className="primary" disabled={busy||!password} onClick={()=>void save()}>{busy?"Applying...":"Terapkan Status Global"}</button><button className="secondary" disabled={busy} onClick={()=>void load()}>Refresh</button></div></div>}
 {passwordConfigured&&<details className="system-change-password"><summary>Ganti password control</summary><div className="grid"><label>Password Saat Ini<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Password Baru<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label></div><button className="secondary" disabled={busy||!currentPassword||newPassword.length<8} onClick={()=>void setControlPassword()}>Update Password</button></details>}
 {msg&&<div className={`owner-inline-note ${/gagal|tidak|password.*sesuai/i.test(msg)?"error":""}`}>{msg}</div>}</section>;
}
