"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
type Row=Record<string,any>;
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const usd=(v:any)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:4,maximumFractionDigits:6}).format(Number(v||0));
const idr=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));

export default function OwnerPlatformHealth({mode}:{mode:"api"|"system"}){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<Row>({}),[usage,setUsage]=useState<Row[]>([]),[runs,setRuns]=useState<Row[]>([]),[issues,setIssues]=useState<Row[]>([]),[providers,setProviders]=useState<Row[]>([]),[health,setHealth]=useState<Row>({}),[observability,setObservability]=useState<Row>({}),[performanceBudget,setPerformanceBudget]=useState<Row>({}),[backupDr,setBackupDr]=useState<Row>({}),[rpcSecurity,setRpcSecurity]=useState<Row>({}),[checkpointBusy,setCheckpointBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){const [s,u,r,i,p,h,o,b,d,sec]=await Promise.all([supabase.rpc("get_owner_monitoring_summary"),supabase.from("luma_api_usage_events").select("*").order("created_at",{ascending:false}).limit(2000),supabase.from("ai_analysis_runs").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("luma_issue_logs").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("luma_provider_accounts").select("*").order("provider"),supabase.rpc("luma_owner_system_health_v1"),supabase.rpc("luma_owner_observability_v2"),supabase.rpc("luma_owner_performance_budget_v1"),supabase.rpc("luma_owner_backup_dr_status_v2"),supabase.rpc("luma_owner_rpc_security_inventory_v1")]);setSummary((s.data||{}) as Row);setUsage((u.data||[]) as Row[]);setRuns((r.data||[]) as Row[]);setIssues((i.data||[]) as Row[]);setProviders((p.data||[]) as Row[]);if(!h.error)setHealth((h.data||{}) as Row);if(!o.error)setObservability((o.data||{}) as Row);if(!b.error)setPerformanceBudget((b.data||{}) as Row);if(!d.error)setBackupDr((d.data||{}) as Row);if(!sec.error)setRpcSecurity((sec.data||{}) as Row)}
 useEffect(()=>{void load()},[]);
 async function createCheckpoint(type="manual"){setCheckpointBusy(true);setMsg("");const x=await supabase.rpc("luma_owner_create_backup_checkpoint_v1",{p_checkpoint_type:type,p_notes:"Created from Owner Platform Health"});if(x.error)setMsg(x.error.message);else{setMsg("Backup readiness checkpoint berhasil dibuat.");await load()}setCheckpointBusy(false)}
 async function resolve(id:number){const {error}=await supabase.from("luma_issue_logs").update({status:"resolved",resolved_at:new Date().toISOString()}).eq("id",id);if(error)return setMsg(error.message);await load()}
 if(mode==="api"){
   const totalUsd=usage.reduce((a,x)=>a+Number(x.cost_usd||0),0),totalIdr=usage.reduce((a,x)=>a+Number(x.cost_idr||0),0);
   const models=Object.entries(usage.filter(x=>x.provider==="openai").reduce((m:Record<string,Row>,x)=>{const k=x.model||"unknown";m[k]??={requests:0,tokens:0,cost_usd:0,cost_idr:0};m[k].requests++;m[k].tokens+=Number(x.total_tokens||0);m[k].cost_usd+=Number(x.cost_usd||0);m[k].cost_idr+=Number(x.cost_idr||0);return m},{}));
   const providerUsage=Object.entries(usage.reduce((m:Record<string,Row>,x)=>{const k=x.provider||"unknown";m[k]??={requests:0,tokens:0,cost_usd:0,cost_idr:0,errors:0};m[k].requests++;m[k].tokens+=Number(x.total_tokens||0);m[k].cost_usd+=Number(x.cost_usd||0);m[k].cost_idr+=Number(x.cost_idr||0);if(x.status!=="success")m[k].errors++;return m},{}));
   return <div className="owner-section-stack"><div className="owner-kpi-row"><Metric label="API Requests" value={fmt(summary.api_requests)}/><Metric label="Input Tokens" value={fmt(summary.api_input_tokens)}/><Metric label="Output Tokens" value={fmt(summary.api_output_tokens)}/><Metric label="Total Tokens" value={fmt(summary.api_total_tokens)}/><Metric label="API Cost USD" value={usd(totalUsd)}/><Metric label="API Cost IDR" value={idr(totalIdr)}/><Metric label="AI Runs" value={fmt(summary.ai_runs)}/></div>
    <section className="owner-panel"><div className="owner-panel-head"><div><h3>OpenAI Model Usage</h3><p>Model aktual yang digunakan termasuk fallback otomatis bila model utama gagal.</p></div></div><div className="owner-kpi-grid small">{models.map(([model,v]:any)=><div className="owner-metric" key={model}><span>{model}</span><b>{fmt(v.tokens)} token</b><small>{fmt(v.requests)} request · {usd(v.cost_usd)} · {idr(v.cost_idr)}</small></div>)}</div></section>
    <section className="owner-panel"><div className="owner-panel-head"><div><h3>Provider Health & Failover</h3><p>FlowKirim / Convia / OpenAI / Xendit health. WhatsApp dan OpenAI dapat berpindah provider/model otomatis sesuai routing.</p></div></div><div className="provider-health-grid">{providers.map(p=><article key={p.id} className={`provider-health-card ${p.status}`}><div><b>{p.display_name}</b><span>{p.status}</span></div><small>{p.last_status||"Belum ada health check"} · failures {p.consecutive_failures||0}</small></article>)}</div><div className="owner-table-wrap"><table><thead><tr><th>Provider</th><th>Requests</th><th>Tokens</th><th>Cost USD</th><th>Cost IDR</th><th>Errors</th></tr></thead><tbody>{providerUsage.map(([name,v]:any)=><tr key={name}><td><b>{name}</b></td><td>{fmt(v.requests)}</td><td>{fmt(v.tokens)}</td><td>{usd(v.cost_usd)}</td><td>{idr(v.cost_idr)}</td><td>{fmt(v.errors)}</td></tr>)}</tbody></table></div></section>
    <Table title="API Usage Log" rows={usage} cols={["created_at","provider","service","request_type","model","input_tokens","output_tokens","total_tokens","cost_usd","cost_idr","status"]}/><Table title="AI Analysis Runs" rows={runs} cols={["created_at","run_id","created_by","analysis_type","start_date","end_date","model","status","error_message"]}/></div>;
 }
 const open=issues.filter(x=>String(x.status).toLowerCase()!=="resolved");
 const api=health.api||{},imports=health.imports||{},payments=health.payments||{},db=health.database||{},healthIssues=health.issues||{}; const obsLatency=observability.latency||{},obsServices=observability.services||[],obsProviders=observability.providers||[],obsHourly=observability.hourly||[];
 return <div className="owner-section-stack">
  <section className={"owner-panel system-health-hero status-"+String(health.status||"unknown")}><div className="owner-panel-head"><div><span className="owner-kicker">LIVE SYSTEM HEALTH</span><h3>{String(health.status||"unknown").toUpperCase()}</h3><p>Snapshot production untuk API, import, payment webhook, checkout intent, provider, database, dan issue queue.</p></div><button className="secondary" onClick={()=>void load()}>Refresh Health</button></div><div className="owner-kpi-row"><Metric label="API Error Rate · 15m" value={(Number(api.error_rate_pct||0)).toFixed(2)+"%"}/><Metric label="API Requests · 15m" value={fmt(api.requests_15m)}/><Metric label="Failed Imports · 24h" value={fmt(imports.failed_24h)}/><Metric label="Stale Imports" value={fmt(imports.stale_processing)}/><Metric label="Failed Webhooks · 24h" value={fmt(payments.failed_webhooks_24h)}/><Metric label="Stale Checkout" value={fmt(payments.stale_checkout_intents)}/><Metric label="DB Size" value={Number(db.megabytes||0).toLocaleString("id-ID")+" MB"}/><Metric label="Open Issues" value={fmt(healthIssues.open??open.length)}/></div></section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Observability · 24 Jam</h3><p>Latency percentile, request volume, error, dan service/provider hotspot.</p></div></div><div className="owner-kpi-row"><Metric label="P50 Latency" value={fmt(obsLatency.p50_ms)+" ms"}/><Metric label="P95 Latency" value={fmt(obsLatency.p95_ms)+" ms"}/><Metric label="P99 Latency" value={fmt(obsLatency.p99_ms)+" ms"}/><Metric label="Hourly Buckets" value={fmt(obsHourly.length)}/></div><div className="owner-table-wrap"><table><thead><tr><th>Service</th><th>Requests</th><th>Errors</th><th>Avg Latency</th><th>P95</th></tr></thead><tbody>{obsServices.map((x:Row)=><tr key={x.service}><td><b>{x.service}</b></td><td>{fmt(x.requests)}</td><td>{fmt(x.errors)}</td><td>{fmt(x.avg_latency_ms)} ms</td><td>{fmt(x.p95_latency_ms)} ms</td></tr>)}</tbody></table></div><div className="owner-table-wrap"><table><thead><tr><th>Provider</th><th>Requests</th><th>Errors</th><th>Avg Latency</th><th>Cost USD</th><th>Cost IDR</th></tr></thead><tbody>{obsProviders.map((x:Row)=><tr key={x.provider}><td><b>{x.provider}</b></td><td>{fmt(x.requests)}</td><td>{fmt(x.errors)}</td><td>{fmt(x.avg_latency_ms)} ms</td><td>{usd(x.cost_usd)}</td><td>{idr(x.cost_idr)}</td></tr>)}</tbody></table></div></section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Performance Budget</h3><p>Pass/fail berdasarkan 24 jam telemetry. Minimum sample mencegah keputusan dari data terlalu sedikit.</p></div></div><div className="owner-table-wrap"><table><thead><tr><th>Scope</th><th>Requests</th><th>P95</th><th>Budget P95</th><th>Error</th><th>Budget Error</th><th>Status</th></tr></thead><tbody>{(performanceBudget.checks||[]).map((x:Row)=><tr key={x.scope}><td><b>{x.scope}</b></td><td>{fmt(x.requests)}</td><td>{fmt(x.p95_ms)} ms</td><td>{fmt(x.budget_p95_ms)} ms</td><td>{Number(x.error_rate_pct||0).toFixed(2)}%</td><td>{Number(x.budget_error_rate_pct||0).toFixed(2)}%</td><td><span className={"integration-badge "+(x.status==="pass"?"connected":x.status==="fail"?"disconnected":"")}>{String(x.status||"-").replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Backup & Disaster Recovery</h3><p>Logical checkpoint untuk restore rehearsal. Provider backup/PITR tetap harus diverifikasi di Supabase.</p></div><button className="secondary" disabled={checkpointBusy} onClick={()=>void createCheckpoint("manual")}>{checkpointBusy?"Saving...":"Create Checkpoint"}</button></div><div className="owner-kpi-row"><Metric label="Checkpoint Age" value={backupDr.checkpoint_age_hours==null?"Belum ada":Number(backupDr.checkpoint_age_hours).toFixed(1)+" jam"}/><Metric label="RPO Target" value={(backupDr.recommended_rpo_hours||24)+" jam"}/><Metric label="RTO Target" value={(backupDr.recommended_rto_hours||4)+" jam"}/><Metric label="Checkpoint Fresh" value={backupDr.checkpoint_fresh?"YES":"NO"}/><Metric label="Provider Backup" value="Verify in Supabase"/></div>{backupDr.latest_checkpoint&&<div className="owner-inline-note"><b>Latest checkpoint #{backupDr.latest_checkpoint.id}</b> · {new Date(backupDr.latest_checkpoint.created_at).toLocaleString("id-ID")} · {backupDr.latest_checkpoint.type}. Checkpoint ini bukan pengganti physical backup.</div>}</section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>RPC Security Inventory</h3><p>SECURITY DEFINER diklasifikasikan berdasarkan exposure dan review status, bukan dimatikan secara massal.</p></div></div><div className="owner-kpi-row"><Metric label="SECURITY DEFINER" value={fmt(rpcSecurity.summary?.security_definer)}/><Metric label="Anon Executable" value={fmt(rpcSecurity.summary?.anon_executable)}/><Metric label="Authenticated" value={fmt(rpcSecurity.summary?.authenticated_executable)}/><Metric label="Reviewed" value={fmt(rpcSecurity.summary?.reviewed)}/><Metric label="Needs Review" value={fmt(rpcSecurity.summary?.needs_review)}/><Metric label="Missing Search Path" value={fmt(rpcSecurity.summary?.missing_search_path)}/></div><div className="owner-table-wrap"><table><thead><tr><th>Function</th><th>Exposure</th><th>Anon</th><th>Auth</th><th>Service</th><th>Search Path</th><th>Review</th></tr></thead><tbody>{(rpcSecurity.functions||[]).slice(0,40).map((x:Row)=><tr key={x.function_name+"|"+x.identity_arguments}><td><b>{x.function_name}</b><small>{x.identity_arguments}</small></td><td>{x.exposure_class}</td><td>{x.anon_execute?"yes":"-"}</td><td>{x.authenticated_execute?"yes":"-"}</td><td>{x.service_execute?"yes":"-"}</td><td>{x.has_search_path?"ok":"missing"}</td><td>{x.review_status}</td></tr>)}</tbody></table></div></section>
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Payment & Provider Health</h3><p>Duplicate delivery tidak menjalankan fulfillment dua kali; stale webhook dan checkout tampil di sini.</p></div></div><div className="owner-kpi-grid small"><Metric label="Duplicate Webhook · 24h" value={fmt(payments.duplicate_deliveries_24h)}/><Metric label="Stale Webhook" value={fmt(payments.stale_webhooks)}/><Metric label="Latest Webhook" value={payments.latest_webhook_at?new Date(payments.latest_webhook_at).toLocaleString("id-ID"):"-"}/><Metric label="Latest Import" value={imports.latest_at?new Date(imports.latest_at).toLocaleString("id-ID"):"-"}/></div><div className="provider-health-grid">{(payments.providers||[]).map((p:Row)=><article key={p.provider} className={"provider-health-card "+String(p.health_status||"unknown")}><div><b>{p.provider}</b><span>{p.enabled?"enabled":"disabled"}</span></div><small>{p.health_status||"unknown"}{p.last_error?" · "+String(p.last_error).slice(0,90):""}</small></article>)}</div></section>
  {msg&&<div className="owner-inline-note">{msg}</div>}
  <section className="owner-panel"><div className="owner-panel-head"><div><h3>Bug, Error & UI Queue</h3><p>Resolve setelah perbaikan diverifikasi di production.</p></div></div><div className="owner-table-wrap"><table><thead><tr><th>Severity</th><th>Issue</th><th>Page</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>{issues.map(x=><tr key={x.id}><td>{x.severity}</td><td><b>{x.title}</b><small>{x.details}</small></td><td>{x.page_path||"-"}</td><td>{x.status}</td><td>{x.created_at?new Date(x.created_at).toLocaleString("id-ID"):"-"}</td><td><button disabled={x.status==="resolved"} onClick={()=>resolve(x.id)}>Resolve</button></td></tr>)}</tbody></table></div></section>
 </div>;
}
function Metric({label,value}:{label:string;value:any}){return <div className="owner-metric"><span>{label}</span><b>{value}</b></div>}
function Table({title,rows,cols}:{title:string;rows:Row[];cols:string[]}){return <section className="owner-panel"><div className="owner-panel-head"><div><h3>{title}</h3><p>{fmt(rows.length)} records</p></div></div><div className="owner-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.run_id||i}>{cols.map(c=><td key={c}>{c==="created_at"&&r[c]?new Date(r[c]).toLocaleString("id-ID"):c==="cost_usd"?usd(r[c]):c==="cost_idr"?idr(r[c]):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div></section>}
