"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
type Row=Record<string,any>;
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const usd=(v:any)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:4,maximumFractionDigits:6}).format(Number(v||0));
const idr=(v:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));

export default function OwnerPlatformHealth({mode}:{mode:"api"|"system"}){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<Row>({}),[usage,setUsage]=useState<Row[]>([]),[runs,setRuns]=useState<Row[]>([]),[issues,setIssues]=useState<Row[]>([]),[providers,setProviders]=useState<Row[]>([]),[msg,setMsg]=useState("");
 async function load(){const [s,u,r,i,p]=await Promise.all([supabase.rpc("get_owner_monitoring_summary"),supabase.from("luma_api_usage_events").select("*").order("created_at",{ascending:false}).limit(2000),supabase.from("ai_analysis_runs").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("luma_issue_logs").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("luma_provider_accounts").select("*").order("provider")]);setSummary((s.data||{}) as Row);setUsage((u.data||[]) as Row[]);setRuns((r.data||[]) as Row[]);setIssues((i.data||[]) as Row[]);setProviders((p.data||[]) as Row[])}
 useEffect(()=>{void load()},[]);
 async function resolve(id:number){const {error}=await supabase.from("luma_issue_logs").update({status:"resolved",resolved_at:new Date().toISOString()}).eq("id",id);if(error)return setMsg(error.message);await load()}
 if(mode==="api"){
   const totalUsd=usage.reduce((a,x)=>a+Number(x.cost_usd||0),0),totalIdr=usage.reduce((a,x)=>a+Number(x.cost_idr||0),0);
   const models=Object.entries(usage.filter(x=>x.provider==="openai").reduce((m:Record<string,Row>,x)=>{const k=x.model||"unknown";m[k]??={requests:0,tokens:0,cost_usd:0,cost_idr:0};m[k].requests++;m[k].tokens+=Number(x.total_tokens||0);m[k].cost_usd+=Number(x.cost_usd||0);m[k].cost_idr+=Number(x.cost_idr||0);return m},{}));
   const providerUsage=Object.entries(usage.reduce((m:Record<string,Row>,x)=>{const k=x.provider||"unknown";m[k]??={requests:0,tokens:0,cost_usd:0,cost_idr:0,errors:0};m[k].requests++;m[k].tokens+=Number(x.total_tokens||0);m[k].cost_usd+=Number(x.cost_usd||0);m[k].cost_idr+=Number(x.cost_idr||0);if(x.status!=="success")m[k].errors++;return m},{}));
   return <div className="owner-section-stack"><div className="owner-kpi-row"><Metric label="API Requests" value={fmt(summary.api_requests)}/><Metric label="Input Tokens" value={fmt(summary.api_input_tokens)}/><Metric label="Output Tokens" value={fmt(summary.api_output_tokens)}/><Metric label="Total Tokens" value={fmt(summary.api_total_tokens)}/><Metric label="API Cost USD" value={usd(totalUsd)}/><Metric label="API Cost IDR" value={idr(totalIdr)}/><Metric label="AI Runs" value={fmt(summary.ai_runs)}/></div>
    <section className="owner-panel"><div className="owner-panel-head"><div><h3>OpenAI Model Usage</h3><p>Model aktual yang digunakan termasuk fallback otomatis bila model utama gagal.</p></div></div><div className="owner-kpi-grid small">{models.map(([model,v]:any)=><div className="owner-metric" key={model}><span>{model}</span><b>{fmt(v.tokens)} token</b><small>{fmt(v.requests)} request · {usd(v.cost_usd)} · {idr(v.cost_idr)}</small></div>)}</div></section>
    <section className="owner-panel"><div className="owner-panel-head"><div><h3>Provider Health & Failover</h3><p>FlowKirim / Convia / OpenAI / Xendit health. WhatsApp dan OpenAI dapat berpindah provider/model otomatis sesuai routing.</p></div></div><div className="provider-health-grid">{providers.map(p=><article key={p.id} className={`provider-health-card ${p.status}`}><div><b>{p.display_name}</b><span>{p.status}</span></div><small>{p.last_status||"Belum ada health check"} · failures {p.consecutive_failures||0}</small></article>)}</div><div className="owner-table-wrap"><table><thead><tr><th>Provider</th><th>Requests</th><th>Tokens</th><th>Cost USD</th><th>Cost IDR</th><th>Errors</th></tr></thead><tbody>{providerUsage.map(([name,v]:any)=><tr key={name}><td><b>{name}</b></td><td>{fmt(v.requests)}</td><td>{fmt(v.tokens)}</td><td>{usd(v.cost_usd)}</td><td>{idr(v.cost_idr)}</td><td>{fmt(v.errors)}</td></tr>)}</tbody></table></div></section>
    <Table title="API Usage Log" rows={usage} cols={["created_at","provider","service","request_type","model","input_tokens","output_tokens","total_tokens","cost_usd","cost_idr","status"]}/><Table title="AI Analysis Runs" rows={runs} cols={["created_at","run_id","created_by","analysis_type","start_date","end_date","model","status","error_message"]}/></div>;
 }
 const open=issues.filter(x=>String(x.status).toLowerCase()!=="resolved");
 return <div className="owner-section-stack"><div className="owner-kpi-row"><Metric label="Open Issues" value={fmt(open.length)}/><Metric label="AI Errors" value={fmt(summary.ai_error)}/><Metric label="Sales Rows" value={fmt(summary.sales_rows)}/><Metric label="Imports" value={fmt(summary.imports)}/></div>{msg&&<div className="owner-inline-note">{msg}</div>}<section className="owner-panel"><div className="owner-panel-head"><div><h3>Bug, Error & UI Queue</h3><p>Resolve setelah perbaikan diverifikasi di production.</p></div></div><div className="owner-table-wrap"><table><thead><tr><th>Severity</th><th>Issue</th><th>Page</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>{issues.map(x=><tr key={x.id}><td>{x.severity}</td><td><b>{x.title}</b><small>{x.details}</small></td><td>{x.page_path||"-"}</td><td>{x.status}</td><td>{x.created_at?new Date(x.created_at).toLocaleString("id-ID"):"-"}</td><td><button disabled={x.status==="resolved"} onClick={()=>resolve(x.id)}>Resolve</button></td></tr>)}</tbody></table></div></section></div>;
}
function Metric({label,value}:{label:string;value:any}){return <div className="owner-metric"><span>{label}</span><b>{value}</b></div>}
function Table({title,rows,cols}:{title:string;rows:Row[];cols:string[]}){return <section className="owner-panel"><div className="owner-panel-head"><div><h3>{title}</h3><p>{fmt(rows.length)} records</p></div></div><div className="owner-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.run_id||i}>{cols.map(c=><td key={c}>{c==="created_at"&&r[c]?new Date(r[c]).toLocaleString("id-ID"):c==="cost_usd"?usd(r[c]):c==="cost_idr"?idr(r[c]):String(r[c]??"-")}</td>)}</tr>)}</tbody></table></div></section>}
