"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase-browser";
type Row=Record<string,any>;
const money=(v:any,c="IDR")=>new Intl.NumberFormat("id-ID",{style:"currency",currency:c,maximumFractionDigits:c==="USD"?4:0}).format(Number(v||0));
export default function OwnerProviderAccounts(){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [msg,setMsg]=useState("");const [busy,setBusy]=useState<number|null>(null);
 async function load(){const {data,error}=await supabase.from("luma_provider_accounts").select("*").order("provider");if(error)setMsg(error.message);else setRows((data||[]) as Row[])}
 useEffect(()=>{void load()},[]);
 async function save(row:Row){setBusy(Number(row.id));const {error}=await supabase.from("luma_provider_accounts").update({status:row.status,balance_usd:Number(row.balance_usd||0),balance_idr:Number(row.balance_idr||0),monthly_budget_usd:Number(row.monthly_budget_usd||0),monthly_budget_idr:Number(row.monthly_budget_idr||0),alert_threshold_usd:Number(row.alert_threshold_usd||0),alert_threshold_idr:Number(row.alert_threshold_idr||0),renewal_at:row.renewal_at||null,notes:row.notes||null,updated_at:new Date().toISOString()}).eq("id",row.id);setBusy(null);setMsg(error?error.message:"Provider account diperbarui.");if(!error)await load()}
 const edit=(i:number,key:string,value:any)=>setRows(v=>v.map((x,j)=>j===i?{...x,[key]:value}:x));
 return <div className="owner-section-stack"><section className="owner-panel"><div className="owner-panel-head"><div><h3>Operational Provider Accounts</h3><p>Kelola saldo, renewal, budget, threshold, dan status OpenAI, FlowKirim, Convia, Xendit, Hostinger VPS/domain agar operasional tidak terputus.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>{msg&&<div className="owner-inline-note">{msg}</div>}<div className="provider-account-grid">{rows.map((r,i)=>{const renewal=r.renewal_at?new Date(r.renewal_at).getTime()-Date.now():null;const alert=r.status!=="active"||(renewal!==null&&renewal<7*86400000)||(Number(r.alert_threshold_idr||0)>0&&Number(r.balance_idr||0)<=Number(r.alert_threshold_idr));return <article className={`provider-account-card ${alert?"alert":""}`} key={r.id}><header><div><span>{r.provider}</span><h4>{r.display_name}</h4></div><select value={r.status} onChange={e=>edit(i,"status",e.target.value)}><option value="active">Active</option><option value="warning">Warning</option><option value="paused">Paused</option><option value="error">Error</option><option value="inactive">Inactive</option></select></header><div className="provider-balance"><b>{money(r.balance_idr)}</b><span>{money(r.balance_usd,"USD")}</span></div><div className="grid"><label>Saldo IDR<input type="number" value={r.balance_idr||0} onChange={e=>edit(i,"balance_idr",e.target.value)}/></label><label>Saldo USD<input type="number" step=".01" value={r.balance_usd||0} onChange={e=>edit(i,"balance_usd",e.target.value)}/></label><label>Budget/bln IDR<input type="number" value={r.monthly_budget_idr||0} onChange={e=>edit(i,"monthly_budget_idr",e.target.value)}/></label><label>Alert IDR<input type="number" value={r.alert_threshold_idr||0} onChange={e=>edit(i,"alert_threshold_idr",e.target.value)}/></label><label>Renewal<input type="datetime-local" value={r.renewal_at?String(r.renewal_at).slice(0,16):""} onChange={e=>edit(i,"renewal_at",e.target.value)}/></label></div><label>Catatan<textarea value={r.notes||""} onChange={e=>edit(i,"notes",e.target.value)}/></label><div className="provider-health"><span>Last status: {r.last_status||"-"}</span><span>Failures: {r.consecutive_failures||0}</span></div><button className="primary" disabled={busy===Number(r.id)} onClick={()=>void save(r)}>{busy===Number(r.id)?"Saving...":"Save Account"}</button></article>})}</div></section></div>;
}
