"use client";
import { useEffect, useState } from "react";
type Ticket=Record<string,any>;type Msg=Record<string,any>;
export default function UserTicketCenter({workspaceId}:{workspaceId:string}){
 const [tickets,setTickets]=useState<Ticket[]>([]);const [active,setActive]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function load(ticketId?:string){setLoading(true);try{const q=new URLSearchParams({workspace_id:workspaceId});if(ticketId)q.set("ticket_id",ticketId);const r=await fetch(`/api/support/tickets?${q.toString()}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error();setTickets(d.tickets||[]);setActive(d.active_ticket||null);setMessages(d.messages||[]);setError("")}catch{setError("error, terjadi kesalahan.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(active?.id),30000);return()=>window.clearInterval(t)},[workspaceId,active?.id]);
 return <section id="support-tickets" className="legacy-page-anchor ticket-center"><div className="eyebrow">LUMAWAY SUPPORT</div><h1>Tiket Bantuan</h1><p className="muted">Pantau tiket yang diteruskan oleh Luma, status penanganan, dan seluruh riwayat percakapan dengan support.</p>{error&&<div className="flash error">{error}</div>}<div className="ticket-layout"><div className="card ticket-list"><div className="section-head"><h3>Daftar Tiket</h3><button className="secondary" onClick={()=>load(active?.id)}>Refresh</button></div>{tickets.length?tickets.map(t=><button key={t.id} className={`ticket-row ${active?.id===t.id?"active":""}`} onClick={()=>load(t.id)}><div><b>{t.ticket_code}</b><span>{t.subject}</span></div><div><span className={`status-pill s-${String(t.status).toLowerCase()}`}>{t.status}</span><small>{t.priority}</small></div></button>):<div className="empty-state"><strong>Belum ada tiket.</strong></div>}</div><div className="card ticket-detail">{active?<><div className="ticket-detail-head"><div><b>{active.ticket_code}</b><span>{active.subject}</span></div><div><span className={`status-pill s-${String(active.status).toLowerCase()}`}>{active.status}</span><small>{active.channel}</small></div></div><div className="ticket-chat-history">{messages.map(m=><div key={m.id} className={`ticket-message from-${m.sender_type}`}><small>{m.sender_type==="owner"?"Support Lumaway":m.sender_type==="agent"?"Luma":m.sender_type==="user"?"Anda":"System"}</small><p>{m.body}</p><time>{m.created_at?new Date(m.created_at).toLocaleString("id-ID"):""}</time></div>)}{!messages.length&&<div className="empty-state"><strong>Belum ada rekaman percakapan.</strong></div>}</div><p className="muted ticket-note">Tiket yang sudah diteruskan akan dibalas oleh admin CS/owner. Riwayat ini hanya dapat dilihat oleh user pemilik tiket.</p></>:<div className="empty-state"><strong>Pilih tiket untuk melihat detail.</strong></div>}</div></div></section>
}
