"use client";

import { useEffect, useState } from "react";

export default function WhatsAppIntegration({workspaceId}:{workspaceId:string}){
  const [form,setForm]=useState({access_token:"",phone_number_id:"",otp_template:"luma_otp",template_language:"id",graph_version:"v24.0",channel_url:""});
  const [configured,setConfigured]=useState(false);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("Memeriksa WhatsApp integration...");
  async function load(){setBusy(true);try{const r=await fetch(`/api/integrations/whatsapp?workspace_id=${encodeURIComponent(workspaceId)}`);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal membaca WhatsApp integration.");setConfigured(Boolean(d.configured));const s=d.settings||{};setForm(f=>({...f,phone_number_id:s.whatsapp_phone_number_id||"",otp_template:s.whatsapp_otp_template||"luma_otp",template_language:s.whatsapp_template_language||"id",graph_version:s.whatsapp_graph_version||"v24.0",channel_url:s.whatsapp_channel_url||""}));setStatus(d.configured?"WhatsApp Cloud API token tersimpan. Lengkapi Phone Number ID, template OTP, dan Channel URL.":"WhatsApp Cloud API belum terhubung.")}catch(e:any){setStatus(e?.message||"Gagal membaca integration.")}finally{setBusy(false)}}
  useEffect(()=>{void load()},[workspaceId]);
  async function save(){setBusy(true);try{const r=await fetch("/api/integrations/whatsapp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,...form})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Gagal menyimpan WhatsApp integration.");setConfigured(Boolean(d.configured));setForm(f=>({...f,access_token:""}));setStatus("WhatsApp integration disimpan. Token tidak ditampilkan kembali ke browser.")}catch(e:any){setStatus(e?.message||"Gagal menyimpan integration.")}finally{setBusy(false)}}
  return <div className="card"><div className="section-head"><div><h3>WhatsApp Cloud API & OTP</h3><p className="muted">Dipakai untuk OTP verifikasi nomor dan onboarding saluran WhatsApp. Gunakan template WhatsApp yang sudah approved.</p></div><span className={`integration-badge ${configured?"connected":"disconnected"}`}>{configured?"Connected":"Not Connected"}</span></div><div className="grid"><label>Access Token<input type="password" value={form.access_token} onChange={e=>setForm({...form,access_token:e.target.value})} placeholder={configured?"Leave blank to keep existing token":"EA..."}/></label><label>Phone Number ID<input value={form.phone_number_id} onChange={e=>setForm({...form,phone_number_id:e.target.value})}/></label><label>OTP Template Name<input value={form.otp_template} onChange={e=>setForm({...form,otp_template:e.target.value})}/></label><label>Template Language<input value={form.template_language} onChange={e=>setForm({...form,template_language:e.target.value})}/></label><label>Graph API Version<input value={form.graph_version} onChange={e=>setForm({...form,graph_version:e.target.value})}/></label><label>WhatsApp Channel URL<input value={form.channel_url} onChange={e=>setForm({...form,channel_url:e.target.value})} placeholder="https://whatsapp.com/channel/..."/></label></div><button className="primary" disabled={busy||(!configured&&!form.access_token)} onClick={save}>{busy?"Saving...":"Save WhatsApp Integration"}</button><p className="muted">{status}</p></div>;
}
