"use client";

import { useEffect, useState } from "react";

export default function XenditIntegration({workspaceId}:{workspaceId:string}){
  const [configured,setConfigured]=useState(false);const [webhookConfigured,setWebhookConfigured]=useState(false);const [secret,setSecret]=useState("");const [webhook,setWebhook]=useState("");const [status,setStatus]=useState("Checking payment gateway...");const [busy,setBusy]=useState(false);
  async function check(){setBusy(true);try{const r=await fetch(`/api/integrations/xendit?workspace_id=${encodeURIComponent(workspaceId)}`);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error);setConfigured(Boolean(d.configured));setWebhookConfigured(Boolean(d.webhook_configured));setStatus(d.configured?"Xendit secret key tersedia server-side.":"Xendit belum dikonfigurasi.");}catch(e:any){setStatus(e.message||"Unable to check Xendit.")}finally{setBusy(false)}}
  useEffect(()=>{void check()},[workspaceId]);
  async function save(){if(!secret.trim())return setStatus("Masukkan Xendit Secret API Key.");setBusy(true);try{const r=await fetch("/api/integrations/xendit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,secret_key:secret.trim(),webhook_token:webhook.trim()})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error);setSecret("");setWebhook("");setConfigured(true);setWebhookConfigured(Boolean(d.webhook_configured));setStatus("Xendit tersimpan aman. Secret tidak ditampilkan kembali di browser.");}catch(e:any){setStatus(e.message||"Gagal menyimpan Xendit.")}finally{setBusy(false)}}
  return <div className="card integration-panel"><div className="section-head"><div><h3>Xendit Payment Gateway</h3><p className="muted">Untuk billing token, QRIS/VA/e-wallet dan payout referral. Secret disimpan server-side.</p></div><span className={`integration-badge ${configured&&webhookConfigured?"connected":"disconnected"}`}>{configured&&webhookConfigured?"Ready":"Setup Required"}</span></div><div className="grid"><label>Secret API Key<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="xnd_..."/></label><label>Webhook Verification Token<input type="password" autoComplete="off" value={webhook} onChange={e=>setWebhook(e.target.value)} placeholder="Xendit callback token"/></label></div><div className="button-row"><button className="primary" disabled={busy||!secret.trim()} onClick={save}>{busy?"Saving...":"Save Securely"}</button><button className="secondary" disabled={busy} onClick={check}>Check Status</button></div><div className={`flash ${configured?"success":"error"}`}>{status} Webhook endpoint: <code>/api/payments/webhook</code></div></div>;
}
