import {notFound} from 'next/navigation';
import Link from 'next/link';
import {audiences,capabilities} from '@/content/products';
import {metadata as meta} from '@/lib/seo';
import {ButtonLink,FinalCta,Status,JsonLd} from '@/components/ui';
import {site} from '@/lib/config';
export function generateStaticParams(){return audiences.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=audiences.find(x=>x.slug===slug);return a?meta(`Lumaway untuk ${a.name}`,a.description,`/solutions/${a.slug}`):{}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=audiences.find(x=>x.slug===slug);if(!a)notFound();const c=capabilities.find(c=>c.slug===a.product)!;return <><div className="container"><header className="inner-hero"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><Link href="/solutions">Solusi</Link><span>/</span><span>{a.name}</span></nav><span className="eyebrow">LUMAWAY UNTUK {a.name.toUpperCase()}</span><h1>{a.title}</h1><p>{a.description}</p></header><div className="inner-body content-grid"><section className="editorial-block"><h2>Pertanyaan yang ingin dijawab</h2><p>{a.question}</p><div className="context-note"><b>Hasil pembahasan yang diharapkan</b><br/>{a.output}</div><h2>Dari temuan menjadi tindakan</h2><ol><li>Sepakati keputusan yang perlu dibuat.</li><li>Periksa data, konteks, dan asumsi.</li><li>Tentukan tindak lanjut dan waktu evaluasi.</li></ol></section><section className="editorial-block"><Status value={c.status}/><h2 className="form-spaced">{c.name}</h2><p>{c.description}</p><p>{c.evidence}</p><div className="related-links"><Link href={`/${c.slug}`}>Pelajari cakupan kemampuan ↗</Link></div><div className="form-spaced"><ButtonLink href="/contact?type=demo">Bahas kebutuhan tim</ButtonLink></div></section></div></div><FinalCta/><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Beranda',item:site.url},{'@type':'ListItem',position:2,name:'Solusi',item:`${site.url}/solutions`},{'@type':'ListItem',position:3,name:a.name,item:`${site.url}/solutions/${a.slug}`}]}}/></>}
