import { NextRequest, NextResponse } from "next/server";
import { getServerContext } from "../../../../lib/server-auth";
import { getServerSecret } from "../../../../lib/server-secrets";
import { openAIResponsesWithFailover } from "../../../../lib/openai-router";
export const runtime="nodejs";
function outputText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==="output_text"&&c?.text)return c.text;return ""}
const slugify=(s:string)=>s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s-]/g,"").trim().replace(/\s+/g,"-").replace(/-+/g,"-").slice(0,90)||`article-${Date.now()}`;
export async function POST(req:NextRequest){try{const b=await req.json();const workspaceId=String(b.workspace_id||"");const action=String(b.action||"generate");const ctx=await getServerContext(workspaceId);if(!ctx.platformAdmin)return NextResponse.json({ok:false,error:"Owner access required."},{status:403});if(action==="publish"){
 const title=String(b.title||"").trim();if(!title)return NextResponse.json({ok:false,error:"Title wajib diisi."},{status:400});
 const editingId=Number(b.id||0);let slug=slugify(String(b.slug||title));let attempt=0;
 while(true){let q=ctx.admin.from("luma_blog_posts").select("id").eq("slug",slug);if(editingId)q=q.neq("id",editingId);const {data}=await q.maybeSingle();if(!data)break;attempt++;slug=`${slugify(title)}-${attempt+1}`;}
 const payload={workspace_id:workspaceId,slug,title,excerpt:b.excerpt||null,content_html:b.content_html||null,category:b.category||"Insight",cover_image_url:b.cover_image_url||null,seo_title:b.seo_title||title,seo_description:b.seo_description||b.excerpt||null,seo_keywords:Array.isArray(b.seo_keywords)?b.seo_keywords:[],external_dofollow_url:b.external_dofollow_url||null,video_embed_url:b.video_embed_url||null,image_prompt:b.image_prompt||null,image_alt:b.image_alt||title,author_name:"Lumaway",status:"published",created_by:ctx.user.id,published_at:new Date().toISOString(),updated_at:new Date().toISOString()};
 let data:any,error:any;
 if(editingId){({data,error}=await ctx.admin.from("luma_blog_posts").update(payload).eq("id",editingId).select("id,slug").single());}else{({data,error}=await ctx.admin.from("luma_blog_posts").insert(payload).select("id,slug").single());}
 if(error)throw error;return NextResponse.json({ok:true,...data,updated:Boolean(editingId)})
}const key=await getServerSecret(ctx.admin,"luma_openai_api_key");if(!key)return NextResponse.json({ok:false,error:"error, terjadi kesalahan."},{status:503});const schema={type:"object",additionalProperties:false,properties:{title:{type:"string"},slug:{type:"string"},excerpt:{type:"string"},category:{type:"string"},seo_title:{type:"string"},seo_description:{type:"string"},seo_keywords:{type:"array",items:{type:"string"}},content_html:{type:"string"},image_prompt:{type:"string"}},required:["title","slug","excerpt","category","seo_title","seo_description","seo_keywords","content_html","image_prompt"]};const model=process.env.OPENAI_MODEL||"gpt-5.6-sol";const input={topic:b.topic||"",audience:b.audience||"pemilik bisnis dan marketer Indonesia",category:b.category||"Insight",objective:b.objective||"edukasi",notes:b.notes||"",external_reference:b.external_dofollow_url||""};const routed=await openAIResponsesWithFailover(ctx.admin,key,{instructions:"Anda adalah SEO editor Lumaway. Buat artikel Bahasa Indonesia berkualitas tinggi, informatif, original, natural, tidak keyword stuffing. Struktur content_html hanya memakai h2,h3,p,ul,li,strong,blockquote. Jangan masukkan script/style/form. SEO title maksimal 60 karakter dan meta description sekitar 140-160 karakter. Jangan mengarang data/statistik. Jika external_reference tersedia, sebut secara natural sebagai referensi tetapi jangan membuat klaim yang tidak diberikan. Image prompt tanpa text/logo/watermark.",input:JSON.stringify(input),text:{format:{type:"json_schema",name:"lumaway_seo_article",schema,strict:true}},store:false},model);const raw=routed.raw;const text=outputText(raw);if(!text)throw new Error("Respons AI kosong.");const result=JSON.parse(text);result.slug=slugify(result.slug||result.title);const usage=raw?.usage||{};await ctx.admin.from("luma_api_usage_events").insert({workspace_id:workspaceId,user_id:ctx.user.id,provider:"openai",service:"seo_blog",request_type:"generate_article",model:routed.model,input_tokens:Number(usage.input_tokens||0),output_tokens:Number(usage.output_tokens||0),total_tokens:Number(usage.total_tokens||0),cost_usd:routed.cost.cost_usd,cost_idr:routed.cost.cost_idr,status:"success",metadata:{fallback_used:routed.fallback_used}});return NextResponse.json({ok:true,result,model:routed.model})}catch{return NextResponse.json({ok:false,error:"error, terjadi kesalahan."},{status:400})}}
