-- Lumaway production schema baseline snapshot
-- Captured from Supabase production on 2026-09-25.
-- Disaster-recovery reference only. DO NOT apply to the existing production database.
-- Customer/business row data is intentionally excluded.

-- affiliate_ads_support
create table if not exists public.affiliate_ads_support (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  platform text DEFAULT 'ALL'::text NOT NULL,
  amount numeric DEFAULT 0 NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- agreements
create table if not exists public.agreements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  agreement_id text,
  creator_name text,
  platform text,
  brand text,
  category text,
  product_name text,
  deal_type text,
  ratecard numeric DEFAULT 0,
  support_type text,
  support_value numeric DEFAULT 0,
  start_date date,
  end_date date,
  document_path text,
  document_status text DEFAULT 'Pending'::text,
  approval_by text,
  approval_date date,
  support_status text DEFAULT 'Pending'::text,
  bonus_eligible text DEFAULT 'No'::text,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  creator_id bigint,
  product_master_id bigint,
  product_hpp numeric DEFAULT 0 NOT NULL,
  e_stamp_id text,
  signed_by_name text,
  signed_at timestamp with time zone,
  pdf_generated_at timestamp with time zone
);

-- ai_analysis_logs
create table if not exists public.ai_analysis_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id text,
  event text,
  details text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- ai_analysis_runs
create table if not exists public.ai_analysis_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id text,
  analysis_type text,
  start_date date,
  end_date date,
  dataset_version text,
  input_hash text,
  model text,
  status text,
  response_id text,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  error_message text,
  workspace_id uuid
);

-- ai_insights
create table if not exists public.ai_insights (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id text,
  insight_json jsonb,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- audit_log
create table if not exists public.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username text,
  action text,
  entity text,
  entity_id text,
  details text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- creator_360_profiles
create table if not exists public.creator_360_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  creator_id bigint NOT NULL,
  favorite boolean DEFAULT false NOT NULL,
  rating numeric DEFAULT 0 NOT NULL,
  program_status text DEFAULT 'Not Joined'::text NOT NULL,
  top_creator boolean DEFAULT false NOT NULL,
  ads_support numeric DEFAULT 0 NOT NULL,
  target_sales numeric DEFAULT 0 NOT NULL,
  target_live numeric DEFAULT 0 NOT NULL,
  target_video numeric DEFAULT 0 NOT NULL,
  video_links jsonb DEFAULT '[]'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- creator_360_targets
create table if not exists public.creator_360_targets (
  id bigint DEFAULT nextval('creator_360_targets_id_seq'::regclass) NOT NULL,
  workspace_id uuid NOT NULL,
  creator_id bigint NOT NULL,
  target_year integer NOT NULL,
  target_month smallint DEFAULT 0 NOT NULL,
  target_sales numeric DEFAULT 0 NOT NULL,
  target_live numeric DEFAULT 0 NOT NULL,
  target_video numeric DEFAULT 0 NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- creator_documents
create table if not exists public.creator_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  creator_id bigint,
  creator_name text,
  document_type text,
  file_name text,
  local_path text,
  drive_file_id text,
  drive_url text,
  uploaded_by text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- creator_history
create table if not exists public.creator_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  creator_id bigint NOT NULL,
  creator_name text,
  history_type text DEFAULT 'note'::text,
  title text,
  summary text,
  detail_json jsonb,
  period_start date,
  period_end date,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- creator_samples
create table if not exists public.creator_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  creator_id bigint,
  creator_name text,
  platform text,
  sku text,
  product_name text,
  sample_status text DEFAULT 'sent'::text,
  sent_date date,
  return_date date,
  qty numeric DEFAULT 1,
  product_value numeric DEFAULT 0,
  tracking text,
  notes text,
  source text DEFAULT 'web'::text,
  source_import_id text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid NOT NULL,
  product_master_id bigint
);

-- creator_store_affiliations
create table if not exists public.creator_store_affiliations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  creator_id bigint NOT NULL,
  platform text NOT NULL,
  store_name text NOT NULL,
  store_id text,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  source_import_id text
);

-- creator_tasks
create table if not exists public.creator_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  creator_id bigint,
  creator_name text,
  platform text,
  title text NOT NULL,
  description text,
  status text DEFAULT 'progress'::text,
  priority text DEFAULT 'normal'::text,
  due_date date,
  assigned_to text,
  period text,
  source text DEFAULT 'web'::text,
  sheet_record_id bigint,
  source_import_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  sort_order numeric DEFAULT 0 NOT NULL,
  created_by uuid,
  source_ref text,
  analysis_type text
);

-- creator_user_access
create table if not exists public.creator_user_access (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  creator_id bigint NOT NULL,
  assigned_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- creators
create table if not exists public.creators (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  creator_code text,
  name text,
  username text,
  platform text,
  affiliate_id text,
  phone text,
  address text,
  payment_type text,
  ratecard numeric DEFAULT 0,
  profile_url text,
  level_override text,
  status text DEFAULT 'Active'::text,
  notes text,
  source_import_id text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  identity_key text
);

-- daily
create table if not exists public.daily (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_date date,
  active_creator numeric DEFAULT 0,
  reach_out numeric DEFAULT 0,
  contacted numeric DEFAULT 0,
  follow_up numeric DEFAULT 0,
  recomm numeric DEFAULT 0,
  deals numeric DEFAULT 0,
  video_upload numeric DEFAULT 0,
  live_hours numeric DEFAULT 0,
  gmv numeric DEFAULT 0,
  qty numeric DEFAULT 0,
  orders numeric DEFAULT 0,
  commission numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  cost_product numeric DEFAULT 0,
  notes text,
  source_file text,
  import_id text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- google_sheet_connections
create table if not exists public.google_sheet_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  spreadsheet_id text NOT NULL,
  spreadsheet_name text,
  status text DEFAULT 'connected'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- google_sheet_sync_history
create table if not exists public.google_sheet_sync_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sync_id text,
  direction text,
  kind text,
  range_name text,
  status text,
  total_rows integer DEFAULT 0,
  created_count integer DEFAULT 0,
  updated_count integer DEFAULT 0,
  skipped_count integer DEFAULT 0,
  conflict_count integer DEFAULT 0,
  error_count integer DEFAULT 0,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  username text,
  message text,
  workspace_id uuid
);

-- google_sheet_sync_state
create table if not exists public.google_sheet_sync_state (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  kind text,
  record_id bigint,
  sheet_hash text,
  db_hash text,
  db_updated_at timestamp with time zone,
  sheet_row integer,
  synced_at timestamp with time zone,
  workspace_id uuid
);

-- imports
create table if not exists public.imports (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  import_id text,
  filename text,
  data_type text,
  platform text,
  start_date date,
  end_date date,
  rows_imported integer,
  status text,
  imported_at timestamp with time zone,
  message text,
  file_hash text,
  workspace_id uuid
);

-- kpi_targets
create table if not exists public.kpi_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  scope text DEFAULT 'dashboard'::text,
  creator_id bigint,
  period text NOT NULL,
  platform text DEFAULT 'All'::text,
  target_gmv numeric DEFAULT 0,
  target_qty numeric DEFAULT 0,
  target_orders numeric DEFAULT 0,
  target_commission numeric DEFAULT 0,
  target_live_hours numeric DEFAULT 0,
  target_video_upload numeric DEFAULT 0,
  target_deals numeric DEFAULT 0,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- listings
create table if not exists public.listings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_date date,
  creator_id bigint,
  creator_name text,
  platform text,
  product_name text,
  sku text,
  stage text,
  payment_type text,
  ratecard numeric DEFAULT 0,
  posting_date date,
  post_link text,
  next_action text,
  agreement_id text,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid NOT NULL,
  product_master_id bigint,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  product_hpp numeric DEFAULT 0 NOT NULL
);

-- luma_api_usage_events
create table if not exists public.luma_api_usage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid,
  user_id uuid,
  provider text NOT NULL,
  service text NOT NULL,
  request_type text,
  model text,
  input_tokens bigint DEFAULT 0 NOT NULL,
  output_tokens bigint DEFAULT 0 NOT NULL,
  total_tokens bigint DEFAULT 0 NOT NULL,
  status text DEFAULT 'success'::text NOT NULL,
  reference text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  cost_usd numeric(18,8) DEFAULT 0 NOT NULL,
  cost_idr numeric(18,2) DEFAULT 0 NOT NULL
);

-- luma_blog_posts
create table if not exists public.luma_blog_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid,
  slug text NOT NULL,
  title text NOT NULL,
  excerpt text,
  content_html text,
  category text DEFAULT 'Insight'::text NOT NULL,
  cover_image_url text,
  seo_title text,
  seo_description text,
  seo_keywords text[],
  external_dofollow_url text,
  status text DEFAULT 'draft'::text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  published_at timestamp with time zone,
  author_name text DEFAULT 'Lumaway'::text NOT NULL,
  video_embed_url text,
  image_prompt text,
  image_alt text
);

-- luma_business_monthly_targets
create table if not exists public.luma_business_monthly_targets (
  id bigint DEFAULT nextval('luma_business_monthly_targets_id_seq'::regclass) NOT NULL,
  target_year integer NOT NULL,
  target_month integer NOT NULL,
  target_revenue numeric(18,2) DEFAULT 0 NOT NULL,
  forecast_revenue numeric(18,2) DEFAULT 0 NOT NULL,
  notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_community_likes
create table if not exists public.luma_community_likes (
  post_id bigint NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_community_posts
create table if not exists public.luma_community_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  body text,
  image_url text,
  image_storage_path text,
  status text DEFAULT 'published'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  image_urls jsonb DEFAULT '[]'::jsonb NOT NULL,
  image_storage_paths jsonb DEFAULT '[]'::jsonb NOT NULL
);

-- luma_community_saves
create table if not exists public.luma_community_saves (
  post_id bigint NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_community_subscriptions
create table if not exists public.luma_community_subscriptions (
  user_id uuid NOT NULL,
  subscribed_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_content_events
create table if not exists public.luma_content_events (
  id bigint DEFAULT nextval('luma_content_events_id_seq'::regclass) NOT NULL,
  content_type text NOT NULL,
  content_id bigint,
  event_type text NOT NULL,
  user_id uuid,
  workspace_id uuid,
  session_id text,
  visitor_id text,
  path text,
  referrer text,
  utm jsonb DEFAULT '{}'::jsonb NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
