-- Lumaway production schema baseline snapshot
-- Captured from Supabase production on 2026-09-25.
-- Disaster-recovery reference only. DO NOT apply to the existing production database.
-- Customer/business row data is intentionally excluded.

-- luma_expense_records
create table if not exists public.luma_expense_records (
  id bigint DEFAULT nextval('luma_expense_records_id_seq'::regclass) NOT NULL,
  expense_date date DEFAULT CURRENT_DATE NOT NULL,
  category text DEFAULT 'operational'::text NOT NULL,
  vendor text,
  description text NOT NULL,
  amount numeric(18,2) DEFAULT 0 NOT NULL,
  currency text DEFAULT 'IDR'::text NOT NULL,
  recurring boolean DEFAULT false NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_financial_reports
create table if not exists public.luma_financial_reports (
  id bigint DEFAULT nextval('luma_financial_reports_id_seq'::regclass) NOT NULL,
  report_type text NOT NULL,
  period_start date,
  period_end date,
  title text NOT NULL,
  input_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  insight_json jsonb DEFAULT '{}'::jsonb NOT NULL,
  model text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_hpp_scenarios
create table if not exists public.luma_hpp_scenarios (
  id bigint DEFAULT nextval('luma_hpp_scenarios_id_seq'::regclass) NOT NULL,
  name text NOT NULL,
  sku text,
  product_name text,
  metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  result jsonb DEFAULT '{}'::jsonb NOT NULL,
  ai_insight jsonb,
  model text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_issue_logs
create table if not exists public.luma_issue_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid,
  user_id uuid,
  category text DEFAULT 'bug'::text NOT NULL,
  severity text DEFAULT 'medium'::text NOT NULL,
  title text NOT NULL,
  details text,
  page_path text,
  status text DEFAULT 'open'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone
);

-- luma_knowledge_documents
create table if not exists public.luma_knowledge_documents (
  id bigint DEFAULT nextval('luma_knowledge_documents_id_seq'::regclass) NOT NULL,
  source_type text DEFAULT 'obsidian'::text NOT NULL,
  source_path text,
  title text NOT NULL,
  content_markdown text NOT NULL,
  tags text[] DEFAULT '{}'::text[] NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  checksum text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_notification_reads
create table if not exists public.luma_notification_reads (
  notification_id bigint NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT now() NOT NULL,
  clicked_at timestamp with time zone
);

-- luma_notifications
create table if not exists public.luma_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid,
  title text NOT NULL,
  body text NOT NULL,
  category text DEFAULT 'info'::text NOT NULL,
  action_url text,
  action_label text,
  image_url text,
  audience text DEFAULT 'all'::text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  published_at timestamp with time zone
);

-- luma_otp_challenges
create table if not exists public.luma_otp_challenges (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  channel text DEFAULT 'whatsapp'::text NOT NULL,
  target text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  salt text
);

-- luma_payment_checkout_intents
create table if not exists public.luma_payment_checkout_intents (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  kind text NOT NULL,
  target_key text NOT NULL,
  promo_code text DEFAULT ''::text NOT NULL,
  amount numeric DEFAULT 0 NOT NULL,
  idempotency_key text NOT NULL,
  order_code text NOT NULL,
  status text DEFAULT 'processing'::text NOT NULL,
  provider text,
  payment_url text,
  payment_session_id text,
  payment_reference text,
  expires_at timestamp with time zone,
  last_error_code text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_payment_provider_settings
create table if not exists public.luma_payment_provider_settings (
  provider text NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  priority integer DEFAULT 100 NOT NULL,
  weight integer DEFAULT 1 NOT NULL,
  health_status text DEFAULT 'unknown'::text NOT NULL,
  last_success_at timestamp with time zone,
  last_error_at timestamp with time zone,
  last_error text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid,
  webhook_registered_at timestamp with time zone
);

-- luma_payment_routing
create table if not exists public.luma_payment_routing (
  id smallint DEFAULT 1 NOT NULL,
  mode text DEFAULT 'priority_fallback'::text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid
);

-- luma_payment_webhook_events
create table if not exists public.luma_payment_webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  provider text NOT NULL,
  event_key text NOT NULL,
  order_code text,
  status text,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_pdf_downloads
create table if not exists public.luma_pdf_downloads (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  report_id bigint NOT NULL,
  user_id uuid NOT NULL,
  tokens_used integer DEFAULT 0,
  downloaded_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- luma_pdf_reports
create table if not exists public.luma_pdf_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  title text,
  period_start date,
  period_end date,
  language text,
  tone text,
  tokens_used integer DEFAULT 10,
  file_name text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  run_id text,
  analysis_type text,
  content_json jsonb,
  status text DEFAULT 'ready'::text,
  previewed_at timestamp with time zone,
  downloaded_at timestamp with time zone,
  download_count integer DEFAULT 0 NOT NULL,
  watermark_removed_at timestamp with time zone,
  page_count integer DEFAULT 20 NOT NULL,
  document_json jsonb,
  pdf_path text
);

-- luma_platform_settings
create table if not exists public.luma_platform_settings (
  setting_key text NOT NULL,
  setting_value text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid
);

-- luma_promo_codes
create table if not exists public.luma_promo_codes (
  id bigint DEFAULT nextval('luma_promo_codes_id_seq'::regclass) NOT NULL,
  code text NOT NULL,
  title text NOT NULL,
  promo_type text NOT NULL,
  value numeric(14,2) NOT NULL,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  max_uses integer,
  per_user_limit integer DEFAULT 1 NOT NULL,
  applicable_plan_codes text[] DEFAULT '{}'::text[] NOT NULL,
  applicable_token_package_ids bigint[] DEFAULT '{}'::bigint[] NOT NULL,
  active boolean DEFAULT true NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_promo_redemptions
create table if not exists public.luma_promo_redemptions (
  id bigint DEFAULT nextval('luma_promo_redemptions_id_seq'::regclass) NOT NULL,
  promo_id bigint NOT NULL,
  user_id uuid NOT NULL,
  workspace_id uuid,
  target_type text NOT NULL,
  target_reference text,
  discount_amount numeric(14,2) DEFAULT 0 NOT NULL,
  bonus_tokens integer DEFAULT 0 NOT NULL,
  extend_days integer DEFAULT 0 NOT NULL,
  status text DEFAULT 'applied'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  applied_at timestamp with time zone
);

-- luma_provider_accounts
create table if not exists public.luma_provider_accounts (
  id bigint DEFAULT nextval('luma_provider_accounts_id_seq'::regclass) NOT NULL,
  provider text NOT NULL,
  service text NOT NULL,
  display_name text NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  balance_usd numeric(18,4) DEFAULT 0 NOT NULL,
  balance_idr numeric(18,2) DEFAULT 0 NOT NULL,
  monthly_budget_usd numeric(18,4) DEFAULT 0 NOT NULL,
  monthly_budget_idr numeric(18,2) DEFAULT 0 NOT NULL,
  alert_threshold_usd numeric(18,4) DEFAULT 0 NOT NULL,
  alert_threshold_idr numeric(18,2) DEFAULT 0 NOT NULL,
  renewal_at timestamp with time zone,
  cost_config jsonb DEFAULT '{}'::jsonb NOT NULL,
  last_status text,
  last_checked_at timestamp with time zone,
  consecutive_failures integer DEFAULT 0 NOT NULL,
  notes text,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_schema_migration_registry
create table if not exists public.luma_schema_migration_registry (
  migration_version text NOT NULL,
  migration_name text NOT NULL,
  source_status text NOT NULL,
  repo_path text,
  production_applied boolean DEFAULT false NOT NULL,
  notes text,
  recorded_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_social_archives
create table if not exists public.luma_social_archives (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  community_post_id bigint,
  image_url text NOT NULL,
  image_storage_path text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_subscription_orders
create table if not exists public.luma_subscription_orders (
  id bigint DEFAULT nextval('luma_subscription_orders_id_seq'::regclass) NOT NULL,
  user_id uuid NOT NULL,
  workspace_id uuid,
  plan_id bigint NOT NULL,
  order_code text NOT NULL,
  base_amount numeric(14,2) DEFAULT 0 NOT NULL,
  discount_amount numeric(14,2) DEFAULT 0 NOT NULL,
  amount numeric(14,2) DEFAULT 0 NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  payment_provider text,
  payment_method text,
  payment_reference text,
  payment_session_id text,
  payment_url text,
  promo_id bigint,
  expires_at timestamp with time zone,
  paid_at timestamp with time zone,
  provider_payload jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  upgrade_from_subscription_id bigint,
  upgrade_credit_days numeric(10,2) DEFAULT 0 NOT NULL,
  upgrade_credit_amount numeric(14,2) DEFAULT 0 NOT NULL,
  checkout_intent_id bigint
);

-- luma_subscription_plans
create table if not exists public.luma_subscription_plans (
  id bigint DEFAULT nextval('luma_subscription_plans_id_seq'::regclass) NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  duration_days integer NOT NULL,
  price numeric(14,2) DEFAULT 0 NOT NULL,
  bonus_tokens integer DEFAULT 0 NOT NULL,
  priority_level text DEFAULT 'normal'::text NOT NULL,
  all_access boolean DEFAULT true NOT NULL,
  is_trial boolean DEFAULT false NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_support_messages
create table if not exists public.luma_support_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  sender_type text NOT NULL,
  sender_user_id uuid,
  body text NOT NULL,
  provider text,
  provider_message_id text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_support_tickets
create table if not exists public.luma_support_tickets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  ticket_code text NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  subject text DEFAULT 'Lumaway Help Desk'::text NOT NULL,
  category text DEFAULT 'general'::text NOT NULL,
  status text DEFAULT 'ai_assist'::text NOT NULL,
  priority text DEFAULT 'normal'::text NOT NULL,
  source text DEFAULT 'luma_agent'::text NOT NULL,
  channel text DEFAULT 'in_app'::text NOT NULL,
  summary text,
  resolution text,
  whatsapp_phone text,
  whatsapp_handoff_at timestamp with time zone,
  assigned_to uuid,
  ai_attempts integer DEFAULT 0 NOT NULL,
  last_message_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone
);

-- luma_system_controls
create table if not exists public.luma_system_controls (
  id integer DEFAULT 1 NOT NULL,
  mode text DEFAULT 'normal'::text NOT NULL,
  status_code integer DEFAULT 200 NOT NULL,
  title text DEFAULT 'Lumaway berjalan normal'::text NOT NULL,
  message text,
  block_user_access boolean DEFAULT false NOT NULL,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_system_events
create table if not exists public.luma_system_events (
  id bigint DEFAULT nextval('luma_system_events_id_seq'::regclass) NOT NULL,
  mode text NOT NULL,
  status_code integer NOT NULL,
  title text NOT NULL,
  message text,
  action text DEFAULT 'update'::text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_token_packages
create table if not exists public.luma_token_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  label text NOT NULL,
  tokens integer NOT NULL,
  price numeric DEFAULT 0 NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_token_transactions
create table if not exists public.luma_token_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  transaction_type text NOT NULL,
  amount integer NOT NULL,
  balance_monthly integer DEFAULT 0,
  balance_bonus integer DEFAULT 0,
  reference text,
  description text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- luma_token_wallets
create table if not exists public.luma_token_wallets (
  user_id uuid NOT NULL,
  month text NOT NULL,
  monthly_limit integer DEFAULT 50,
  used_tokens integer DEFAULT 0,
  bonus_tokens integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- luma_topup_orders
create table if not exists public.luma_topup_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  order_code text NOT NULL,
  package_tokens integer NOT NULL,
  amount numeric DEFAULT 0,
  status text DEFAULT 'pending'::text,
  payment_provider text,
  payment_reference text,
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  approved_by text,
  notes text,
  workspace_id uuid,
  payment_method text,
  payment_session_id text,
  payment_url text,
  expires_at timestamp with time zone DEFAULT (now() + '3 days'::interval),
  provider_payload jsonb,
  expiry_reminder_sent_at timestamp with time zone,
  promo_id bigint,
  base_amount numeric(14,2),
  discount_amount numeric(14,2) DEFAULT 0 NOT NULL,
  checkout_intent_id bigint
);
