-- Lumaway production schema baseline snapshot
-- Captured from Supabase production on 2026-09-25.
-- Disaster-recovery reference only. DO NOT apply to the existing production database.
-- Customer/business row data is intentionally excluded.

-- luma_tutorial_progress
create table if not exists public.luma_tutorial_progress (
  id bigint DEFAULT nextval('luma_tutorial_progress_id_seq'::regclass) NOT NULL,
  user_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  tutorial_id bigint NOT NULL,
  completed boolean DEFAULT true NOT NULL,
  watched_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- luma_user_subscriptions
create table if not exists public.luma_user_subscriptions (
  id bigint DEFAULT nextval('luma_user_subscriptions_id_seq'::regclass) NOT NULL,
  user_id uuid NOT NULL,
  workspace_id uuid,
  plan_id bigint NOT NULL,
  status text DEFAULT 'trialing'::text NOT NULL,
  priority_level text DEFAULT 'trial'::text NOT NULL,
  starts_at timestamp with time zone DEFAULT now() NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  source text DEFAULT 'system'::text NOT NULL,
  order_code text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- marketing_lead_outbox
create table if not exists public.marketing_lead_outbox (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  lead_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  state text DEFAULT 'pending'::text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  delivered_at timestamp with time zone
);

-- marketing_leads
create table if not exists public.marketing_leads (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  request_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  kind text NOT NULL,
  email text NOT NULL,
  name text DEFAULT ''::text NOT NULL,
  company text DEFAULT ''::text NOT NULL,
  consent boolean NOT NULL,
  marketing_consent boolean DEFAULT false NOT NULL,
  payload jsonb NOT NULL,
  fingerprint text NOT NULL,
  status text DEFAULT 'new'::text NOT NULL
);

-- owner_service_subscriptions
create table if not exists public.owner_service_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  provider text NOT NULL,
  service_name text NOT NULL,
  category text DEFAULT 'SaaS'::text NOT NULL,
  plan_name text,
  billing_cycle text DEFAULT 'monthly'::text NOT NULL,
  amount numeric DEFAULT 0 NOT NULL,
  currency text DEFAULT 'IDR'::text NOT NULL,
  next_billing_date date,
  status text DEFAULT 'active'::text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- product_hpp_history
create table if not exists public.product_hpp_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id bigint,
  sku text,
  product_name text,
  period text NOT NULL,
  hpp numeric DEFAULT 0,
  selling_price numeric DEFAULT 0,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  source_import_id text,
  workspace_id uuid,
  product_master_id bigint
);

-- product_master
create table if not exists public.product_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  sku text NOT NULL,
  sku_normalized text NOT NULL,
  product_name text,
  category text,
  selling_price numeric(18,2),
  cost_price numeric(18,2),
  point_per_unit numeric(18,2) DEFAULT 0,
  status text DEFAULT 'Active'::text,
  notes text,
  source_import_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- product_platform_items
create table if not exists public.product_platform_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  product_master_id bigint NOT NULL,
  sku text NOT NULL,
  platform text NOT NULL,
  product_code text NOT NULL,
  product_name text,
  variant_slot smallint,
  variant_name text,
  source_import_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  category text
);

-- product_variants
create table if not exists public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  product_master_id bigint NOT NULL,
  sku text NOT NULL,
  slot smallint NOT NULL,
  variant_name text NOT NULL,
  hpp numeric,
  selling_price numeric,
  source_import_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- products
create table if not exists public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sku text,
  product_name text,
  category text,
  selling_price numeric DEFAULT 0,
  cost_price numeric DEFAULT 0,
  point_per_unit numeric DEFAULT 0,
  status text DEFAULT 'Active'::text,
  notes text,
  source_import_id text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- profiles
create table if not exists public.profiles (
  id uuid NOT NULL,
  legacy_user_id bigint,
  username text,
  role text DEFAULT 'staff'::text NOT NULL,
  active boolean DEFAULT true NOT NULL,
  full_name text DEFAULT ''::text,
  email text DEFAULT ''::text,
  whatsapp text DEFAULT ''::text,
  social_media text DEFAULT ''::text,
  avatar_character text DEFAULT 'A'::text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  phone text,
  phone_verified_at timestamp with time zone,
  avatar_url text,
  bio text,
  education text,
  birth_date date,
  position_title text,
  social_alias text,
  social_avatar_key text,
  whatsapp_opt_in boolean DEFAULT false NOT NULL,
  whatsapp_opt_in_at timestamp with time zone,
  whatsapp_channel_joined_at timestamp with time zone,
  nickname text,
  profile_completed boolean DEFAULT false NOT NULL,
  email_verified_at timestamp with time zone,
  social_avatar_url text
);

-- promo_generations
create table if not exists public.promo_generations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid,
  title text,
  product_name text,
  audience text,
  tone text,
  key_points text,
  landing_json jsonb,
  reels_json jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'saved'::text,
  workspace_id uuid,
  content_type text,
  platform text,
  structure text,
  output_json jsonb
);

-- ratecard_master
create table if not exists public.ratecard_master (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  creator_id bigint,
  platform text,
  ratecard numeric(18,4) DEFAULT 0 NOT NULL,
  effective_from date,
  effective_to date,
  status text DEFAULT 'Active'::text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- referral_events
create table if not exists public.referral_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  referrer_user_id uuid NOT NULL,
  referred_user_id uuid,
  reference text,
  base_amount numeric DEFAULT 0,
  commission_rate numeric DEFAULT 0.05,
  commission_amount numeric DEFAULT 0,
  status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  workspace_id uuid
);

-- referral_profiles
create table if not exists public.referral_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  referral_code text NOT NULL,
  referred_by_user_id uuid,
  referred_by_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- referral_withdrawals
create table if not exists public.referral_withdrawals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  payout_method text NOT NULL,
  channel_code text,
  account_number text NOT NULL,
  account_name text,
  status text DEFAULT 'pending'::text NOT NULL,
  provider text DEFAULT 'xendit'::text,
  provider_reference text,
  provider_payload jsonb,
  notes text,
  requested_at timestamp with time zone DEFAULT now() NOT NULL,
  processed_at timestamp with time zone,
  provider_fee numeric(18,2) DEFAULT 0 NOT NULL,
  provider_fee_currency text DEFAULT 'IDR'::text NOT NULL
);

-- sales
create table if not exists public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  record_key text,
  data_type text DEFAULT 'sales'::text,
  transaction_id text,
  order_id text,
  item_id text,
  data_date date,
  end_date date,
  creator_id bigint,
  creator_name text,
  username text,
  platform text,
  channel text,
  sku text,
  product_name text,
  category text,
  qty numeric DEFAULT 0,
  orders numeric DEFAULT 0,
  gmv numeric DEFAULT 0,
  refund numeric DEFAULT 0,
  commission numeric DEFAULT 0,
  cost_product numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  points numeric DEFAULT 0,
  clicks numeric DEFAULT 0,
  buyers numeric DEFAULT 0,
  new_buyers numeric DEFAULT 0,
  live_gmv numeric DEFAULT 0,
  video_gmv numeric DEFAULT 0,
  showcase_gmv numeric DEFAULT 0,
  ctr numeric DEFAULT 0,
  ctor numeric DEFAULT 0,
  live_count numeric DEFAULT 0,
  video_count numeric DEFAULT 0,
  sample_content numeric DEFAULT 0,
  sample_sent numeric DEFAULT 0,
  impressions numeric DEFAULT 0,
  video_views numeric DEFAULT 0,
  source_file text,
  imported_at timestamp with time zone,
  import_id text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  store_name text,
  store_id text,
  ads_spend numeric DEFAULT 0 NOT NULL,
  refund_qty numeric DEFAULT 0 NOT NULL,
  sales_creator numeric DEFAULT 0 NOT NULL,
  flat_fee numeric DEFAULT 0 NOT NULL,
  roi numeric DEFAULT 0 NOT NULL,
  product_code text,
  variant_name text
);

-- shipping
create table if not exists public.shipping (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_date date,
  creator_name text,
  platform text,
  sku text,
  product_name text,
  qty numeric DEFAULT 0,
  product_cost numeric DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  courier text,
  tracking text,
  status text,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid NOT NULL,
  creator_id bigint,
  product_master_id bigint
);

-- tutorials
create table if not exists public.tutorials (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  youtube_url text NOT NULL,
  embed_url text NOT NULL,
  category text DEFAULT 'Getting Started'::text,
  status text DEFAULT 'Published'::text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- user_notifications
create table if not exists public.user_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  title text,
  message text,
  kind text DEFAULT 'info'::text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  workspace_id uuid,
  action_url text
);

-- user_payout_methods
create table if not exists public.user_payout_methods (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  method_type text NOT NULL,
  channel_code text NOT NULL,
  account_number text NOT NULL,
  account_name text,
  is_default boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- user_permissions
create table if not exists public.user_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  permission text NOT NULL,
  enabled boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  workspace_id uuid
);

-- workspace_grid_rows
create table if not exists public.workspace_grid_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  sheet_id bigint NOT NULL,
  row_order numeric DEFAULT 0 NOT NULL,
  row_data jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid DEFAULT auth.uid(),
  updated_by uuid DEFAULT auth.uid(),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- workspace_grid_sheets
create table if not exists public.workspace_grid_sheets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  workspace_id uuid NOT NULL,
  name text NOT NULL,
  columns_json jsonb DEFAULT '["Column A", "Column B", "Column C", "Column D"]'::jsonb NOT NULL,
  created_by uuid DEFAULT auth.uid(),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- workspace_members
create table if not exists public.workspace_members (
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  membership_role text DEFAULT 'member'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- workspaces
create table if not exists public.workspaces (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
