import { conviaSendText, DEFAULT_CONVIA_BASE_URL, normalizeConviaPhone } from "./convia";
import { getServerSecret } from "./server-secrets";

type NoticeKind="token_checkout"|"token_paid"|"token_expired"|"token_failed"|"subscription_checkout"|"subscription_paid"|"subscription_expired"|string;
type NoticeInput={userId:string;workspaceId:string;kind:NoticeKind;title:string;message:string;actionUrl?:string|null};
const esc=(value:string)=>String(value||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
async function settings(admin:any){const keys=["convia_base_url","convia_phone_number_id","email_from"];const {data}=await admin.from("luma_platform_settings").select("setting_key,setting_value").in("setting_key",keys);return Object.fromEntries((data||[]).map((x:any)=>[x.setting_key,String(x.setting_value||"")])) as Record<string,string>}
async function log(admin:any,input:NoticeInput,provider:string,status:string,metadata:Record<string,unknown>={}){try{await admin.from("luma_api_usage_events").insert({workspace_id:input.workspaceId,user_id:input.userId,provider,service:"transactional_notice",request_type:input.kind,status,reference:null,metadata})}catch{}}
export async function sendExternalCustomerNotice(admin:any,input:NoticeInput){const result:{email:"sent"|"skipped"|"error";whatsapp:"sent"|"skipped"|"error"}={email:"skipped",whatsapp:"skipped"};try{const [{data:profile},cfg]=await Promise.all([admin.from("profiles").select("email,full_name,whatsapp,phone").eq("id",input.userId).maybeSingle(),settings(admin)]);const name=String(profile?.full_name||"Pengguna Lumaway").trim();const appUrl=(process.env.NEXT_PUBLIC_APP_URL||"").replace(/\/$/,"");const action=input.actionUrl||`${appUrl}/#billing`;
 try{const resendKey=await getServerSecret(admin,"luma_resend_api_key");const from=String(process.env.LUMA_EMAIL_FROM||cfg.email_from||"").trim();const email=String(profile?.email||"").trim();if(resendKey&&from&&email){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[email],subject:`Lumaway · ${input.title}`,html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#101828"><h2 style="margin-bottom:8px">${esc(input.title)}</h2><p>Halo ${esc(name)},</p><p style="line-height:1.65">${esc(input.message)}</p>${action?`<p><a href="${esc(action)}" style="display:inline-block;background:#635bff;color:white;text-decoration:none;padding:11px 16px;border-radius:10px">Buka Lumaway</a></p>`:""}<p style="font-size:12px;color:#667085;margin-top:28px">Lumaway · Light Up Your Potential.</p></div>`})});if(!response.ok)throw new Error(`Resend ${response.status}`);result.email="sent";await log(admin,input,"resend","success",{channel:"email"})}}catch(error:any){result.email="error";await log(admin,input,"resend","error",{channel:"email",error:String(error?.message||"unknown").slice(0,180)})}
 try{const conviaKey=await getServerSecret(admin,"luma_convia_api_key");const rawPhone=String(profile?.whatsapp||profile?.phone||"").trim();const phone=rawPhone?normalizeConviaPhone(rawPhone):"";if(conviaKey&&/^\+[1-9][0-9]{8,14}$/.test(phone)){const content=`Lumaway — ${input.title}\n\nHalo ${name}, ${input.message}${action?`\n\n${action}`:""}`.slice(0,4096);await conviaSendText(conviaKey,phone,content,{baseUrl:process.env.CONVIA_BASE_URL||cfg.convia_base_url||DEFAULT_CONVIA_BASE_URL,whatsappPhoneNumberId:process.env.CONVIA_WHATSAPP_PHONE_NUMBER_ID||cfg.convia_phone_number_id||"",customerName:name});result.whatsapp="sent";await log(admin,input,"convia","success",{channel:"whatsapp",recipient_last4:phone.slice(-4)})}}catch(error:any){result.whatsapp="error";await log(admin,input,"convia","error",{channel:"whatsapp",error:String(error?.message||"unknown").slice(0,180)})}}catch{}return result}
