export type Article = {slug:string;title:string;description:string;category:string;date:string;readTime:string;sections:{title:string;paragraphs:string[]}[]};
export const articles:Article[] = [
 {slug:'dari-data-ke-keputusan',title:'Banyak data, tetapi keputusan masih terasa sulit?',description:'Cara memulai analisis dari pertanyaan bisnis, menyamakan definisi metrik, dan merumuskan tindakan.',category:'Business Intelligence',date:'2026-09-16',readTime:'4 menit',sections:[
  {title:'Mulai dari keputusan yang ingin dibuat',paragraphs:['Dashboard sering dimulai dari pertanyaan: angka apa yang bisa ditampilkan? Untuk kerja sehari-hari, cobalah urutan berbeda. Tentukan keputusan yang perlu dibuat, lalu cari data yang membantu menilai pilihan tersebut.','Misalnya, tim ingin memilih produk untuk didukung dalam kampanye berikutnya. Total penjualan saja belum cukup. Tim juga perlu memahami periode penjualan, kontribusi kreator, kondisi stok, dan biaya dukungan. Tidak semua data itu harus berada dalam satu grafik, tetapi semuanya perlu masuk ke pembahasan.']},
  {title:'Samakan arti angka sebelum membandingkan',paragraphs:['Order, kuantitas barang, GMV, dan pendapatan bersih menjawab pertanyaan yang berbeda. Buat kamus metrik sederhana: nama, definisi, sumber, periode, dan hal yang tidak tercakup. Periksa pula apakah angka memuat pembatalan atau pengembalian.','Jika dua sumber memakai definisi berbeda, tampilkan terpisah sampai rekonsiliasinya jelas. Angka kosong berarti belum diketahui, bukan otomatis nol. Kebiasaan kecil ini membantu tim menghindari kesimpulan yang terlihat meyakinkan tetapi salah konteks.']},
  {title:'Pisahkan observasi, dugaan, dan tindakan',paragraphs:['Observasi menjelaskan apa yang terlihat pada data. Dugaan menjelaskan kemungkinan penyebabnya. Tindakan menjelaskan apa yang ingin dilakukan untuk memeriksa atau merespons temuan itu.','Contoh: kontribusi satu SKU menurun pada periode tertentu adalah observasi. Perubahan materi promosi sebagai penyebab masih berupa dugaan. Membandingkan materi dan ketersediaan stok pada periode yang sama adalah langkah investigasi. Urutan ini membuat analisis lebih terbuka untuk diuji.']},
  {title:'Tutup analisis dengan catatan keputusan',paragraphs:['Catat pilihan yang diambil, alasan, pemilik pekerjaan, dan waktu evaluasi. Tentukan indikator yang akan menunjukkan apakah tindakan layak diteruskan atau perlu diubah.','Lumaway dirancang untuk mendukung hubungan antara data, pemahaman, dan tindak lanjut. Namun, kualitas keputusan tetap bergantung pada data yang relevan serta disiplin tim dalam memeriksa hasilnya.']}
 ]},
 {slug:'rnd-marketing-dari-hipotesis-ke-eksperimen',title:'R&D marketing: dari ide kampanye menjadi eksperimen.',description:'Kerangka praktis untuk merumuskan hipotesis, membatasi variabel, dan mencatat pembelajaran marketing.',category:'Marketing & R&D',date:'2026-09-16',readTime:'5 menit',sections:[
  {title:'Riset dimulai dengan pertanyaan yang spesifik',paragraphs:['R&D marketing dapat dimulai dari masalah yang dekat dengan operasional. Mengapa calon pelanggan tertarik tetapi belum mengambil tindakan? Pesan apa yang belum jelas? Segmen mana yang sebenarnya sesuai dengan manfaat produk?','Tentukan satu pertanyaan utama. Kumpulkan bukti yang relevan: pertanyaan pelanggan, hasil kampanye, umpan balik tim penjualan, serta pengamatan pada materi komunikasi. Bedakan bukti langsung dari pendapat atau asumsi.']},
  {title:'Ubah ide menjadi hipotesis yang dapat diperiksa',paragraphs:['Hipotesis yang berguna menghubungkan perubahan, audiens, dan hasil yang diharapkan. Contohnya: penjelasan cara pemakaian yang lebih singkat diperkirakan membantu calon pengguna memahami manfaat produk dan melanjutkan ke permintaan demo.','Tuliskan alasan di balik dugaan tersebut. Jika alasannya belum kuat, eksperimen tetap bisa dilakukan sebagai eksplorasi, tetapi jangan memperlakukan hasil awal sebagai kepastian.']},
  {title:'Tentukan batas eksperimen sebelum berjalan',paragraphs:['Pilih perubahan utama, kelompok audiens, channel, periode, serta indikator yang akan diamati. Perubahan banyak hal sekaligus membuat penyebab hasil sulit ditelusuri.','Gunakan indikator yang berkaitan dengan tujuan. Klik dapat berguna untuk memeriksa ketertarikan awal, tetapi belum tentu menjawab kualitas lead. Catat juga perubahan stok, promosi, musim, atau faktor lain yang bisa memengaruhi pembacaan.']},
  {title:'Simpan pembelajaran, termasuk ketika hasil belum jelas',paragraphs:['Hasil eksperimen bisa mendukung hipotesis, melemahkannya, atau belum cukup jelas. Ketiga hasil tersebut berguna jika dicatat dengan konteks. Hindari memaksakan kesimpulan dari data yang sedikit atau periode yang tidak sebanding.','Format catatan yang sederhana sudah cukup: pertanyaan, bukti awal, hipotesis, perubahan yang diuji, hasil, keterbatasan, dan langkah berikutnya. Dengan cara ini, tim berikutnya tidak perlu mengulang riset yang sama.','Arah pengembangan Marketing Intelligence Lumaway berangkat dari siklus ini. Fondasi analisis dan Kanban dapat membantu pembahasan, sementara integrasi otomatis lintas channel masih memerlukan pengembangan dan validasi.']}
 ]},
 {slug:'evaluasi-affiliate-di-luar-gmv',title:'Evaluasi affiliate lebih lengkap dari sekadar GMV.',description:'Baca kontribusi kreator bersama konteks produk, dukungan program, dan kualitas data.',category:'Affiliate Intelligence',date:'2026-09-16',readTime:'4 menit',sections:[
  {title:'GMV adalah titik awal pembahasan',paragraphs:['GMV membantu menggambarkan nilai transaksi dalam definisi laporan tertentu. Namun, angka itu belum selalu menjelaskan nilai bersih bagi bisnis, kebutuhan dukungan kreator, atau konsistensi hasil.','Sebelum membandingkan kreator, pastikan periode, platform, dan status transaksi sebanding. Kreator dengan periode aktif yang berbeda tidak dapat dinilai secara adil hanya dari total akhir.']},
  {title:'Baca kontribusi bersama konteks dukungan',paragraphs:['Susun informasi kreator, SKU yang dipromosikan, komisi, sampel, dan dukungan kampanye dalam satu bahan evaluasi. Jangan menganggap semua biaya sudah tercakup jika sumber datanya belum lengkap.','Periksa juga konsentrasi penjualan. Hasil yang bergantung pada satu SKU memiliki karakter berbeda dari kontribusi yang tersebar. Temuan ini dapat membantu menyusun pertanyaan lanjutan tentang kecocokan kreator dan portofolio.']},
  {title:'Jaga identitas dan kualitas data',paragraphs:['Nama kreator atau produk dapat berubah antar file. Gunakan identitas yang stabil bila tersedia, dan pertahankan jejak sumber agar duplikasi dapat ditelusuri. SKU yang tidak ada pada sumber sebaiknya tetap ditandai belum tersedia, bukan diisi dengan tebakan.','Saat menemukan angka yang berbeda, telusuri definisi kolom, filter waktu, pembatalan, dan apakah transaksi dihitung sebagai order atau jumlah barang. Selisih adalah alasan untuk memeriksa data, bukan langsung menilai kinerja tim.']},
  {title:'Jadikan hasil review sebagai tindakan yang spesifik',paragraphs:['Tindak lanjut dapat berupa diskusi materi dengan kreator, evaluasi kecocokan produk, pengecekan stok, atau pemeriksaan data tambahan. Tentukan siapa yang menindaklanjuti dan kapan hasilnya akan dibahas kembali.','Creator 360 dan analisis affiliate Lumaway disiapkan untuk membantu membaca konteks ini dari data yang tersedia. Hasil review tetap perlu mempertimbangkan tujuan program dan kondisi bisnis Anda.']}
 ]}
];
