export const pages:Record<string,{title:string;description:string;sections:{title:string;text:string[]}[]}>= {
 about:{title:'Arah yang lebih jelas untuk potensi bisnis Anda.',description:'Lumaway menghubungkan data, pemahaman, dan langkah nyata dalam satu gagasan: Light Up Your Potential.',sections:[
 {title:'Makna di balik Lumaway',text:['Luma berarti cahaya dan kejelasan. Way berarti jalan, arah, dan perjalanan. Lumaway menggambarkan jalan yang menerangi potensi: mengubah informasi yang terpisah menjadi konteks untuk mengambil keputusan.']},
 {title:'Berangkat dari kebutuhan operasional',text:['Fondasi produk berfokus pada analisis affiliate, pengelolaan data produk, dan kebutuhan tim membaca performa dari berbagai laporan. Arah pengembangannya meluas menuju riset pasar, kompetitor, R&D marketing, serta alur keputusan bisnis.','Lumaway merupakan bagian dari ekosistem produk digital PT Totemo Creative Studio. Website ini menampilkan kemampuan yang dapat ditelusuri pada aplikasi dan rencana pengembangan secara terpisah.']},
 {title:'Cara kami memandang intelligence',text:['Data perlu sumber. Insight perlu konteks. Keputusan perlu alasan. Tindakan perlu evaluasi. Prinsip tersebut menjadi dasar pengalaman Lumaway, dari unggahan laporan hingga pembahasan langkah berikutnya.']}
 ]},
 security:{title:'Keamanan dimulai dari akses yang jelas.',description:'Kenali prinsip pengelolaan data dan batas informasi keamanan yang dapat kami sampaikan.',sections:[
 {title:'Akses aplikasi dan workspace',text:['Source aplikasi Lumaway memakai Supabase Auth dan data yang dipisahkan berdasarkan workspace. Konfigurasi akses dan kebijakan database perlu diuji pada environment yang digunakan sebelum akses produksi dinyatakan siap.']},
 {title:'Formulir pada website ini',text:['Data formulir dikirim melalui endpoint server. Penyimpanan dirancang menggunakan akses server, validasi input, pembatasan pengiriman, dan pencegahan penyimpanan permintaan yang sama dua kali. Email dan isi formulir tidak dikirim sebagai event analitik.']},
 {title:'Transparansi klaim',text:['Website ini tidak mengklaim sertifikasi, audit independen, SLA, atau kemitraan platform yang belum dikonfirmasi. Untuk kebutuhan evaluasi vendor, sampaikan persyaratan tim Anda sebelum menggunakan data operasional.']}
 ]},
 privacy:{title:'Informasi privasi website Lumaway.',description:'Bagaimana informasi formulir digunakan dan bagaimana Anda mengelola pilihan analitik.',sections:[
 {title:'Informasi yang diminta',text:['Formulir meminta email serta, untuk demo dan penjualan, nama dan nama bisnis. Peran, ukuran tim, channel, dan tantangan bisnis bersifat opsional. Kami juga mencatat jenis permintaan, modul yang diminati, persetujuan, serta sumber kampanye yang tersedia.','Alamat IP tidak disimpan sebagai teks pada tabel lead; server dapat mengubah alamat koneksi menjadi penanda tersamar untuk membatasi pengiriman berulang. Halaman asal disimpan tanpa query bebas dan referrer dibatasi ke domain.']},
 {title:'Tujuan penggunaan',text:['Informasi digunakan untuk meninjau serta menanggapi permintaan demo, kebutuhan bisnis, minat pengembangan, atau permintaan materi. Pilihan menerima newsletter dibuat terpisah dari persetujuan untuk memproses permintaan utama.','Formulir tidak menyatakan berhasil sampai penyimpanan dikonfirmasi. Penyimpanan leads dirancang menggunakan Supabase dan endpoint server di Vercel.']},
 {title:'Analitik opsional',text:['Analitik dan pixel pihak ketiga hanya diaktifkan setelah Anda memilih Izinkan, apabila layanan tersebut dikonfigurasi. Anda dapat menolak tanpa kehilangan akses formulir. Nama, email, dan isi tantangan bisnis tidak dimasukkan ke event analitik.']},
 {title:'Permintaan terkait data',text:['Gunakan halaman Hubungi Tim untuk mengajukan pertanyaan, perubahan, atau penghapusan data. Tim perlu memverifikasi permintaan sebelum memprosesnya. Penyimpanan dan tindak lanjut harus dibatasi pada kebutuhan layanan serta ketentuan yang disepakati.','Informasi ini berlaku untuk website marketing. Pemakaian aplikasi, layanan berbayar, serta pihak ketiga mengikuti informasi dan perjanjian yang relevan.']}
 ]},
 terms:{title:'Ketentuan penggunaan website.',description:'Baca batas informasi produk dan proses sebelum menggunakan layanan Lumaway.',sections:[
 {title:'Informasi dan status kemampuan',text:['Website ini menjelaskan konsep produk, fondasi aplikasi, serta rencana pengembangan. Label Beta berarti implementasi tersedia pada source dan masih memerlukan verifikasi kesiapan workspace. Label Direncanakan tidak merupakan janji tanggal rilis atau akses.']},
 {title:'Akun, harga, dan langganan',text:['Pembuatan akun, uji coba, harga, kuota, pembatalan, perpanjangan, dan pengembalian dana mengikuti penawaran atau perjanjian layanan yang berlaku. Mengirim formulir tidak membentuk transaksi berbayar atau janji uji coba gratis.']},
 {title:'Penggunaan informasi dan data',text:['Gunakan website dan materi untuk tujuan yang sah serta sesuai hak akses Anda. Pastikan data yang Anda kirim boleh digunakan untuk tujuan tersebut. Jangan mengirim kata sandi, API key, atau informasi rahasia operasional melalui formulir marketing.']},
 {title:'Analisis dan keputusan bisnis',text:['Materi edukasi dan hasil analisis perlu dinilai sesuai konteks bisnis. Informasi tidak menjamin peningkatan penjualan, laba, atau hasil tertentu. Pengguna tetap bertanggung jawab memvalidasi sumber, batas data, dan alasan sebelum bertindak.']}
 ]},
 cookies:{title:'Pilihan cookie dan analitik.',description:'Tetap kendalikan analitik opsional saat menjelajahi Lumaway.',sections:[
 {title:'Preferensi analitik',text:['Pilihan Izinkan atau Tolak disimpan di browser agar tidak perlu ditanyakan pada setiap halaman. Skrip GA4, Google Tag Manager, Meta Pixel, atau Vercel Analytics hanya dimuat bila diaktifkan dalam konfigurasi dan Anda memberi persetujuan.','Tombol Preferensi cookie tampil saat analitik dikonfigurasi. Mengubah pilihan ke Tolak memuat ulang halaman untuk menghentikan skrip opsional. Untuk menghapus cookie pihak ketiga yang sudah terbentuk, gunakan pengaturan privasi browser.']},
 {title:'Konteks sumber permintaan',text:['Parameter kampanye dan halaman pertama dapat disimpan selama sesi browser untuk memahami asal permintaan yang Anda kirim. Data ini bukan isi dashboard Anda. Formulir dan navigasi tetap berfungsi ketika analitik opsional ditolak.']}
 ]}
};
