export type Capability = {
 slug:string; name:string; label:string; status:'beta'|'planned'; headline:string; description:string;
 challenge:string; outcome:string; steps:string[]; evidence:string; related:string[];
};
export const capabilities: Capability[] = [
 {slug:'affiliate-intelligence',name:'Affiliate Intelligence',label:'Affiliate',status:'beta',headline:'Pahami kontribusi kreator. Tentukan langkah berikutnya.',description:'Satukan konteks kreator, produk, penjualan, dan dukungan kampanye dari data yang Anda unggah.',challenge:'GMV yang tinggi belum menjawab kreator mana yang tepat untuk didukung lagi. Data komisi, sampel, dan performa produk perlu dibaca bersama.',outcome:'Bahan evaluasi program affiliate yang lebih lengkap: siapa yang berkontribusi, produk apa yang bergerak, dan dukungan apa yang perlu ditinjau.',steps:['Unggah file performa sesuai format yang didukung.','Tinjau ranking dan profil Creator 360 bersama konteks produk.','Bandingkan kontribusi dengan dukungan, lalu tetapkan tindak lanjut.'],evidence:'Modul Upload Center, Creator Ranking, dan Creator 360 tersedia pada source aplikasi. Akses serta data bergantung pada konfigurasi workspace.',related:['product-intelligence','marketing-intelligence']},
 {slug:'product-intelligence',name:'Product Intelligence',label:'Produk',status:'beta',headline:'Lihat cerita di balik setiap SKU.',description:'Hubungkan master produk dengan data penjualan dan aktivitas affiliate untuk membaca performa produk secara lebih terstruktur.',challenge:'Nama produk yang tidak konsisten dan SKU yang tidak terisi membuat evaluasi portofolio sulit dibandingkan.',outcome:'Prioritas SKU untuk ditinjau, perbaikan kualitas data, dan bahan diskusi antara marketplace, marketing, dan tim produk.',steps:['Rapikan master produk dan identitas SKU.','Baca kontribusi produk dari laporan yang tersedia.','Catat peluang perbaikan dan kebutuhan validasi.'],evidence:'Master produk tersedia pada aplikasi. Estimasi permintaan pasar dan riset produk kompetitor masih termasuk arah pengembangan.',related:['affiliate-intelligence','market-intelligence']},
 {slug:'commerce-intelligence',name:'Commerce Intelligence',label:'Commerce',status:'beta',headline:'Baca performa bisnis dalam konteks yang utuh.',description:'Gunakan laporan transaksi dan performa yang diunggah sebagai dasar pembacaan penjualan lintas sumber.',challenge:'Definisi order, kuantitas, dan GMV bisa berbeda antar laporan. Menggabungkan angka tanpa memahami sumbernya dapat menyesatkan.',outcome:'Evaluasi yang dimulai dari periode, sumber, dan definisi metrik yang jelas, sebelum menyimpulkan perubahan bisnis.',steps:['Pilih sumber dan periode laporan yang sesuai.','Tinjau kualitas data sebelum membandingkan hasil.','Telusuri produk dan kreator yang membentuk performa.'],evidence:'Dashboard dan impor data tersedia dalam source. Koneksi langsung ke Seller Center tidak diklaim tersedia.',related:['affiliate-intelligence','product-intelligence']},
 {slug:'ai-insights',name:'AI Insights',label:'AI Insights',status:'beta',headline:'Ubah kumpulan angka menjadi pertanyaan yang lebih tajam.',description:'Gunakan analisis AI untuk merangkum konteks, menemukan pola, dan menyiapkan arah investigasi bisnis.',challenge:'Tim dapat menghabiskan banyak waktu merangkum laporan sebelum sempat memikirkan tindakan.',outcome:'Ringkasan dan bahan investigasi untuk diperiksa tim. Keputusan tetap perlu mempertimbangkan kualitas data dan konteks bisnis.',steps:['Mulai dengan data dan pertanyaan yang spesifik.','Baca analisis bersama sumber data yang tersedia.','Validasi temuan dan ubah menjadi rencana kerja.'],evidence:'Modul AI Analytics dan sistem token tersedia pada source. Penggunaan memerlukan konfigurasi AI dan kuota workspace.',related:['marketing-intelligence','affiliate-intelligence']},
 {slug:'decision-workspace',name:'Decision Workspace',label:'Workspace',status:'beta',headline:'Bawa insight sampai ke meja eksekusi.',description:'Susun pekerjaan dalam Kanban dan jaga agar tindak lanjut analisis tetap terlihat oleh tim.',challenge:'Temuan mudah berhenti di laporan ketika pemilik pekerjaan, langkah selanjutnya, dan waktu evaluasi tidak jelas.',outcome:'Rencana tindakan dengan konteks yang bisa dibahas dan ditinjau kembali bersama tim.',steps:['Tuliskan hipotesis dan tindakan yang ingin diuji.','Tentukan penanggung jawab dan status pekerjaan.','Tinjau hasil sebelum mengulang atau memperluas eksperimen.'],evidence:'Kanban tersedia pada source aplikasi. Alur rekomendasi AI ke tugas otomatis belum diklaim tersedia.',related:['ai-insights','marketing-intelligence']},
 {slug:'market-intelligence',name:'Market Intelligence',label:'Pasar',status:'planned',headline:'Temukan peluang dari perubahan pasar.',description:'Arah pengembangan untuk riset kategori, pergerakan produk, dan sinyal kebutuhan pelanggan.',challenge:'Ide produk sering muncul dari intuisi, sementara bukti tentang kebutuhan, harga, dan persaingan tersebar.',outcome:'Rencana analisis pasar yang membantu tim menyusun hipotesis dan kebutuhan data sebelum mengambil keputusan.',steps:['Tentukan kategori, segmen, dan pertanyaan riset.','Kumpulkan bukti dari sumber yang diizinkan.','Bandingkan sinyal dan susun prioritas validasi.'],evidence:'Masih direncanakan. Sumber data, cakupan, frekuensi pembaruan, dan tanggal rilis belum ditetapkan.',related:['competitor-intelligence','product-intelligence']},
 {slug:'competitor-intelligence',name:'Competitor Intelligence',label:'Kompetitor',status:'planned',headline:'Pahami perubahan kompetitor dalam konteks strategi Anda.',description:'Arah pengembangan untuk benchmarking produk, harga, positioning, dan aktivitas kompetitor dari sumber yang diizinkan.',challenge:'Memantau kompetitor tanpa pertanyaan yang jelas menghasilkan banyak catatan, tetapi sedikit keputusan.',outcome:'Kerangka perbandingan yang relevan untuk strategi harga, konten, produk, dan prioritas eksperimen.',steps:['Pilih kompetitor dan dimensi yang relevan.','Bandingkan perubahan berdasarkan waktu dan sumbernya.','Tentukan respons yang sesuai dengan strategi brand.'],evidence:'Masih direncanakan. Data penjualan atau order kompetitor tidak tersedia secara otomatis dan tidak diklaim sebagai data aktual.',related:['market-intelligence','marketing-intelligence']},
 {slug:'marketing-intelligence',name:'Marketing Intelligence',label:'Marketing & R&D',status:'planned',headline:'Jadikan riset sebagai awal strategi marketing.',description:'Arah pengembangan untuk menyatukan riset pasar, hipotesis kampanye, eksperimen, dan pembelajaran.',challenge:'Laporan channel sering berdiri sendiri, sehingga tim kesulitan menjelaskan mengapa hasil berubah dan apa yang harus dicoba berikutnya.',outcome:'Siklus R&D marketing: pertanyaan → bukti → hipotesis → eksperimen → evaluasi → perbaikan.',steps:['Tentukan masalah, audiens, dan hipotesis.','Rancang eksperimen dengan indikator yang jelas.','Bandingkan hasil dan dokumentasikan keputusan berikutnya.'],evidence:'Integrasi otomatis performa iklan lintas channel masih direncanakan. Analisis data unggahan dan Kanban menjadi fondasi yang sudah ada pada source.',related:['decision-workspace','ai-insights']},
 {slug:'smart-alerts',name:'Smart Alerts',label:'Notifikasi',status:'planned',headline:'Fokus pada perubahan yang layak ditindaklanjuti.',description:'Arah pengembangan untuk notifikasi perubahan berdasarkan konteks dan ambang yang relevan.',challenge:'Memeriksa semua angka terus-menerus menghabiskan perhatian, sementara perubahan penting bisa terlewat.',outcome:'Prioritas pemeriksaan untuk tim, dengan konteks perubahan dan sumber data yang transparan.',steps:['Tentukan metrik dan perubahan yang penting.','Pilih ambang serta penerima notifikasi.','Verifikasi sinyal sebelum bertindak.'],evidence:'Notifikasi internal tersedia dalam aplikasi. Alert penjualan kompetitor, pemantauan real-time, dan jadwal otomatis belum diverifikasi.',related:['competitor-intelligence','commerce-intelligence']},
];
export const audiences = [
 {slug:'brand-owner',name:'Brand owner',short:'Arah pertumbuhan',title:'Tentukan prioritas dengan konteks bisnis yang lebih jelas.',description:'Baca kontribusi produk dan affiliate sebelum memutuskan area yang perlu dukungan, evaluasi, atau eksperimen baru.',question:'Di mana tim perlu memusatkan perhatian bulan ini?',output:'Prioritas produk dan program yang perlu ditinjau.',product:'affiliate-intelligence'},
 {slug:'marketplace-team',name:'Tim marketplace',short:'Evaluasi channel',title:'Kurangi pekerjaan berulang saat membaca performa.',description:'Mulai dari laporan yang rapi, definisi metrik yang konsisten, dan konteks SKU untuk diskusi performa yang lebih terarah.',question:'Apa yang berubah pada produk dan kontribusi penjualan?',output:'Daftar SKU dan aktivitas untuk ditelusuri.',product:'commerce-intelligence'},
 {slug:'marketing-team',name:'Tim marketing',short:'Strategi berbasis bukti',title:'Hubungkan temuan analisis dengan eksperimen marketing.',description:'Gunakan pertanyaan yang jelas, bukti yang relevan, dan catatan hasil untuk memperbaiki strategi dari satu siklus ke siklus berikutnya.',question:'Hipotesis mana yang layak diuji selanjutnya?',output:'Brief eksperimen dengan indikator evaluasi.',product:'marketing-intelligence'},
 {slug:'affiliate-team',name:'Tim affiliate',short:'Kontribusi kreator',title:'Berikan dukungan dengan pemahaman kontribusi yang lebih lengkap.',description:'Lihat konteks kreator, produk, sampel, dan komisi sebelum meninjau keputusan kerja sama.',question:'Kreator dan SKU mana yang perlu dievaluasi bersama?',output:'Bahan review kreator dan alokasi dukungan.',product:'affiliate-intelligence'},
 {slug:'product-rnd',name:'Produk & R&D',short:'Validasi peluang',title:'Ubah ide produk menjadi hipotesis yang dapat diuji.',description:'Mulai dari kebutuhan pelanggan dan konteks produk. Pisahkan apa yang sudah terbukti dari apa yang masih perlu diteliti.',question:'Bukti apa yang perlu dikumpulkan sebelum mengembangkan produk?',output:'Matriks peluang, asumsi, dan rencana validasi.',product:'product-intelligence'},
 {slug:'agency',name:'Agency',short:'Konteks setiap klien',title:'Jaga konteks analisis setiap workspace tetap terpisah.',description:'Susun pembahasan performa per bisnis agar rekomendasi tetap relevan dengan tujuan dan kondisi masing-masing.',question:'Temuan apa yang relevan untuk tujuan klien ini?',output:'Bahan pembahasan performa dan tindak lanjut.',product:'decision-workspace'},
 {slug:'management',name:'Manajemen & analis',short:'Prioritas keputusan',title:'Mulai rapat dari pertanyaan yang perlu diputuskan.',description:'Gunakan ringkasan, data pendukung, dan opsi tindakan sebagai bahan diskusi lintas fungsi.',question:'Apa keputusan yang perlu diambil dan bukti apa yang mendukungnya?',output:'Ringkasan keputusan, pemilik aksi, dan jadwal review.',product:'ai-insights'},
];
export const faqs = [
 {q:'Apa itu Lumaway?',a:'Lumaway adalah Business Intelligence Operating Workspace: ruang kerja untuk menghubungkan data, analisis, dan tindak lanjut bisnis. Fondasi aplikasi saat ini berfokus pada data affiliate, produk, analisis AI, dan pengelolaan pekerjaan.'},
 {q:'Untuk siapa Lumaway dirancang?',a:'Untuk brand owner, tim marketplace, marketing, affiliate, produk dan R&D, agency, serta manajemen yang ingin membaca performa dan menyusun keputusan dengan konteks yang lebih jelas.'},
 {q:'Apakah semua fitur di website sudah tersedia?',a:'Tidak. Modul berlabel Beta sudah memiliki implementasi pada source aplikasi, tetapi akses dan kesiapannya bergantung pada konfigurasi workspace. Modul berlabel Direncanakan menjelaskan arah pengembangan dan belum dijanjikan tersedia.'},
 {q:'Apakah Lumaway langsung terhubung ke Shopee dan TikTok Shop?',a:'Koneksi API marketplace langsung belum dikonfirmasi. Fondasi yang tersedia memakai unggahan laporan sesuai format yang didukung. Lumaway tidak menggantikan Seller Center.'},
 {q:'Bisakah melihat penjualan dan order kompetitor secara aktual?',a:'Kemampuan tersebut belum tersedia untuk dijanjikan. Riset kompetitor masih dalam rencana pengembangan; sumber, cakupan, dan sifat data harus dijelaskan sebelum digunakan, termasuk perbedaan estimasi dengan data aktual.'},
 {q:'Bagaimana AI membantu tim?',a:'AI Analytics membantu menyusun analisis dari konteks data yang diberikan. Penggunaannya bergantung pada pengaturan dan kuota token. Hasilnya perlu diperiksa; AI tidak menjamin keputusan atau hasil bisnis.'},
 {q:'Bagaimana harga, kuota, ekspor, dan akses tim ditentukan?',a:'Harga paket, jumlah pengguna, batas data, fitur ekspor, retensi, dan layanan ditetapkan pada penawaran yang disepakati. Website ini tidak menampilkan harga atau kuota yang belum disetujui.'},
 {q:'Apakah tersedia uji coba gratis?',a:'Ketentuan uji coba gratis belum dikonfirmasi. Pembuatan akun tidak otomatis berarti seluruh modul dapat dipakai gratis. Hubungi tim untuk mengetahui akses yang sesuai dengan kebutuhan Anda.'},
 {q:'Bagaimana data bisnis dikelola?',a:'Source aplikasi memakai autentikasi dan pemisahan workspace dengan Supabase. Efektivitas pengaturan akses perlu diverifikasi pada deployment. Tidak ada klaim sertifikasi keamanan pada website ini.'},
 {q:'Bagaimana pembatalan langganan dilakukan?',a:'Ketentuan pembatalan, perpanjangan, dan pengembalian dana mengikuti perjanjian atau paket yang berlaku. Minta penjelasan tertulis sebelum berlangganan.'}
];
