'use client';
import {useEffect,useState,useRef} from 'react';
import {usePathname} from 'next/navigation';
import Script from 'next/script';
import Link from 'next/link';
import {hasConsent,track,EventName} from '@/lib/analytics';
export function Analytics(){const path=usePathname();const [consent,setConsent]=useState<string|null>(null);const [loaded,setLoaded]=useState(false);const [hydrated,setHydrated]=useState(false);const lastPage=useRef('');
 const gtm=process.env.NEXT_PUBLIC_GTM_ID;const ga=process.env.NEXT_PUBLIC_GA4_ID;const meta=process.env.NEXT_PUBLIC_META_PIXEL_ID;const va=process.env.NEXT_PUBLIC_VERCEL_ANALYTICS==='true';const configured=Boolean(gtm||ga||meta||va);
 useEffect(()=>{try{setConsent(localStorage.getItem('lumaway-consent-v1'));if(!sessionStorage.getItem('lumaway-attribution-v1')){const query=new URLSearchParams(location.search);const source:Record<string,string>={landing_page:location.pathname};for(const key of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']){const value=query.get(key);if(value)source[key]=value.slice(0,150)}if(document.referrer)source.referrer=new URL(document.referrer).origin;sessionStorage.setItem('lumaway-attribution-v1',JSON.stringify(source))}}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(!hasConsent()||!loaded||lastPage.current===path)return;lastPage.current=path;track('page_view',{path});if(path==='/pricing')track('pricing_view',{path});if(path.startsWith('/insights/'))track('article_view',{path})},[path,consent,loaded]);
 useEffect(()=>{function onClick(e:MouseEvent){const element=(e.target as Element).closest<HTMLElement>('[data-event]');if(element)track(element.dataset.event as EventName,{path})}document.addEventListener('click',onClick);return()=>document.removeEventListener('click',onClick)},[path]);
 function choose(value:string){try{localStorage.setItem('lumaway-consent-v1',value)}catch{}setConsent(value);if(value==='rejected')window.location.reload()}
 return <>{consent==='accepted'&&<>{gtm&&/^GTM-[A-Z0-9]+$/.test(gtm)?<Script id="gtm" strategy="afterInteractive" onReady={()=>setLoaded(true)} dangerouslySetInnerHTML={{__html:`window.dataLayer=window.dataLayer||[];window.dataLayer.push({'gtm.start':Date.now(),event:'gtm.js'});var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtm.js?id=${gtm}';document.head.appendChild(s);`}}/>:ga&&/^G-[A-Z0-9]+$/.test(ga)?<><Script src={`https://www.googletagmanager.com/gtag/js?id=${ga}`} onReady={()=>setLoaded(true)}/><Script id="ga" dangerouslySetInnerHTML={{__html:`window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config','${ga}',{send_page_view:false});`}}/></>:null}{meta&&/^\d+$/.test(meta)&&<Script id="meta" onReady={()=>setLoaded(true)} dangerouslySetInnerHTML={{__html:`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${meta}');`}}/>}{va&&<><Script id="va-init" dangerouslySetInnerHTML={{__html:"window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)};window.va('beforeSend',function(e){e.url=e.url.split('?')[0];return e;});"}}/><Script src="/_vercel/insights/script.js" data-disable-auto-track="1" onReady={()=>setLoaded(true)}/></>}</>}{configured&&hydrated&&!consent&&<aside className="cookie-banner" aria-label="Pilihan analitik"><p>Izinkan analitik untuk membantu kami memahami penggunaan website? Formulir tetap dapat digunakan tanpa analitik. <Link href="/cookies">Pelajari</Link></p><div><button onClick={()=>choose('rejected')}>Tolak</button><button onClick={()=>choose('accepted')}>Izinkan</button></div></aside>}{configured&&hydrated&&consent&&<button className="cookie-settings" onClick={()=>setConsent(null)}>Preferensi cookie</button>}</>;
}
