'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Database,Search,Layers,Target,Users,Package,Check,ChartNoAxesCombined,FileSpreadsheet,Lightbulb,MoveUpRight} from 'lucide-react';
import {audiences} from '@/content/products';
import {track} from '@/lib/analytics';
const stages=[['Data','Kumpulkan sinyal yang relevan.'],['Pahami','Berikan konteks pada angka.'],['Analisis','Temukan pola dan pertanyaan.'],['Putuskan','Tentukan prioritas tim.'],['Aksi','Ubah keputusan menjadi langkah.'],['Tumbuh','Pelajari hasil dan perbaiki.']];
export function LightPath(){const [active,setActive]=useState(2);return <div className="light-path"><div className="visual-top"><span><span className="tiny-square"/> DARI SINYAL KE ARAH</span><span>01 — 06</span></div><div className="signal-map"><div className="signal-sources"><span><FileSpreadsheet/>Laporan</span><span><Package/>Produk</span><span><Users/>Affiliate</span></div><svg className="flow-lines" viewBox="0 0 450 180" aria-hidden="true"><defs><linearGradient id="flow" x1="0" x2="1"><stop stopColor="#ffa977"/><stop offset=".45" stopColor="#e354b4"/><stop offset=".7" stopColor="#7767ef"/><stop offset="1" stopColor="#39c9dd"/></linearGradient></defs><path d="M40 15V45 Q40 65 70 65H190Q225 65 225 100V175 M225 15V175 M410 15V45Q410 65 380 65H260Q225 65 225 100V175" fill="none" stroke="url(#flow)" strokeWidth="1.7"/><circle cx="225" cy="140" r="5" fill="#a08bfa"/></svg><div className="intelligence-core"><Image src="/brand/luma-mark.png" alt="" width={44} height={48}/><div><span>LUMAWAY</span><strong>Temukan maknanya.</strong></div><Layers size={24}/></div><div className="signal-result"><Lightbulb size={19}/><div><span>PERTANYAAN YANG LEBIH JELAS</span><strong>Apa langkah terbaik berikutnya?</strong></div><ArrowUpRight size={19}/></div></div><div className="path-stages" aria-label="Tahapan alur intelligence">{stages.map(([label],i)=><button key={label} onClick={()=>setActive(i)} aria-pressed={active===i} className={active===i?'active':''}><span>0{i+1}</span>{label}</button>)}</div><p className="stage-caption" aria-live="polite"><span>0{active+1}</span>{stages[active][1]}</p><div className="visual-note">Ilustrasi alur kerja • bukan tampilan aplikasi</div></div>}
const stories=[
 {label:'Affiliate',title:'Kontribusi kreator, dalam konteks.',question:'Siapa yang perlu mendapat dukungan berikutnya?',input:'Laporan performa · Produk · Konteks kreator',output:'Review dukungan dan prioritas tindak lanjut',points:['Telusuri kontribusi kreator dan SKU.','Baca konteks sampel, komisi, dan dukungan.','Catat keputusan untuk review berikutnya.'],status:'Beta',href:'/affiliate-intelligence',icon:Users},
 {label:'Produk',title:'Setiap SKU punya cerita.',question:'Produk apa yang perlu dievaluasi lebih dalam?',input:'Master SKU · Laporan penjualan',output:'Daftar produk dan pertanyaan investigasi',points:['Mulai dari identitas produk yang konsisten.','Baca kontribusi dari data yang diunggah.','Pisahkan temuan dari asumsi pasar.'],status:'Beta',href:'/product-intelligence',icon:Package},
 {label:'AI Insights',title:'Temukan pertanyaan di balik angka.',question:'Perubahan apa yang perlu diperiksa tim?',input:'Data tersedia · Pertanyaan bisnis',output:'Ringkasan untuk divalidasi oleh tim',points:['Rangkum konteks yang relevan.','Gunakan AI untuk membantu analisis.','Periksa hasil sebelum mengambil keputusan.'],status:'Beta',href:'/ai-insights',icon:Lightbulb},
 {label:'Pasar',title:'Mulai dari peluang yang relevan.',question:'Kebutuhan mana yang belum terjawab?',input:'Kategori · Segmen · Sumber riset',output:'Hipotesis peluang untuk divalidasi',points:['Tentukan pertanyaan riset terlebih dahulu.','Bandingkan bukti dari sumber yang diizinkan.','Susun kebutuhan validasi produk.'],status:'Direncanakan',href:'/market-intelligence',icon:Search},
 {label:'Kompetitor',title:'Benchmark dengan pertanyaan yang tepat.',question:'Apa yang berubah pada positioning kompetitor?',input:'Produk · Harga · Aktivitas publik',output:'Bahan diskusi strategi dan eksperimen',points:['Pilih dimensi perbandingan yang relevan.','Catat sumber dan waktu pengamatan.','Bedakan sinyal publik dari data aktual.'],status:'Direncanakan',href:'/competitor-intelligence',icon:Target}
];
export function ProductStories(){const [tab,setTab]=useState(0);const s=stories[tab];const Icon=s.icon;return <div className="product-stories"><div className="story-tabs" role="tablist" aria-label="Cerita penggunaan produk">{stories.map((s,i)=><button key={s.label} role="tab" id={`story-tab-${i}`} aria-controls={`story-panel-${i}`} aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>{setTab(i);track('product_demo_click',{module:s.label})}} onKeyDown={e=>{let n=tab;if(e.key==='ArrowRight')n=(tab+1)%stories.length;else if(e.key==='ArrowLeft')n=(tab+stories.length-1)%stories.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=stories.length-1;else return;e.preventDefault();setTab(n);document.getElementById(`story-tab-${n}`)?.focus()}}>{s.label}</button>)}</div><div role="tabpanel" id={`story-panel-${tab}`} aria-labelledby={`story-tab-${tab}`} className="story-panel"><div className="story-copy"><span className={`status ${s.status==='Beta'?'beta':'planned'}`}>{s.status}</span><h3>{s.title}</h3><ul>{s.points.map(p=><li key={p}><Check size={17}/>{p}</li>)}</ul><Link href={s.href} className="text-link">Pelajari kemampuan <ArrowUpRight size={17}/></Link></div><div className="story-visual"><div className="story-window-bar"><span>ILUSTRASI PENGGUNAAN</span><span>lumaway / intelligence</span></div><div className="story-question"><Icon size={26}/><span>PERTANYAAN BISNIS</span><h4>{s.question}</h4></div><div className="story-flow"><div><Database size={17}/><span>MASUKAN<strong>{s.input}</strong></span></div><ArrowRight size={20}/><div><MoveUpRight size={17}/><span>ARAH TINDAKAN<strong>{s.output}</strong></span></div></div><p>Konsep alur. Ketersediaan modul mengikuti status produk.</p></div></div></div>}
export function UseCases(){const [selected,setSelected]=useState(0);const a=audiences[selected];return <div className="use-cases"><div className="audience-options" aria-label="Pilih audiens">{audiences.map((a,i)=><button key={a.slug} aria-pressed={selected===i} className={selected===i?'active':''} onClick={()=>setSelected(i)}>{a.name}<ArrowUpRight size={18}/></button>)}</div><div className="audience-detail" aria-live="polite"><span className="eyebrow">{a.short}</span><h3>{a.title}</h3><p>{a.description}</p><div className="audience-question"><span>PERTANYAAN ANDA</span><strong>“{a.question}”</strong></div><div className="audience-output"><Check size={18}/>{a.output}</div><Link className="text-link" href={`/solutions/${a.slug}`}>Jelajahi solusi untuk {a.name.toLowerCase()}<ArrowUpRight size={17}/></Link></div></div>}
const workflow=[['Hubungkan','Mulai dari sumber yang relevan dan diizinkan.'],['Rapikan','Samakan identitas, periode, dan definisi metrik.'],['Pahami','Baca kondisi bisnis bersama konteksnya.'],['Analisis','Telusuri pola dan pertanyaan yang perlu diuji.'],['Putuskan','Tentukan pilihan serta bukti pendukungnya.'],['Jalankan','Tunjuk pemilik aksi dan indikator evaluasi.'],['Pelajari','Tinjau hasil untuk keputusan berikutnya.']];
export function Workflow(){const ref=useRef<HTMLOListElement>(null);const [active,setActive]=useState(0);useEffect(()=>{const elements=ref.current?.querySelectorAll('li');if(!elements||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.index))},{rootMargin:'-25% 0px -45% 0px'});elements.forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);return <ol className="workflow-list" ref={ref}>{workflow.map(([title,description],i)=><li key={title} data-index={i} className={active===i?'active':''}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol>}
