import Link from 'next/link';
import Image from 'next/image';
import {ArrowUpRight,ArrowRight,Plus} from 'lucide-react';
import {capabilities,faqs} from '@/content/products';
import {articles} from '@/content/articles';
import {serializeSchema} from '@/lib/seo';
import {appLinks,marketingPath} from '@/lib/config';
export function Brand({light=false}:{light?:boolean}) {return <Link href="/home" className={`brand ${light?'brand-light':''}`} aria-label="Lumaway beranda"><Image src={marketingPath('/brand/luma-mark.png')} alt="" width={34} height={36}/><span>LUMAWAY<span className="brand-period">.</span></span></Link>}
export function ButtonLink({href,children,secondary=false,event}:{href:string;children:React.ReactNode;secondary?:boolean;event?:string}){return <Link href={href} className={`button ${secondary?'button-secondary':''}`} data-event={event}>{children}<ArrowUpRight size={17} aria-hidden="true"/></Link>}
export function SectionHeading({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>}
export function Status({value}:{value:'beta'|'planned'}){return <span className={`status ${value}`}>{value==='beta'?'Beta':'Direncanakan'}</span>}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeSchema(data)}}/>}
export function Faq({items=faqs}:{items?:typeof faqs}){return <><div className="faq-list">{items.map(item=><details key={item.q}><summary>{item.q}<Plus size={18} aria-hidden="true"/></summary><p>{item.a}</p></details>)}</div><JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(item=>({'@type':'Question',name:item.q,acceptedAnswer:{'@type':'Answer',text:item.a}}))}}/></>}
export function FinalCta(){return <section className="container final-cta"><div><span className="eyebrow">LANGKAH BERIKUTNYA</span><h2>Data Anda punya potensi.<br/>Mari temukan arahnya.</h2><p>Diskusikan kebutuhan tim dan kenali alur kerja yang relevan untuk bisnis Anda.</p></div><div className="cta-stack"><ButtonLink href={appLinks.register} event="register_click">Buat akun Lumaway</ButtonLink><Link href="/contact?type=demo" className="text-link" data-event="demo_request_open">Minta demo <ArrowRight size={17}/></Link></div></section>}
export function ArticleCards(){return <div className="article-grid">{articles.map((article,i)=><Link className="article-card" key={article.slug} href={`/insights/${article.slug}`}><div className={`article-art art-${i}`} aria-hidden="true"><span className="art-index">0{i+1}</span><span className="art-label">{['DATA → DIRECTION','RESEARCH → LEARNING','CONTEXT → ACTION'][i]}</span></div><span className="eyebrow">{article.category} <span>• {article.readTime}</span></span><h3>{article.title}</h3><p>{article.description}</p><span className="text-link">Baca insight <ArrowUpRight size={17}/></span></Link>)}</div>}
export function CapabilityList(){return <div className="capability-list">{capabilities.map((c,i)=><Link href={`/${c.slug}`} className="capability-row" key={c.slug} data-event="feature_view"><span className="row-number">{String(i+1).padStart(2,'0')}</span><div><h3>{c.name}</h3><p>{c.description}</p></div><Status value={c.status}/><ArrowUpRight size={22}/></Link>)}</div>}
