import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { getServerContext } from "../../../../lib/server-auth";
import { getServerSecret } from "../../../../lib/server-secrets";
import { openAIResponsesWithFailover } from "../../../../lib/openai-router";

export const runtime = "nodejs";
const AI_SCHEMA={type:"object",additionalProperties:false,properties:{executive_summary:{type:"string"},performance_status:{type:"string",enum:["HIGH GROWTH","GROWING","STABLE","DECLINING","AT RISK","TOP PERFORMER","INFO"]},key_findings:{type:"array",items:{type:"string"}},creator_findings:{type:"array",items:{type:"string"}},product_findings:{type:"array",items:{type:"string"}},trend_findings:{type:"array",items:{type:"string"}},anomalies:{type:"array",items:{type:"string"}},recommendations:{type:"array",items:{type:"string"}},confidence_note:{type:"string"}},required:["executive_summary","performance_status","key_findings","creator_findings","product_findings","trend_findings","anomalies","recommendations","confidence_note"]};
const BASE_PROMPT=`Anda adalah Senior Business Intelligence Analyst untuk LUMA Affiliate Intelligence. Gunakan HANYA database_context dan related_analysis yang diberikan. Angka database adalah sumber kebenaran. Related analysis hanya konteks sekunder dan tidak boleh mengalahkan data mentah/agregat. Jangan menciptakan angka, creator, SKU, sebab-akibat, benchmark, atau tren. Jika data tidak cukup, katakan eksplisit. Bahasa Indonesia profesional, managerial, jelas, dan actionable. Recommendations harus konkret dan dapat dijadikan task.`;
const ANALYSIS_GUIDE:Record<string,string>={performance:`Fokus PERFORMANCE ANALYSIS: kesehatan KPI keseluruhan, GMV, Qty, Orders, Commission, refund, efisiensi, dan kontribusi platform. Kaitkan creator/product/trend hanya jika menjelaskan perubahan KPI.`,creator:`Fokus CREATOR ANALYSIS: konsentrasi kontribusi, top/middle/low contributor, ketergantungan, peluang retain/grow/reactivate/test. Kaitkan product/trend/performance bila relevan dan didukung data.`,product:`Fokus PRODUCT ANALYSIS: SKU/product, GMV, Qty, Orders, product mix, volume vs revenue. Kaitkan creator/trend bila tersedia. Jika SKU granular kosong, nyatakan keterbatasan dan jangan mengarang produk.`,trend:`Fokus TREND ANALYSIS: perubahan antar bulan/periode, momentum, konsistensi, seasonality yang terlihat. Kaitkan perubahan dengan creator/product hanya jika data mendukung. Jangan menyebut tren jika hanya ada satu titik waktu.`,anomaly:`Fokus ANOMALY DETECTION: outlier, perubahan ekstrem, ketidakseimbangan GMV-vs-orders-vs-qty, konsentrasi creator/platform/product, serta kemungkinan anomali data. Bedakan fakta, hipotesis, dan item yang harus diverifikasi.`,recommendation:`Fokus RECOMMENDATIONS: kombinasikan seluruh analysis yang tersedia menjadi prioritas tindakan. Urutkan dampak dan urgensi. Setiap rekomendasi harus memiliki dasar temuan, tidak generik, dan bisa langsung dijadikan Kanban task.`};
function extractOutputText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const item of data?.output||[])for(const content of item?.content||[])if(content?.type==="output_text"&&content?.text)return content.text;return "";}

export async function POST(req:NextRequest){
 const started=Date.now();let ctx:Awaited<ReturnType<typeof getServerContext>>|null=null;const runId=`AI-${randomUUID().replace(/-/g,"").slice(0,12).toUpperCase()}`;
 try{
  const body=await req.json();const workspaceId=String(body.workspace_id||"");const analysisType=String(body.analysis_type||"performance");const context=body.context||{};const start=body.start_date?String(body.start_date):"";const end=body.end_date?String(body.end_date):"";if(!workspaceId)return NextResponse.json({ok:false,error:"error, terjadi kesalahan."},{status:400});ctx=await getServerContext(workspaceId);
  const apiKey=await getServerSecret(ctx.admin,"luma_openai_api_key");const model=process.env.OPENAI_MODEL||process.env.AI_MODEL||"gpt-5.6-sol";if(!apiKey)return NextResponse.json({ok:false,error:"error, terjadi kesalahan."},{status:503});
  let rq=ctx.admin.from("ai_analysis_runs").select("run_id,analysis_type,start_date,end_date,created_at").eq("workspace_id",workspaceId).eq("created_by",ctx.user.id).eq("status","Success").order("created_at",{ascending:false}).limit(50);if(start)rq=rq.eq("start_date",start);else rq=rq.is("start_date",null);if(end)rq=rq.eq("end_date",end);else rq=rq.is("end_date",null);
  const {data:previousRuns}=await rq;const latest:Record<string,any>={};for(const x of previousRuns||[])if(!latest[x.analysis_type])latest[x.analysis_type]=x;const prevIds=Object.values(latest).map((x:any)=>x.run_id);const {data:prevInsights}=prevIds.length?await ctx.admin.from("ai_insights").select("run_id,insight_json").eq("workspace_id",workspaceId).in("run_id",prevIds):{data:[]} as any;const insightMap=Object.fromEntries((prevInsights||[]).map((x:any)=>[x.run_id,x.insight_json]));const relatedAnalysis=Object.values(latest).map((x:any)=>({analysis_type:x.analysis_type,run_id:x.run_id,result:insightMap[x.run_id]||{}}));
  await ctx.admin.from("ai_analysis_runs").insert({workspace_id:workspaceId,run_id:runId,analysis_type:analysisType,start_date:start||null,end_date:end||null,dataset_version:"supabase-production",input_hash:"",model,status:"Processing",created_at:new Date().toISOString(),created_by:ctx.user.id});
  const instructions=`${BASE_PROMPT}\n\n${ANALYSIS_GUIDE[analysisType]||ANALYSIS_GUIDE.performance}\n\nCross-analysis rule: gunakan related_analysis untuk menemukan hubungan antartipe analysis, tetapi validasi terhadap database_context. Jika terjadi konflik, database_context menang. Isi field yang bukan fokus hanya bila relevan dan didukung data.`;
  const routed=await openAIResponsesWithFailover(ctx.admin,apiKey,{instructions,input:JSON.stringify({analysis_type:analysisType,database_context:context,related_analysis:relatedAnalysis}),text:{format:{type:"json_schema",name:"luma_ai_analysis",schema:AI_SCHEMA,strict:true}},store:false},model);
  const raw=routed.raw;const actualModel=routed.model;const outputText=extractOutputText(raw);if(!outputText)throw new Error("Respons AI kosong.");const result=JSON.parse(outputText);const usage=raw?.usage||{};
  await ctx.admin.from("ai_analysis_runs").update({status:"Success",response_id:raw?.id||null,error_message:null,model:actualModel}).eq("workspace_id",workspaceId).eq("run_id",runId);
  await ctx.admin.from("ai_insights").insert({workspace_id:workspaceId,run_id:runId,insight_json:result,created_at:new Date().toISOString()});
  await ctx.admin.from("ai_analysis_logs").insert({workspace_id:workspaceId,run_id:runId,event:"completed",details:{duration_ms:Date.now()-started,model:actualModel,requested_model:model,fallback_used:routed.fallback_used,analysis_type:analysisType,related_types:relatedAnalysis.map((x:any)=>x.analysis_type),usage,cost:routed.cost},created_at:new Date().toISOString()});
  await ctx.admin.from("luma_api_usage_events").insert({workspace_id:workspaceId,user_id:ctx.user.id,provider:"openai",service:"responses",request_type:`analytics:${analysisType}`,model:actualModel,input_tokens:Number(usage.input_tokens||0),output_tokens:Number(usage.output_tokens||0),total_tokens:Number(usage.total_tokens||0),cost_usd:routed.cost.cost_usd,cost_idr:routed.cost.cost_idr,status:"success",reference:runId,metadata:{response_id:raw?.id||null,duration_ms:Date.now()-started,requested_model:model,fallback_used:routed.fallback_used,fx:routed.fx}});
  return NextResponse.json({ok:true,run_id:runId,model:actualModel,fallback_used:routed.fallback_used,cost:routed.cost,result,related_types:relatedAnalysis.map((x:any)=>x.analysis_type)});
 }catch(error:any){if(ctx){try{await ctx.admin.from("ai_analysis_runs").update({status:"Error",error_message:error?.message||"AI analysis failed"}).eq("run_id",runId);await ctx.admin.from("luma_api_usage_events").insert({workspace_id:null,user_id:ctx.user.id,provider:"openai",service:"responses",request_type:"analytics",status:"error",reference:runId,metadata:{error:error?.message||"unknown"}})}catch{}}return NextResponse.json({ok:false,error:"error, terjadi kesalahan."},{status:400});}
}
