import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowUpRight,Check} from 'lucide-react';
import {capabilities,audiences,faqs} from '@/content/products';
import {pages} from '@/content/pages';
import {ButtonLink,CapabilityList,SectionHeading,FinalCta,Status,Faq,ArticleCards,JsonLd} from '@/components/ui';
import {ProductStories,UseCases,Workflow} from '@/components/experience';
import {LeadForm} from '@/components/lead-form';
import {metadata as meta} from '@/lib/seo';
import {site,plans} from '@/lib/config';
import {leadKinds,LeadKind} from '@/lib/leads';
const catalog:Record<string,[string,string]>={product:['Satu ekosistem. Banyak sudut pandang.','Jelajahi fondasi aplikasi Lumaway dan arah pengembangan intelligence untuk bisnis Anda.'],solutions:['Mulai dari keputusan yang perlu Anda buat.','Solusi dan pendekatan Lumaway untuk brand owner, tim marketplace, marketing, affiliate, produk dan R&D, agency, serta manajemen.'],pricing:['Akses yang berangkat dari kebutuhan tim.','Diskusikan kebutuhan modul, pengguna, dan data sebelum menentukan akses Lumaway yang sesuai.'],insights:['Intelligence untuk keputusan yang lebih baik.','Artikel dan kerangka berpikir tentang data bisnis, strategi marketplace, affiliate, dan R&D marketing.'],resources:['Bekal untuk langkah berikutnya.','Panduan praktis untuk menghubungkan pertanyaan bisnis, bukti, hipotesis, dan tindakan.'],contact:['Mari bicarakan arah bisnis Anda.','Ceritakan apa yang ingin Anda pahami. Tim Lumaway dapat meninjau kebutuhan yang relevan untuk Anda.'],roadmap:['Fondasi hari ini. Arah berikutnya.','Transparansi status produk: pisahkan kemampuan yang memiliki implementasi dari yang masih direncanakan.'],customers:['Pembelajaran yang berangkat dari praktik.','Ruang untuk cerita penggunaan Lumaway yang telah diverifikasi dan memperoleh persetujuan publikasi.'],integrations:['Sumber data dengan konteks yang jelas.','Kenali cara data masuk ke Lumaway dan batas integrasi yang telah dikonfirmasi.'],enterprise:['Diskusikan kebutuhan organisasi Anda.','Sampaikan kebutuhan akses, data, integrasi, dan dukungan sebelum menentukan ruang lingkup layanan.'],changelog:['Perkembangan produk yang dapat ditelusuri.','Status kemampuan pada website ditinjau dari source aplikasi Lumaway, tanpa menjanjikan tanggal rilis yang belum ditetapkan.']};
export function generateStaticParams(){return [...capabilities.map(c=>c.slug),...Object.keys(pages),...Object.keys(catalog)].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=capabilities.find(c=>c.slug===slug);const p=pages[slug];const entry=c?[c.name,c.description]:p?[p.title,p.description]:catalog[slug];if(!entry)return {};return meta(entry[0],entry[1],`/${slug}`)}
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const {slug}=await params;const query=await searchParams;const c=capabilities.find(c=>c.slug===slug);const p=pages[slug];const entry=c?[c.headline,c.description]:p?[p.title,p.description]:catalog[slug];if(!entry)notFound();const enabled=Boolean(process.env.MARKETING_SUPABASE_URL&&process.env.MARKETING_SUPABASE_SECRET_KEY&&process.env.LEAD_RATE_LIMIT_SALT);const type=typeof query.type==='string'&&leadKinds.includes(query.type as LeadKind)?query.type as LeadKind:'demo';
 return <><div className="container"><header className="inner-hero"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/home">Beranda</Link><span>/</span><span>{c?.name||({about:'Tentang',privacy:'Privasi',terms:'Ketentuan',cookies:'Cookie',security:'Keamanan',...Object.fromEntries(Object.keys(catalog).map(k=>[k,({product:'Produk',solutions:'Solusi',pricing:'Harga',insights:'Wawasan',resources:'Panduan',contact:'Hubungi Tim',roadmap:'Arah pengembangan',customers:'Cerita pelanggan',integrations:'Integrasi',enterprise:'Organisasi',changelog:'Pembaruan'} as Record<string,string>)[k]]))} as Record<string,string>)[slug]}</span></nav><span className="eyebrow">{c?.name||'LUMAWAY · LIGHT UP YOUR POTENTIAL.'}{c&&<Status value={c.status}/>}</span><h1>{entry[0]}</h1><p>{entry[1]}</p></header>
 {c&&<div className="inner-body"><div className="content-grid"><section className="editorial-block"><h2>Tantangan yang ingin dijawab</h2><p>{c.challenge}</p><h2>Arah yang ingin dihasilkan</h2><p>{c.outcome}</p></section><section className="editorial-block"><h2>Mulai dari alur yang jelas</h2><ol>{c.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="context-note"><b>Status kemampuan</b><br/>{c.evidence}</div><ButtonLink href={c.status==='planned'?`/contact?type=waitlist&module=${encodeURIComponent(c.name)}`:'/contact?type=demo'}>{c.status==='planned'?'Daftarkan minat':'Diskusikan penggunaan'}</ButtonLink></section></div><SectionHeading eyebrow="KEMAMPUAN TERKAIT" title="Lengkapi sudut pandang Anda."/><div className="related-links">{c.related.map(r=><Link key={r} href={`/${r}`}>{capabilities.find(x=>x.slug===r)?.name} ↗</Link>)}</div></div>}
 {p&&<div className="inner-body policy-content">{p.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.text.map(t=><p key={t}>{t}</p>)}</section>)}<div className="related-links"><Link href="/contact?type=sales">Hubungi tim Lumaway ↗</Link></div></div>}
 {slug==='product'&&<div className="inner-body"><ProductStories/><div className="section"><CapabilityList/></div><Workflow/></div>}
 {slug==='solutions'&&<div className="inner-body audience-grid">{audiences.map(a=><Link className="audience-card" href={`/solutions/${a.slug}`} key={a.slug}><span className="eyebrow">{a.short}</span><h2>{a.name}</h2><p>{a.description}</p><span className="text-link">Pelajari solusi<ArrowUpRight size={17}/></span></Link>)}</div>}
 {slug==='insights'&&<div className="inner-body"><ArticleCards/><div className="section content-grid"><div className="editorial-block"><span className="eyebrow">LUMAWAY INSIGHTS</span><h2>Dapatkan perspektif berikutnya.</h2><p>Daftarkan minat untuk menerima wawasan dan kabar pengembangan Lumaway melalui email.</p></div><LeadForm kind="newsletter" enabled={enabled}/></div></div>}
 {slug==='pricing'&&<div className="inner-body"><div className="content-grid"><div className="editorial-block"><h2>Kebutuhan dahulu, baru paket.</h2><p>Harga final dan paket komersial belum dipublikasikan. Tim dapat membahas kebutuhan Anda sebelum menawarkan akses yang sesuai.</p><p>Pembuatan akun tidak otomatis berarti seluruh modul tersedia gratis. Ketentuan uji coba, pembatalan, dan perpanjangan mengikuti penawaran tertulis.</p><ButtonLink href="/contact?type=sales" event="pricing_plan_click">Diskusikan kebutuhan akses</ButtonLink></div><div className="editorial-block"><h2>Hal yang akan dibahas</h2><ul>{['Modul dan use case prioritas','Jumlah workspace serta pengguna','Volume data dan histori yang diperlukan','Kebutuhan kuota AI atau token','Ekspor, notifikasi, dan kolaborasi','Kebutuhan integrasi serta dukungan','Retensi data dan ketentuan layanan'].map(item=><li key={item}>{item}</li>)}</ul></div></div>{plans.filter(p=>p.approved).map(p=><div className="context-note" key={p.name}><h3>{p.name}</h3><p>{p.audience}</p><p>{p.price!==null?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR'}).format(p.price):'Diskusikan dengan tim'}</p>{p.features.map(f=><p key={f}>{f}</p>)}</div>)}<Faq items={faqs.filter(x=>/harga|coba|pembatalan/.test(x.q))}/></div>}
 {slug==='roadmap'&&<div className="inner-body"><div className="context-note">Label Beta menunjukkan implementasi pada source aplikasi; belum merupakan verifikasi layanan produksi. Label Direncanakan tidak menyatakan tanggal peluncuran. Cakupan dapat berubah berdasarkan validasi produk.</div><CapabilityList/></div>}
 {slug==='contact'&&<div className="contact-layout"><div className="contact-copy"><h2>Mulai dengan kebutuhan yang nyata.</h2><p>Pilih tujuan Anda dan ceritakan tantangan utama tim. Anda tidak perlu menyiapkan data operasional untuk memulai diskusi.</p><ul><li>Kenali kemampuan yang relevan.</li><li>Bahas kebutuhan pengguna dan data.</li><li>Catat minat untuk modul yang masih dikembangkan.</li></ul>{site.contactEmail&&<p><a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a></p>}<div className="context-note">Jangan menyertakan password, API key, atau data pelanggan pada formulir ini.</div></div><LeadForm key={`${type}-${query.module||''}`} kind={type} module={typeof query.module==='string'?query.module:''} enabled={enabled}/></div>}
 {slug==='resources'&&<div className="inner-body content-grid"><section className="editorial-block"><span className="eyebrow">PANDUAN PRAKTIS</span><h2>Kerangka eksperimen R&D marketing.</h2><p>Gunakan panduan singkat untuk mencatat pertanyaan, bukti, hipotesis, indikator, serta evaluasi eksperimen.</p><ol><li>Mulai dari masalah audiens.</li><li>Tentukan bukti dan asumsi.</li><li>Susun eksperimen yang bisa dievaluasi.</li><li>Catat keputusan berikutnya.</li></ol><Link className="text-link" href="/insights/rnd-marketing-dari-hipotesis-ke-eksperimen">Baca artikel pendamping<ArrowUpRight size={17}/></Link></section><LeadForm kind="resource" enabled={enabled}/></div>}
 {slug==='customers'&&<div className="inner-body"><div className="empty-proof"><h2>Cerita penggunaan akan ditambahkan setelah diverifikasi.</h2><p>Kami belum mempublikasikan testimoni atau hasil pelanggan di halaman ini. Untuk menilai kecocokan produk, diskusikan kebutuhan Anda melalui demo.</p><div className="form-spaced"><ButtonLink href="/contact?type=demo">Diskusikan penggunaan</ButtonLink></div></div></div>}
 {slug==='integrations'&&<div className="inner-body content-grid"><section className="editorial-block"><h2>Unggahan laporan sebagai fondasi</h2><p>Source aplikasi memiliki Upload Center untuk memproses laporan sesuai format yang didukung. Kualitas analisis mengikuti kelengkapan, definisi, serta periode data sumber.</p><Link href="/commerce-intelligence" className="text-link">Kenali Commerce Intelligence<ArrowUpRight size={17}/></Link></section><section className="editorial-block"><h2>Koneksi langsung perlu diverifikasi</h2><p>Website ini tidak menyatakan adanya kemitraan platform, akses API penjualan kompetitor, atau integrasi langsung marketplace yang belum dikonfirmasi. Kebutuhan koneksi baru dibahas sesuai hak akses dan ketentuan sumber data.</p></section></div>}
 {slug==='enterprise'&&<div className="inner-body"><UseCases/><div className="context-note">Dukungan organisasi, SLA, batas pengguna, dan integrasi khusus mengikuti evaluasi kebutuhan. Tidak ada kapasitas atau layanan tambahan yang dijanjikan tanpa ruang lingkup tertulis.</div><ButtonLink href="/contact?type=sales">Diskusikan kebutuhan organisasi</ButtonLink></div>}
 {slug==='changelog'&&<div className="inner-body editorial-block"><h2>September 2026 · Website marketing</h2><p>Website marketing terpisah dari aplikasi: penjelasan kemampuan, solusi per audiens, wawasan, status pengembangan, dan kanal permintaan demo.</p><Link className="text-link" href="/roadmap">Lihat status kemampuan<ArrowUpRight size={17}/></Link></div>}
 </div>{!['contact','privacy','terms','cookies'].includes(slug)&&<FinalCta/>}<JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Beranda',item:site.homeUrl},{'@type':'ListItem',position:2,name:c?.name||entry[0],item:`${site.url}/${slug}`}]}}/></>;
}
