import {test} from 'node:test';
import assert from 'node:assert/strict';
import {leadSchema,sanitizedAttribution} from '../lib/leads';
import {POST} from '../app/api/leads/route';
const valid={kind:'demo',email:'qa@example.invalid',name:'QA',company:'QA test',consent:true,requestId:'40be8f1c-0dab-4d86-8494-be2304b615dc'};
const request=(body:unknown,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/leads',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const proxiedRequest=(body:unknown)=>new Request('https://lumaway-marketing.vercel.app/web/api/leads',{method:'POST',headers:{Origin:'https://lumaway.online','Content-Type':'application/json'},body:JSON.stringify(body)});
test('requires consent and validates conditional fields',()=>{assert.equal(leadSchema.safeParse({...valid,consent:false}).success,false);assert.equal(leadSchema.safeParse({...valid,name:''}).success,false);assert.equal(leadSchema.safeParse({...valid,kind:'newsletter',name:'',company:'',marketingConsent:true}).success,true);assert.equal(leadSchema.safeParse({...valid,kind:'newsletter',marketingConsent:false}).success,false)});
test('removes URL query and fragment attribution',()=>{assert.deepEqual(sanitizedAttribution({landing_page:'https://lumaway.online/contact?email=secret#x',referrer:'https://source.example/path?token=secret'}),{landing_page:'/contact',referrer:'https://source.example'})});
test('refuses other origins and oversized bodies',async()=>{assert.equal((await POST(request(valid,'https://other.example'))).status,403);assert.equal((await POST(request({...valid,challenge:'x'.repeat(17000)}))).status,413)});
test('does not return success without storage configuration',async()=>{const keys=['MARKETING_SUPABASE_URL','MARKETING_SUPABASE_SECRET_KEY','LEAD_RATE_LIMIT_SALT'];const old=keys.map(k=>process.env[k]);try{keys.forEach(k=>delete process.env[k]);assert.equal((await POST(request(valid))).status,503);assert.equal((await POST(proxiedRequest(valid))).status,503)}finally{keys.forEach((k,i)=>old[i]===undefined?delete process.env[k]:process.env[k]=old[i])}});
test('storage failure and rate limiting never become success; success requires an ID',async()=>{const oldFetch=globalThis.fetch;const env={...process.env};process.env.MARKETING_SUPABASE_URL='https://storage.example';process.env.MARKETING_SUPABASE_SECRET_KEY='sb_secret_test';process.env.LEAD_RATE_LIMIT_SALT='test-only-not-a-production-secret';try{
 globalThis.fetch=async()=>Response.json({message:'storage_failed'},{status:500});assert.equal((await POST(request(valid))).status,502);
 globalThis.fetch=async()=>Response.json({message:'marketing_rate_limit'},{status:400});assert.equal((await POST(request(valid))).status,429);
 globalThis.fetch=async()=>Response.json({ok:true});assert.equal((await POST(request(valid))).status,502);
 globalThis.fetch=async(input,init)=>{assert.ok(String(input).endsWith('/rpc/marketing_capture_lead'));const headers=init?.headers as Record<string,string>;assert.equal(headers.Authorization,undefined);const parsed=JSON.parse(init?.body as string);assert.equal(parsed.p_payload.email,valid.email);assert.equal(parsed.p_fingerprint.length,64);return Response.json('75a18c52-ff9c-4b30-81f2-2f05e8c08b10')};const result=await POST(request(valid));assert.equal(result.status,201);assert.ok((await result.json()).id);
 }finally{globalThis.fetch=oldFetch;for(const k of ['MARKETING_SUPABASE_URL','MARKETING_SUPABASE_SECRET_KEY','LEAD_RATE_LIMIT_SALT']){if(env[k]===undefined)delete process.env[k];else process.env[k]=env[k]}}});
