-- PR77D: Seed 12 global tutorials + 20 SEO-friendly Lumaway articles

insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Mulai Menggunakan Workspace Lumaway','Panduan pertama dari login, memilih workspace, mengenali navigasi, sampai membuka dashboard utama.',null,null,'Getting Started','Published',1,null,'mulai-workspace','/learning/tutorial-01-mulai-workspace-cover.svg','/learning/tutorial-01-mulai-workspace-motion.svg',null,null,null,true,true,'Pemula',4,'dashboard','Lumaway',now(),'Mulai Menggunakan Workspace Lumaway | Tutorial Lumaway','Panduan pertama dari login, memilih workspace, mengenali navigasi, sampai membuka dashboard utama.'
where not exists(select 1 from public.tutorials where slug='mulai-workspace' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Masuk ke Lumaway','Buka halaman login Lumaway lalu gunakan email yang terdaftar. Setelah autentikasi berhasil, sistem akan membawa Anda ke workspace yang memiliki akses aktif.','/learning/tutorial-01-mulai-workspace-cover.svg','/learning/tutorial-01-mulai-workspace-motion.svg','Masuk Dashboard','dashboard' from public.tutorials where slug='mulai-workspace' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Kenali sidebar','Sidebar mengelompokkan Data & Intelligence, Insights & Analysis, Affiliate & Creator, Product & Commerce, Growth & Workflow, Support & Billing, serta Content & Community.','/learning/tutorial-01-mulai-workspace-cover.svg','/learning/tutorial-01-mulai-workspace-motion.svg','Lihat Dashboard','dashboard' from public.tutorials where slug='mulai-workspace' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Periksa status workspace','Pastikan nama workspace dan status Active tampil di bagian atas. Jika akses terkunci, buka Billing untuk memeriksa status langganan.','/learning/tutorial-01-mulai-workspace-cover.svg','/learning/tutorial-01-mulai-workspace-motion.svg','Buka Billing','billing' from public.tutorials where slug='mulai-workspace' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Mulai dari Dashboard','Gunakan Dashboard untuk melihat KPI, tren performa, kontribusi platform, ranking produk, dan creator sesuai periode yang dipilih.','/learning/tutorial-01-mulai-workspace-cover.svg','/learning/tutorial-01-mulai-workspace-motion.svg','Pelajari Dashboard','dashboard' from public.tutorials where slug='mulai-workspace' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Upload Affiliate Performance','Cara mengimpor data performa affiliate dengan alur Upload → Mapping → Preview → Import.',null,null,'Data & Upload','Published',2,null,'upload-affiliate-performance','/learning/tutorial-02-upload-affiliate-performance-cover.svg','/learning/tutorial-02-upload-affiliate-performance-motion.svg',null,null,null,true,true,'Pemula',6,'upload','Lumaway',now(),'Upload Affiliate Performance | Tutorial Lumaway','Cara mengimpor data performa affiliate dengan alur Upload → Mapping → Preview → Import.'
where not exists(select 1 from public.tutorials where slug='upload-affiliate-performance' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Pilih Affiliate Performance','Masuk ke Upload Center lalu pilih Affiliate Performance. Tentukan platform dan periode bila diperlukan.','/learning/tutorial-02-upload-affiliate-performance-cover.svg','/learning/tutorial-02-upload-affiliate-performance-motion.svg','Buka Upload Center','upload' from public.tutorials where slug='upload-affiliate-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Upload file CSV/XLSX','Pilih file dari marketplace. Lumaway membaca header, mendeteksi platform, dan menyiapkan Auto Map.','/learning/tutorial-02-upload-affiliate-performance-cover.svg','/learning/tutorial-02-upload-affiliate-performance-motion.svg','Pilih File','upload' from public.tutorials where slug='upload-affiliate-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Periksa Mapping','Cocokkan Creator Name/Username/Affiliate ID serta GMV, Qty, Orders, Commission dan metrik lain. Jangan lanjut jika mapping wajib belum lengkap.','/learning/tutorial-02-upload-affiliate-performance-cover.svg','/learning/tutorial-02-upload-affiliate-performance-motion.svg','Periksa Data Health','data-health' from public.tutorials where slug='upload-affiliate-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Preview lalu Import','Periksa lima row preview. Setelah sesuai, klik Import Data. Hasil akan masuk ke Dashboard, Ranking Creator, dan Customer 360.','/learning/tutorial-02-upload-affiliate-performance-cover.svg','/learning/tutorial-02-upload-affiliate-performance-motion.svg','Buka Database','database' from public.tutorials where slug='upload-affiliate-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Upload Product Performance','Panduan mengimpor performa produk agar Product Ranking dan Product Master tetap terhubung.',null,null,'Data & Upload','Published',3,null,'upload-product-performance','/learning/tutorial-03-upload-product-performance-cover.svg','/learning/tutorial-03-upload-product-performance-motion.svg',null,null,null,true,false,'Pemula',6,'upload','Lumaway',now(),'Upload Product Performance | Tutorial Lumaway','Panduan mengimpor performa produk agar Product Ranking dan Product Master tetap terhubung.'
where not exists(select 1 from public.tutorials where slug='upload-product-performance' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Pilih Product Performance','Gunakan tipe Product Performance di Upload Center dan pilih platform yang sesuai.','/learning/tutorial-03-upload-product-performance-cover.svg','/learning/tutorial-03-upload-product-performance-motion.svg','Buka Upload Center','upload' from public.tutorials where slug='upload-product-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Pastikan identitas produk','Product ID/Item ID, Product Name, dan GMV wajib terpetakan. SKU sebaiknya konsisten dengan Product Master.','/learning/tutorial-03-upload-product-performance-cover.svg','/learning/tutorial-03-upload-product-performance-motion.svg','Buka Product Master','product-master' from public.tutorials where slug='upload-product-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Periksa preview','Pastikan nilai sales, items sold, orders, refund, click, LIVE, dan video berada di kolom yang benar.','/learning/tutorial-03-upload-product-performance-cover.svg','/learning/tutorial-03-upload-product-performance-motion.svg','Periksa Data Health','data-health' from public.tutorials where slug='upload-product-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Import dan cek ranking','Setelah import selesai, buka Dashboard atau Product Master untuk memastikan produk dan performanya terbaca.','/learning/tutorial-03-upload-product-performance-cover.svg','/learning/tutorial-03-upload-product-performance-motion.svg','Buka Dashboard','dashboard' from public.tutorials where slug='upload-product-performance' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Mapping Kolom Agar Data Tidak Gagal','Cara menangani perubahan header TikTok, Shopee, atau file internal tanpa merusak database Lumaway.',null,null,'Data & Upload','Published',4,null,'mapping-data','/learning/tutorial-04-mapping-data-cover.svg','/learning/tutorial-04-mapping-data-motion.svg',null,null,null,true,true,'Pemula',7,'upload','Lumaway',now(),'Mapping Kolom Agar Data Tidak Gagal | Tutorial Lumaway','Cara menangani perubahan header TikTok, Shopee, atau file internal tanpa merusak database Lumaway.'
where not exists(select 1 from public.tutorials where slug='mapping-data' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Baca header file','Setelah file dipilih, Mapping Wizard menampilkan semua header asli dari file.','/learning/tutorial-04-mapping-data-cover.svg','/learning/tutorial-04-mapping-data-motion.svg','Buka Upload Center','upload' from public.tutorials where slug='mapping-data' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Gunakan Auto Map sebagai awal','Auto Map membantu mengenali header umum, tetapi user tetap perlu memeriksa hasilnya sebelum import.','/learning/tutorial-04-mapping-data-cover.svg','/learning/tutorial-04-mapping-data-motion.svg','Periksa Mapping','upload' from public.tutorials where slug='mapping-data' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Perbaiki field wajib','Pilih source column secara manual untuk field yang belum dikenali. Preview akan langsung mengikuti mapping yang dipilih.','/learning/tutorial-04-mapping-data-cover.svg','/learning/tutorial-04-mapping-data-motion.svg','Lihat Preview','upload' from public.tutorials where slug='mapping-data' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Simpan mapping','Simpan mapping untuk struktur file yang sama agar upload berikutnya lebih cepat. Gunakan Data Health untuk menemukan mapping yang putus.','/learning/tutorial-04-mapping-data-cover.svg','/learning/tutorial-04-mapping-data-motion.svg','Buka Data Health','data-health' from public.tutorials where slug='mapping-data' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Kelola Master Creator & Social Profile','Mengelola identitas creator, affiliate ID, ratecard, link sosial, foto profil, dan duplicate identity.',null,null,'Affiliate & Creator','Published',5,null,'master-creator','/learning/tutorial-05-master-creator-cover.svg','/learning/tutorial-05-master-creator-motion.svg',null,null,null,true,false,'Pemula',7,'listings','Lumaway',now(),'Kelola Master Creator & Social Profile | Tutorial Lumaway','Mengelola identitas creator, affiliate ID, ratecard, link sosial, foto profil, dan duplicate identity.'
where not exists(select 1 from public.tutorials where slug='master-creator' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Buka Master Creator','Masuk ke Listings dan gunakan Master Creator untuk melihat creator yang tersedia di workspace.','/learning/tutorial-05-master-creator-cover.svg','/learning/tutorial-05-master-creator-motion.svg','Buka Listings','listings' from public.tutorials where slug='master-creator' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Lengkapi identitas','Isi nama, username, platform, Affiliate ID, phone, payment type, dan ratecard jika tersedia.','/learning/tutorial-05-master-creator-cover.svg','/learning/tutorial-05-master-creator-motion.svg','Buka Listings','listings' from public.tutorials where slug='master-creator' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Tambahkan social profile','Simpan Instagram, TikTok, Facebook, Lemon8, YouTube, Threads, X/Twitter atau link lain. Lumaway mencoba mengambil foto profil dari metadata publik.','/learning/tutorial-05-master-creator-cover.svg','/learning/tutorial-05-master-creator-motion.svg','Buka Listings','listings' from public.tutorials where slug='master-creator' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Review duplicate','Gunakan Creator Identity Center untuk membandingkan record, confidence, linked data, dan menentukan canonical creator secara aman.','/learning/tutorial-05-master-creator-cover.svg','/learning/tutorial-05-master-creator-motion.svg','Buka Creator Identity','creator-identity' from public.tutorials where slug='master-creator' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Listings & Follow Up Creator','Membuat listing creator, mengatur stage, follow up, produk, dan riwayat aktivitas.',null,null,'Affiliate & Creator','Published',6,null,'listings','/learning/tutorial-06-listings-cover.svg','/learning/tutorial-06-listings-motion.svg',null,null,null,true,false,'Pemula',6,'listings','Lumaway',now(),'Listings & Follow Up Creator | Tutorial Lumaway','Membuat listing creator, mengatur stage, follow up, produk, dan riwayat aktivitas.'
where not exists(select 1 from public.tutorials where slug='listings' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Tambah Listing','Klik Tambah Listing lalu pilih creator dan produk yang akan ditindaklanjuti.','/learning/tutorial-06-listings-cover.svg','/learning/tutorial-06-listings-motion.svg','Tambah Listing','listings' from public.tutorials where slug='listings' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Atur stage','Gunakan Reach Out, Follow Up, Negotiation, Sample Sent, Content In Progress atau stage yang sesuai proses kerja tim.','/learning/tutorial-06-listings-cover.svg','/learning/tutorial-06-listings-motion.svg','Buka Listings','listings' from public.tutorials where slug='listings' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Catat aktivitas','Tambahkan note follow up agar tim tidak kehilangan konteks percakapan dan langkah berikutnya.','/learning/tutorial-06-listings-cover.svg','/learning/tutorial-06-listings-motion.svg','Buka Listings','listings' from public.tutorials where slug='listings' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Lanjutkan workflow','Dari creator yang sama, buka Creator Samples, Shipping, Campaign Tracker, atau Customer 360 sesuai kebutuhan.','/learning/tutorial-06-listings-cover.svg','/learning/tutorial-06-listings-motion.svg','Buka Customer 360','listings' from public.tutorials where slug='listings' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Creator Samples dari Pengiriman sampai Konten','Mengelola sample produk dan progresnya sampai konten creator selesai.',null,null,'Affiliate & Creator','Published',7,null,'creator-samples','/learning/tutorial-07-creator-samples-cover.svg','/learning/tutorial-07-creator-samples-motion.svg',null,null,null,true,false,'Pemula',6,'creator-samples','Lumaway',now(),'Creator Samples dari Pengiriman sampai Konten | Tutorial Lumaway','Mengelola sample produk dan progresnya sampai konten creator selesai.'
where not exists(select 1 from public.tutorials where slug='creator-samples' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Tambah sample','Pilih creator, SKU/Product Master, qty, nilai sample, dan tanggal pengiriman.','/learning/tutorial-07-creator-samples-cover.svg','/learning/tutorial-07-creator-samples-motion.svg','Buka Creator Samples','creator-samples' from public.tutorials where slug='creator-samples' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Update status pengiriman','Setelah sample diterima, ubah status dari Sent menjadi Received.','/learning/tutorial-07-creator-samples-cover.svg','/learning/tutorial-07-creator-samples-motion.svg','Buka Creator Samples','creator-samples' from public.tutorials where slug='creator-samples' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Pantau content pending','Saat creator masuk proses pembuatan konten, gunakan Content Pending untuk menjaga follow up tetap terlihat.','/learning/tutorial-07-creator-samples-cover.svg','/learning/tutorial-07-creator-samples-motion.svg','Buka Creator Samples','creator-samples' from public.tutorials where slug='creator-samples' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Tutup workflow','Tandai Content Done jika deliverable selesai, atau Returned/Cancelled bila workflow berhenti.','/learning/tutorial-07-creator-samples-cover.svg','/learning/tutorial-07-creator-samples-motion.svg','Buka Creator Samples','creator-samples' from public.tutorials where slug='creator-samples' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Shipping, Tracking & Preview Resi','Cara membuat pengiriman, menyimpan nomor resi, melihat preview, mengedit, dan menghapus data.',null,null,'Operations','Published',8,null,'shipping','/learning/tutorial-08-shipping-cover.svg','/learning/tutorial-08-shipping-motion.svg',null,null,null,true,false,'Pemula',5,'shipping','Lumaway',now(),'Shipping, Tracking & Preview Resi | Tutorial Lumaway','Cara membuat pengiriman, menyimpan nomor resi, melihat preview, mengedit, dan menghapus data.'
where not exists(select 1 from public.tutorials where slug='shipping' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Tambah Shipping','Buat pengiriman baru dari menu Shipping dan lengkapi penerima, produk, courier, serta informasi paket.','/learning/tutorial-08-shipping-cover.svg','/learning/tutorial-08-shipping-motion.svg','Buka Shipping','shipping' from public.tutorials where slug='shipping' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Masukkan tracking','Simpan nomor AWB/resi agar pengiriman dapat ditelusuri dan terhubung dengan workflow creator.','/learning/tutorial-08-shipping-cover.svg','/learning/tutorial-08-shipping-motion.svg','Buka Shipping','shipping' from public.tutorials where slug='shipping' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Preview template resi','Gunakan preview resi untuk mengecek informasi pengirim, penerima, item, dan reference sebelum diunduh.','/learning/tutorial-08-shipping-cover.svg','/learning/tutorial-08-shipping-motion.svg','Buka Shipping','shipping' from public.tutorials where slug='shipping' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Update status','Perbarui status sampai Delivered/Finish. Notification Center dapat menampilkan pengiriman yang selesai.','/learning/tutorial-08-shipping-cover.svg','/learning/tutorial-08-shipping-motion.svg','Buka Shipping','shipping' from public.tutorials where slug='shipping' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Campaign Tracker untuk Affiliate & Influencer','Membuat campaign, memasang banner, menambahkan creator, dan memantau deliverable, GMV, order, serta komisi.',null,null,'Growth & Workflow','Published',9,null,'campaign-tracker','/learning/tutorial-09-campaign-tracker-cover.svg','/learning/tutorial-09-campaign-tracker-motion.svg',null,null,null,true,true,'Pemula',8,'campaign-tracker','Lumaway',now(),'Campaign Tracker untuk Affiliate & Influencer | Tutorial Lumaway','Membuat campaign, memasang banner, menambahkan creator, dan memantau deliverable, GMV, order, serta komisi.'
where not exists(select 1 from public.tutorials where slug='campaign-tracker' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Buat Campaign','Isi nama campaign, brand, platform, periode, target GMV, target order, budget, dan catatan.','/learning/tutorial-09-campaign-tracker-cover.svg','/learning/tutorial-09-campaign-tracker-motion.svg','Buka Campaign Tracker','campaign-tracker' from public.tutorials where slug='campaign-tracker' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Upload banner','Tambahkan 1–3 banner JPG/PNG/WEBP. Detail campaign menampilkan carousel otomatis setiap 10 detik.','/learning/tutorial-09-campaign-tracker-cover.svg','/learning/tutorial-09-campaign-tracker-motion.svg','Buka Campaign Tracker','campaign-tracker' from public.tutorials where slug='campaign-tracker' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Tambahkan creator','Hubungkan creator ke campaign dan tentukan content/deliverable serta due date.','/learning/tutorial-09-campaign-tracker-cover.svg','/learning/tutorial-09-campaign-tracker-motion.svg','Buka Campaign Tracker','campaign-tracker' from public.tutorials where slug='campaign-tracker' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Pantau hasil','Bandingkan target dan actual GMV/order, status deliverable, sample/shipping, serta commission.','/learning/tutorial-09-campaign-tracker-cover.svg','/learning/tutorial-09-campaign-tracker-motion.svg','Buka Campaign Tracker','campaign-tracker' from public.tutorials where slug='campaign-tracker' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Membaca Customer 360 Creator','Memahami creator dari profil, timeline, sales, produk, support, sample, shipping, dan campaign dalam satu drawer.',null,null,'Insight & Analysis','Published',10,null,'customer-360','/learning/tutorial-10-customer-360-cover.svg','/learning/tutorial-10-customer-360-motion.svg',null,null,null,true,false,'Pemula',7,'listings','Lumaway',now(),'Membaca Customer 360 Creator | Tutorial Lumaway','Memahami creator dari profil, timeline, sales, produk, support, sample, shipping, dan campaign dalam satu drawer.'
where not exists(select 1 from public.tutorials where slug='customer-360' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Buka Customer 360','Klik Customer 360 dari Listing, Creator Samples, atau Ratecard Master.','/learning/tutorial-10-customer-360-cover.svg','/learning/tutorial-10-customer-360-motion.svg','Buka Listings','listings' from public.tutorials where slug='customer-360' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Pilih periode','Gunakan filter periode agar pembacaan GMV, order, item, commission, LIVE, video, click, refund dan sample konsisten.','/learning/tutorial-10-customer-360-cover.svg','/learning/tutorial-10-customer-360-motion.svg','Buka Customer 360','listings' from public.tutorials where slug='customer-360' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Baca timeline','Timeline membantu melihat aktivitas creator lintas listing, sample, shipping, campaign, task, ratecard dan performance.','/learning/tutorial-10-customer-360-cover.svg','/learning/tutorial-10-customer-360-motion.svg','Buka Customer 360','listings' from public.tutorials where slug='customer-360' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Gunakan untuk follow up','Gunakan konteks yang terlihat untuk menentukan tindakan berikutnya tanpa kehilangan histori creator.','/learning/tutorial-10-customer-360-cover.svg','/learning/tutorial-10-customer-360-motion.svg','Buka Listings','listings' from public.tutorials where slug='customer-360' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Cara Membaca Dashboard & Visual Chart','Memahami KPI, tren performa, kontribusi platform, ranking, serta chart yang mengikuti periode dan metrik pilihan.',null,null,'Insight & Analysis','Published',11,null,'dashboard-chart','/learning/tutorial-11-dashboard-chart-cover.svg','/learning/tutorial-11-dashboard-chart-motion.svg',null,null,null,true,true,'Pemula',7,'dashboard','Lumaway',now(),'Cara Membaca Dashboard & Visual Chart | Tutorial Lumaway','Memahami KPI, tren performa, kontribusi platform, ranking, serta chart yang mengikuti periode dan metrik pilihan.'
where not exists(select 1 from public.tutorials where slug='dashboard-chart' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Pilih periode','Pastikan rentang tanggal dan platform sesuai pertanyaan yang ingin dijawab.','/learning/tutorial-11-dashboard-chart-cover.svg','/learning/tutorial-11-dashboard-chart-motion.svg','Buka Dashboard','dashboard' from public.tutorials where slug='dashboard-chart' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Baca KPI utama','Gunakan GMV, Orders, Qty Paid, Creator Aktif, Commission, ROI, LIVE, Video, dan metrik lain sebagai ringkasan.','/learning/tutorial-11-dashboard-chart-cover.svg','/learning/tutorial-11-dashboard-chart-motion.svg','Buka Dashboard','dashboard' from public.tutorials where slug='dashboard-chart' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Gunakan Tren Performa','Pilih metrik yang ingin dilihat sebagai time-series untuk memahami perubahan antar hari/periode.','/learning/tutorial-11-dashboard-chart-cover.svg','/learning/tutorial-11-dashboard-chart-motion.svg','Buka Dashboard','dashboard' from public.tutorials where slug='dashboard-chart' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Drill down ke detail','Gunakan Product Ranking, Creator Ranking, Product Master, Customer 360 atau Data Health untuk menelusuri angka yang tidak wajar.','/learning/tutorial-11-dashboard-chart-cover.svg','/learning/tutorial-11-dashboard-chart-motion.svg','Buka Data Health','data-health' from public.tutorials where slug='dashboard-chart' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.tutorials(title,description,youtube_url,embed_url,category,status,sort_order,workspace_id,slug,cover_image_url,cover_gif_url,short_video_url,instagram_url,tiktok_url,is_global,is_featured,difficulty,estimated_minutes,feature_route,author_name,published_at,seo_title,seo_description)
select 'Menggunakan Promo di Billing Lumaway','Cara melihat promo, menyalin kode, memvalidasi benefit, dan menggunakannya saat checkout.',null,null,'Billing','Published',12,null,'promo-billing','/learning/tutorial-12-promo-billing-cover.svg','/learning/tutorial-12-promo-billing-motion.svg',null,null,null,true,false,'Pemula',4,'billing','Lumaway',now(),'Menggunakan Promo di Billing Lumaway | Tutorial Lumaway','Cara melihat promo, menyalin kode, memvalidasi benefit, dan menggunakannya saat checkout.'
where not exists(select 1 from public.tutorials where slug='promo-billing' and is_global=true);
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,1,'Pilih promo aktif','Buka Insight & Blog → Promotion untuk melihat campaign yang masih aktif dan syarat singkatnya.','/learning/tutorial-12-promo-billing-cover.svg','/learning/tutorial-12-promo-billing-motion.svg','Lihat Promo','content-hub' from public.tutorials where slug='promo-billing' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,2,'Salin kode','Gunakan kode yang tertera. Setiap promo memiliki kuota, periode, dan limit penggunaan per user.','/learning/tutorial-12-promo-billing-cover.svg','/learning/tutorial-12-promo-billing-motion.svg','Buka Billing','billing' from public.tutorials where slug='promo-billing' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,3,'Validasi promo','Masukkan kode pada Billing. Lumaway memeriksa tanggal, kuota, eligibility, minimum transaksi, serta apakah kode pernah digunakan.','/learning/tutorial-12-promo-billing-cover.svg','/learning/tutorial-12-promo-billing-motion.svg','Validasi Promo','billing' from public.tutorials where slug='promo-billing' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();
insert into public.luma_tutorial_steps(tutorial_id,step_no,title,description,image_url,gif_url,cta_label,cta_route)
select id,4,'Checkout','Jika promo valid, discount diterapkan pada checkout. Promo baru dianggap terpakai ketika transaksi berhasil, dengan reservation anti-double selama proses pembayaran.','/learning/tutorial-12-promo-billing-cover.svg','/learning/tutorial-12-promo-billing-motion.svg','Buka Billing','billing' from public.tutorials where slug='promo-billing' and is_global=true
on conflict(tutorial_id,step_no) do update set title=excluded.title,description=excluded.description,image_url=excluded.image_url,gif_url=excluded.gif_url,cta_label=excluded.cta_label,cta_route=excluded.cta_route,updated_at=now();

-- SEO article seed
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'cara-upload-data-affiliate-tanpa-bikin-dashboard-kacau','Cara Upload Data Affiliate Tanpa Bikin Dashboard Kacau','Panduan aman mengimpor data affiliate memakai Mapping Wizard, preview, dan Data Health sebelum membaca dashboard.','<h2>Mulai dari struktur, bukan dari tombol upload</h2><p>Masalah upload sering bukan terjadi karena file rusak, tetapi karena nama kolom berubah atau definisi metrik berbeda. Karena itu Lumaway memisahkan proses menjadi Upload, Mapping, Preview, lalu Import.</p><h2>Periksa identitas creator dan metrik utama</h2><p>Pastikan minimal ada identitas creator seperti username atau Affiliate ID serta salah satu metrik GMV, Qty, Orders, atau Commission. Mapping wajib yang kosong akan menghentikan proses sebelum data ditulis.</p><h2>Gunakan preview sebagai pemeriksaan terakhir</h2><p>Lihat beberapa row pertama dan pastikan angka masuk ke field yang benar. Jika hasilnya janggal, perbaiki mapping sebelum menekan Import Data.</p><h2>Tutup dengan Data Health</h2><p>Setelah import, buka Data Health untuk mengecek row tanpa creator, row dengan seluruh metrik nol, duplicate identity, serta masalah mapping produk.</p>','Tutorial Lumaway','/insights/01-cara-upload-data-affiliate-tanpa-bikin-dashboard-kacau.svg','Cara Upload Data Affiliate Tanpa Bikin Dashboard Kacau','Panduan aman mengimpor data affiliate memakai Mapping Wizard, preview, dan Data Health sebelum membaca dashboard.',array['upload data affiliate','mapping data','lumaway'],'published',now(),'Lumaway',null,'Cara Upload Data Affiliate Tanpa Bikin Dashboard Kacau','article',array['upload data affiliate','mapping data','lumaway'],true,true,4,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'apa-itu-business-intelligence-operating-workspace','Apa Itu Business Intelligence Operating Workspace?','Memahami perbedaan dashboard laporan dengan workspace yang menghubungkan data, insight, keputusan, dan tindak lanjut.','<h2>Dashboard menjawab apa yang terjadi</h2><p>Dashboard membantu merangkum kondisi, tetapi keputusan bisnis sering membutuhkan konteks tambahan: sumber data, periode, creator, produk, biaya, serta tindakan yang sudah dilakukan.</p><h2>Operating workspace menyambungkan konteks</h2><p>Lumaway dirancang agar upload data, Creator 360, Product Master, Campaign Tracker, Kanban, dan workflow operasional dapat dibaca sebagai rangkaian, bukan halaman terpisah.</p><h2>Nilainya muncul ketika tim kembali setiap hari</h2><p>Workspace menjadi berguna ketika tim memakai definisi data yang konsisten, mencatat tindakan, dan mengevaluasi hasil dengan periode yang sebanding.</p>','Business & Growth','/insights/02-apa-itu-business-intelligence-operating-workspace.svg','Apa Itu Business Intelligence Operating Workspace?','Memahami perbedaan dashboard laporan dengan workspace yang menghubungkan data, insight, keputusan, dan tindak lanjut.',array['business intelligence','operating workspace','dashboard bisnis'],'published',now(),'Lumaway',null,'Apa Itu Business Intelligence Operating Workspace?','article',array['business intelligence','operating workspace','dashboard bisnis'],true,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'kpi-affiliate-yang-perlu-dipantau','KPI Affiliate yang Perlu Dipantau, Bukan Cuma GMV','GMV penting, tetapi evaluasi affiliate juga membutuhkan order, qty, commission, content, click, refund, sample, dan konteks produk.','<h2>GMV bukan satu-satunya sinyal</h2><p>GMV menunjukkan nilai transaksi pada definisi laporan tertentu. Untuk memahami kualitas kontribusi, baca bersama order, item, komisi, refund, dan distribusi produk.</p><h2>Tambahkan konteks aktivitas</h2><p>Jumlah video, LIVE, sample, click, dan periode aktif membantu menjelaskan mengapa dua creator dengan GMV serupa dapat memiliki pola kerja yang berbeda.</p><h2>Gunakan metrik untuk menentukan pertanyaan berikutnya</h2><p>KPI bukan nilai moral untuk creator. Gunakan angka untuk menyusun follow up, eksperimen produk, dan prioritas campaign berikutnya.</p>','Affiliate & Creator','/insights/03-kpi-affiliate-yang-perlu-dipantau.svg','KPI Affiliate yang Perlu Dipantau, Bukan Cuma GMV','GMV penting, tetapi evaluasi affiliate juga membutuhkan order, qty, commission, content, click, refund, sample, dan konteks produk.',array['kpi affiliate','gmv','creator performance'],'published',now(),'Lumaway',null,'KPI Affiliate yang Perlu Dipantau, Bukan Cuma GMV','article',array['kpi affiliate','gmv','creator performance'],true,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'cara-mengelola-database-creator','Cara Mengelola Database Creator agar Tidak Penuh Duplikasi','Prinsip identity management untuk username, affiliate ID, social profile, ratecard, dan histori creator.','<h2>Gunakan identitas yang stabil</h2><p>Nama display dapat berubah. Prioritaskan username, Affiliate ID, platform, dan link profil yang dapat diverifikasi.</p><h2>Pisahkan kandidat duplicate dari keputusan merge</h2><p>Creator Identity Center menampilkan confidence dan linked data agar user dapat membandingkan record sebelum memilih canonical creator.</p><h2>Jangan merge identity sampah</h2><p>Nilai seperti kosong, --, N/A, atau unknown harus dipisahkan karena banyak creator berbeda dapat jatuh ke key yang sama jika data sumber buruk.</p>','Affiliate & Creator','/insights/04-cara-mengelola-database-creator.svg','Cara Mengelola Database Creator agar Tidak Penuh Duplikasi','Prinsip identity management untuk username, affiliate ID, social profile, ratecard, dan histori creator.',array['database creator','creator identity','duplicate creator'],'published',now(),'Lumaway',null,'Cara Mengelola Database Creator agar Tidak Penuh Duplikasi','article',array['database creator','creator identity','duplicate creator'],true,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'customer-360-untuk-tim-affiliate','Customer 360 untuk Tim Affiliate: Apa yang Perlu Dilihat?','Cara memakai Customer 360 sebagai pusat konteks creator tanpa memindahkan data antar spreadsheet.','<h2>Mulai dari profil creator</h2><p>Periksa identity, platform, social profile, ratecard dan informasi kontak sebelum membaca performa.</p><h2>Baca timeline lintas aktivitas</h2><p>Listing, sample, shipping, campaign, task, ratecard dan performance menjadi lebih berguna ketika disusun berdasarkan waktu.</p><h2>Jaga hubungan antara data dan tindakan</h2><p>Setelah menemukan pola, catat follow up atau task agar insight tidak berhenti sebagai angka.</p>','Product Knowledge','/insights/05-customer-360-untuk-tim-affiliate.svg','Customer 360 untuk Tim Affiliate: Apa yang Perlu Dilihat?','Cara memakai Customer 360 sebagai pusat konteks creator tanpa memindahkan data antar spreadsheet.',array['customer 360','creator 360','affiliate crm'],'published',now(),'Lumaway',null,'Customer 360 untuk Tim Affiliate: Apa yang Perlu Dilihat?','article',array['customer 360','creator 360','affiliate crm'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'product-master-sku-induk','Kenapa Product Master Butuh SKU Induk yang Konsisten?','Cara menjaga hubungan antara Product ID marketplace, variasi, HPP, dan performa lintas platform.','<h2>Marketplace dapat memiliki kode yang berbeda</h2><p>Satu produk bisnis dapat memiliki Product ID Shopee dan TikTok yang berbeda. SKU induk membantu menyatukan konteks produk.</p><h2>HPP harus berada pada level yang benar</h2><p>HPP yang kosong atau salah akan memengaruhi pembacaan margin, ROI, dan guardrail promo.</p><h2>Mapping produk harus dapat diaudit</h2><p>Simpan kode platform, nama produk, variasi, dan SKU secara eksplisit agar perubahan file marketplace tetap dapat ditelusuri.</p>','Product Knowledge','/insights/06-product-master-sku-induk.svg','Kenapa Product Master Butuh SKU Induk yang Konsisten?','Cara menjaga hubungan antara Product ID marketplace, variasi, HPP, dan performa lintas platform.',array['product master','sku induk','hpp'],'published',now(),'Lumaway',null,'Kenapa Product Master Butuh SKU Induk yang Konsisten?','article',array['product master','sku induk','hpp'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'campaign-tracker-affiliate','Cara Menjalankan Campaign Affiliate dengan Tracker yang Rapi','Kerangka campaign dari target, creator, banner, deliverable, sample, shipping sampai hasil.','<h2>Definisikan target dan periode</h2><p>Tentukan objective, platform, target GMV/order, budget, start date dan end date sebelum campaign berjalan.</p><h2>Hubungkan creator dan deliverable</h2><p>Setiap creator perlu memiliki content type, due date, stage, sample/shipping, dan target yang bisa dipantau.</p><h2>Evaluasi target vs actual</h2><p>Setelah campaign berjalan, baca deliverable progress bersama GMV, order, commission dan biaya pendukung.</p>','Campaign & Promotion','/insights/07-campaign-tracker-affiliate.svg','Cara Menjalankan Campaign Affiliate dengan Tracker yang Rapi','Kerangka campaign dari target, creator, banner, deliverable, sample, shipping sampai hasil.',array['campaign affiliate','campaign tracker','influencer'],'published',now(),'Lumaway',null,'Cara Menjalankan Campaign Affiliate dengan Tracker yang Rapi','article',array['campaign affiliate','campaign tracker','influencer'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'cara-membaca-tren-performa','Cara Membaca Tren Performa Tanpa Tertipu Angka Harian','Prinsip membaca time-series GMV, order, qty, commission, dan metrik lain secara lebih kontekstual.','<h2>Pilih periode yang sesuai</h2><p>Perubahan harian dapat terlihat dramatis pada periode pendek. Gunakan rentang yang relevan dengan siklus campaign dan aktivitas bisnis.</p><h2>Bedakan level dan perubahan</h2><p>Nilai hari ini dan persentase perubahan menjawab pertanyaan berbeda. Selalu periksa basis pembanding.</p><h2>Cari konteks di bawah grafik</h2><p>Gunakan ranking creator, product ranking, campaign, dan event operasional untuk memahami perubahan yang terlihat pada chart.</p>','Data & Analytics','/insights/08-cara-membaca-tren-performa.svg','Cara Membaca Tren Performa Tanpa Tertipu Angka Harian','Prinsip membaca time-series GMV, order, qty, commission, dan metrik lain secara lebih kontekstual.',array['trend chart','time series','gmv harian'],'published',now(),'Lumaway',null,'Cara Membaca Tren Performa Tanpa Tertipu Angka Harian','article',array['trend chart','time series','gmv harian'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'data-health-sebelum-analisis','Kenapa Data Health Perlu Dicek Sebelum Membuat Kesimpulan?','Data yang tidak terhubung, duplicate, nol, atau salah mapping dapat membuat visual terlihat meyakinkan tetapi menyesatkan.','<h2>Analisis bagus membutuhkan input yang dapat dipercaya</h2><p>Chart tidak dapat memperbaiki identitas creator yang putus atau Product ID yang salah mapping.</p><h2>Pisahkan critical dan warning</h2><p>Critical berarti ada hubungan data penting yang putus. Warning berarti data mungkin tetap valid tetapi membutuhkan pemeriksaan.</p><h2>Jadikan health check sebagai rutinitas</h2><p>Cek setelah import besar, perubahan template marketplace, atau ketika dashboard tiba-tiba berubah signifikan.</p>','Data & Analytics','/insights/09-data-health-sebelum-analisis.svg','Kenapa Data Health Perlu Dicek Sebelum Membuat Kesimpulan?','Data yang tidak terhubung, duplicate, nol, atau salah mapping dapat membuat visual terlihat meyakinkan tetapi menyesatkan.',array['data quality','data health','analytics'],'published',now(),'Lumaway',null,'Kenapa Data Health Perlu Dicek Sebelum Membuat Kesimpulan?','article',array['data quality','data health','analytics'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'shipping-sample-creator','Menghubungkan Sample dan Shipping dalam Workflow Creator','Mengapa sample, resi, status diterima, dan hasil konten sebaiknya berada dalam satu alur.','<h2>Sample adalah biaya dan komitmen</h2><p>Sample yang dikirim perlu memiliki creator, SKU, qty, nilai produk dan tanggal yang jelas.</p><h2>Tracking mengurangi blind spot</h2><p>Nomor resi membantu tim membedakan sample yang belum dikirim, sedang berjalan, sudah diterima, atau membutuhkan follow up.</p><h2>Workflow berakhir pada outcome</h2><p>Setelah diterima, lanjutkan ke Content Pending dan Content Done agar pengiriman tidak berhenti sebagai aktivitas logistik.</p>','Operations','/insights/10-shipping-sample-creator.svg','Menghubungkan Sample dan Shipping dalam Workflow Creator','Mengapa sample, resi, status diterima, dan hasil konten sebaiknya berada dalam satu alur.',array['creator sample','shipping','affiliate operations'],'published',now(),'Lumaway',null,'Menghubungkan Sample dan Shipping dalam Workflow Creator','article',array['creator sample','shipping','affiliate operations'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'cara-menilai-ratecard-creator','Cara Membaca Ratecard Creator dalam Konteks Bisnis','Ratecard sebaiknya dibaca bersama histori, deliverable, performa, dan tujuan campaign.','<h2>Ratecard bukan angka yang berdiri sendiri</h2><p>Harga creator perlu dibandingkan dengan jenis deliverable, periode, platform, dan scope pekerjaan.</p><h2>Lihat histori dan keterhubungan</h2><p>Profile view membantu menempatkan ratecard saat ini bersama history dan aktivitas creator.</p><h2>Gunakan untuk budgeting, bukan label kualitas</h2><p>Ratecard membantu menyusun biaya campaign. Kualitas creator tetap perlu dinilai dari kecocokan audience, konten, dan hasil yang relevan.</p>','Affiliate & Creator','/insights/11-cara-menilai-ratecard-creator.svg','Cara Membaca Ratecard Creator dalam Konteks Bisnis','Ratecard sebaiknya dibaca bersama histori, deliverable, performa, dan tujuan campaign.',array['ratecard creator','creator cost','campaign'],'published',now(),'Lumaway',null,'Cara Membaca Ratecard Creator dalam Konteks Bisnis','article',array['ratecard creator','creator cost','campaign'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'promo-yang-sehat-untuk-saas','Merancang Promo SaaS yang Menarik Tanpa Merusak Harga','Prinsip membuat potongan kecil, kuota terbatas, dan bonus masa aktif yang tetap menjaga value produk.','<h2>Promo harus punya tujuan</h2><p>Bedakan promo acquisition, renewal, activation, dan loyalty. Satu kode untuk semua tujuan sering sulit dievaluasi.</p><h2>Batasi nilai dan penggunaan</h2><p>Lumaway membatasi monetary discount maksimal Rp12.000 pada campaign promo awal agar promosi tetap terasa tanpa menggeser positioning harga.</p><h2>Cegah double usage</h2><p>Reservation dan redemption perlu dibedakan. Promo tidak boleh habis hanya karena user membuka checkout, tetapi juga tidak boleh dipakai dua kali bersamaan.</p>','Campaign & Promotion','/insights/12-promo-yang-sehat-untuk-saas.svg','Merancang Promo SaaS yang Menarik Tanpa Merusak Harga','Prinsip membuat potongan kecil, kuota terbatas, dan bonus masa aktif yang tetap menjaga value produk.',array['promo saas','discount strategy','pricing'],'published',now(),'Lumaway',null,'Merancang Promo SaaS yang Menarik Tanpa Merusak Harga','article',array['promo saas','discount strategy','pricing'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'workflow-follow-up-creator','Follow Up Creator: Cara Mengurangi Aktivitas yang Terlupakan','Gunakan stage, notes, task, dan notification agar hubungan creator tidak berhenti di chat pribadi.','<h2>Tentukan next action</h2><p>Setiap listing aktif sebaiknya memiliki stage atau langkah berikutnya yang jelas.</p><h2>Simpan konteks di workspace</h2><p>Catatan singkat mengenai pembicaraan, sample, deadline, atau permintaan creator lebih berguna daripada mengandalkan ingatan tim.</p><h2>Gunakan reminder sebagai pengaman</h2><p>Listing yang terlalu lama tidak diperbarui dapat muncul di Data Health atau Notification Center untuk diperiksa kembali.</p>','Operations','/insights/13-workflow-follow-up-creator.svg','Follow Up Creator: Cara Mengurangi Aktivitas yang Terlupakan','Gunakan stage, notes, task, dan notification agar hubungan creator tidak berhenti di chat pribadi.',array['follow up creator','crm affiliate','workflow'],'published',now(),'Lumaway',null,'Follow Up Creator: Cara Mengurangi Aktivitas yang Terlupakan','article',array['follow up creator','crm affiliate','workflow'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'dashboard-untuk-owner','Dashboard Owner: Apa yang Perlu Dilihat dalam 2 Menit?','Ringkasan metrik dan warning yang membantu owner memahami situasi tanpa membuka seluruh tabel.','<h2>Mulai dari outcome</h2><p>GMV, order, qty, creator aktif, commission dan ROI memberi gambaran awal.</p><h2>Cari perubahan yang material</h2><p>Gunakan trend chart dan comparison period untuk menemukan area yang bergerak, bukan sekadar membaca seluruh angka.</p><h2>Buka detail hanya bila perlu</h2><p>Dashboard yang baik memberi jalur ke creator, product, campaign atau data health ketika ada pertanyaan lanjutan.</p>','Business & Growth','/insights/14-dashboard-untuk-owner.svg','Dashboard Owner: Apa yang Perlu Dilihat dalam 2 Menit?','Ringkasan metrik dan warning yang membantu owner memahami situasi tanpa membuka seluruh tabel.',array['executive dashboard','owner dashboard','business metrics'],'published',now(),'Lumaway',null,'Dashboard Owner: Apa yang Perlu Dilihat dalam 2 Menit?','article',array['executive dashboard','owner dashboard','business metrics'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'creator-economy-database-sebagai-aset','Creator Database Bisa Menjadi Aset Operasional Brand','Mengapa histori hubungan creator, produk, sample, dan campaign bernilai lebih dari daftar username.','<h2>Daftar kontak mudah dibuat, konteks sulit dibangun</h2><p>Nilai database muncul dari histori: kapan dihubungi, produk apa yang dikirim, campaign apa yang diikuti, dan outcome apa yang tercatat.</p><h2>Data membantu continuity tim</h2><p>Ketika anggota tim berubah, workspace yang rapi mengurangi kehilangan pengetahuan yang biasanya hanya tersimpan di chat pribadi.</p><h2>Kualitas lebih penting dari jumlah</h2><p>Ribuan creator tanpa identity dan history yang jelas tidak selalu lebih berguna daripada database yang lebih kecil tetapi terhubung.</p>','Lifestyle & Productivity','/insights/15-creator-economy-database-sebagai-aset.svg','Creator Database Bisa Menjadi Aset Operasional Brand','Mengapa histori hubungan creator, produk, sample, dan campaign bernilai lebih dari daftar username.',array['creator economy','creator database','marketing operations'],'published',now(),'Lumaway',null,'Creator Database Bisa Menjadi Aset Operasional Brand','article',array['creator economy','creator database','marketing operations'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'ai-analytics-tetap-butuh-validasi','AI Analytics Tetap Butuh Validasi Manusia','Cara menggunakan AI untuk membantu membaca data tanpa menyerahkan keputusan sepenuhnya pada model.','<h2>AI membantu menyusun pola dan pertanyaan</h2><p>Ringkasan otomatis dapat mempercepat proses membaca data yang besar dan menemukan area untuk diperiksa.</p><h2>Sumber data tetap menentukan kualitas</h2><p>Jika tanggal, mapping, identity atau HPP salah, output AI dapat ikut salah meskipun bahasanya terlihat meyakinkan.</p><h2>Pisahkan insight dan keputusan</h2><p>Gunakan AI sebagai bahan analisis. Keputusan campaign, budget, creator, dan produk tetap memerlukan konteks bisnis yang dimiliki tim.</p>','Data & Analytics','/insights/16-ai-analytics-tetap-butuh-validasi.svg','AI Analytics Tetap Butuh Validasi Manusia','Cara menggunakan AI untuk membantu membaca data tanpa menyerahkan keputusan sepenuhnya pada model.',array['ai analytics','business intelligence','human review'],'published',now(),'Lumaway',null,'AI Analytics Tetap Butuh Validasi Manusia','article',array['ai analytics','business intelligence','human review'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'cara-membuat-kanban-marketing','Kanban Marketing yang Tidak Cuma Jadi To-do List','Menyusun task marketing dengan title, description, priority, due date, dan status yang benar-benar membantu eksekusi.','<h2>Task harus punya outcome</h2><p>Judul seperti ''follow up creator A'' lebih jelas jika description menjelaskan apa yang perlu diselesaikan.</p><h2>Priority bukan dekorasi</h2><p>Gunakan Low, Normal, High, Urgent sesuai konsekuensi dan deadline, bukan berdasarkan siapa yang meminta paling keras.</p><h2>Review board secara berkala</h2><p>Kanban baru berguna jika status diperbarui dan task selesai benar-benar ditutup.</p>','Lifestyle & Productivity','/insights/17-cara-membuat-kanban-marketing.svg','Kanban Marketing yang Tidak Cuma Jadi To-do List','Menyusun task marketing dengan title, description, priority, due date, dan status yang benar-benar membantu eksekusi.',array['kanban marketing','task management','workflow'],'published',now(),'Lumaway',null,'Kanban Marketing yang Tidak Cuma Jadi To-do List','article',array['kanban marketing','task management','workflow'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'refund-dalam-analisis-ecommerce','Refund Harus Masuk ke Pembacaan Performa E-commerce','GMV dan order perlu dibaca bersama refunded GMV dan refunded items agar evaluasi lebih utuh.','<h2>Gross performance belum tentu net outcome</h2><p>GMV tinggi dapat terlihat positif, tetapi refund dapat mengubah interpretasi kualitas penjualan.</p><h2>Pisahkan metrik sumber</h2><p>Gunakan definisi yang diberikan marketplace dan jangan mencampur refunded item dengan cancelled order jika sumber membedakannya.</p><h2>Bandingkan produk dan creator</h2><p>Refund dapat ditelusuri sebagai pertanyaan lanjutan ke SKU, campaign, atau creator tertentu tanpa langsung menyimpulkan penyebab.</p>','Marketplace & E-commerce','/insights/18-refund-dalam-analisis-ecommerce.svg','Refund Harus Masuk ke Pembacaan Performa E-commerce','GMV dan order perlu dibaca bersama refunded GMV dan refunded items agar evaluasi lebih utuh.',array['refund gmv','ecommerce analytics','marketplace'],'published',now(),'Lumaway',null,'Refund Harus Masuk ke Pembacaan Performa E-commerce','article',array['refund gmv','ecommerce analytics','marketplace'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'social-profile-creator-di-listings','Social Profile Creator di Listings: Kenapa Perlu?','Cara menghubungkan Instagram, TikTok, Facebook, Lemon8, YouTube, Threads, dan X ke Master Creator.','<h2>Satu creator dapat aktif di banyak platform</h2><p>Link sosial membantu tim membuka profil yang benar tanpa mencari ulang username.</p><h2>Foto profil mempermudah scanning</h2><p>Lumaway mencoba membaca foto dari metadata publik. Jika platform membatasi akses, user tetap dapat menyimpan link dan menggunakan Avatar URL manual.</p><h2>Simpan di Master Creator</h2><p>Social profile berada pada identity creator sehingga dapat dipakai lintas listing dan workflow lain.</p>','Product Knowledge','/insights/19-social-profile-creator-di-listings.svg','Social Profile Creator di Listings: Kenapa Perlu?','Cara menghubungkan Instagram, TikTok, Facebook, Lemon8, YouTube, Threads, dan X ke Master Creator.',array['social profile creator','listings','affiliate crm'],'published',now(),'Lumaway',null,'Social Profile Creator di Listings: Kenapa Perlu?','article',array['social profile creator','listings','affiliate crm'],false,true,3,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
insert into public.luma_blog_posts(workspace_id,slug,title,excerpt,content_html,category,cover_image_url,seo_title,seo_description,seo_keywords,status,published_at,author_name,video_embed_url,image_alt,content_type,tags,is_featured,is_global,reading_minutes,faq_json)
values(null,'dari-upload-ke-keputusan','Dari Upload File sampai Keputusan: Alur Kerja Data yang Lebih Sehat','Sebuah workflow praktis: upload, validasi, analisis, keputusan, action, lalu review.','<h2>Upload bukan akhir pekerjaan</h2><p>Data perlu dipetakan, dipreview, dan diperiksa kesehatannya sebelum dipakai sebagai dasar diskusi.</p><h2>Analisis perlu pertanyaan</h2><p>Gunakan dashboard untuk menjawab pertanyaan tertentu, bukan untuk mencari makna dari semua angka sekaligus.</p><h2>Hubungkan insight ke action</h2><p>Campaign Tracker, Listings, Kanban, Sample dan Shipping memberi tempat agar keputusan dapat diteruskan menjadi aktivitas.</p><h2>Review membentuk pengetahuan</h2><p>Catat hasil setelah tindakan dilakukan. Dengan begitu, tim tidak hanya menyimpan data, tetapi membangun pembelajaran operasional.</p>','Business & Growth','/insights/20-dari-upload-ke-keputusan.svg','Dari Upload File sampai Keputusan: Alur Kerja Data yang L...','Sebuah workflow praktis: upload, validasi, analisis, keputusan, action, lalu review.',array['data workflow','business decision','lumaway'],'published',now(),'Lumaway',null,'Dari Upload File sampai Keputusan: Alur Kerja Data yang Lebih Sehat','article',array['data workflow','business decision','lumaway'],false,true,4,'[]'::jsonb)
on conflict(slug) do update set title=excluded.title,excerpt=excluded.excerpt,content_html=excluded.content_html,category=excluded.category,cover_image_url=excluded.cover_image_url,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,status='published',published_at=coalesce(public.luma_blog_posts.published_at,now()),author_name='Lumaway',content_type='article',tags=excluded.tags,is_global=true,reading_minutes=excluded.reading_minutes,updated_at=now();
