-- PR35: global payment orchestration for Mayar.id, Xendit, and Midtrans.

create table if not exists public.luma_payment_routing (
  id smallint primary key default 1 check (id=1),
  mode text not null default 'priority_fallback' check (mode in ('priority_fallback','weighted')),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.luma_payment_routing(id,mode) values(1,'priority_fallback')
on conflict(id) do nothing;

create table if not exists public.luma_payment_provider_settings (
  provider text primary key check (provider in ('mayar','xendit','midtrans')),
  enabled boolean not null default true,
  priority integer not null default 100 check (priority between 1 and 999),
  weight integer not null default 1 check (weight between 1 and 100),
  health_status text not null default 'unknown' check (health_status in ('unknown','healthy','degraded','error')),
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.luma_payment_provider_settings(provider,enabled,priority,weight) values
 ('mayar',true,10,10),
 ('xendit',true,20,3),
 ('midtrans',true,30,2)
on conflict(provider) do nothing;

create table if not exists public.luma_payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_key text not null,
  order_code text,
  status text,
  payload jsonb,
  created_at timestamptz not null default now(),
  constraint uq_luma_payment_webhook_event unique(provider,event_key)
);
create index if not exists idx_luma_payment_webhook_order on public.luma_payment_webhook_events(order_code);

alter table public.luma_payment_routing enable row level security;
alter table public.luma_payment_provider_settings enable row level security;
alter table public.luma_payment_webhook_events enable row level security;

revoke all on public.luma_payment_routing from anon,authenticated;
revoke all on public.luma_payment_provider_settings from anon,authenticated;
revoke all on public.luma_payment_webhook_events from anon,authenticated;

create or replace function public.luma_payment_provider_health(
  p_provider text,
  p_ok boolean,
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
begin
  update public.luma_payment_provider_settings
  set health_status=case when p_ok then 'healthy' else 'error' end,
      last_success_at=case when p_ok then now() else last_success_at end,
      last_error_at=case when p_ok then last_error_at else now() end,
      last_error=case when p_ok then null else left(coalesce(p_error,'unknown'),500) end,
      updated_at=now()
  where provider=lower(p_provider);
end
$function$;

revoke all on function public.luma_payment_provider_health(text,boolean,text) from public,anon,authenticated;
grant execute on function public.luma_payment_provider_health(text,boolean,text) to service_role;
