-- PR32: canonical SKU master, per-platform product codes, and up to 15 variants.

alter table public.sales
  add column if not exists product_code text,
  add column if not exists variant_name text;

alter table public.product_hpp_history
  add column if not exists product_master_id bigint references public.product_master(id) on delete set null;

-- Previous unique key was global (sku, period) and could collide across workspaces.
alter table public.product_hpp_history
  drop constraint if exists product_hpp_history_sku_period_key;

create unique index if not exists uq_product_hpp_workspace_sku_period
  on public.product_hpp_history(workspace_id, lower(sku), period)
  where workspace_id is not null and sku is not null;

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  product_master_id bigint not null references public.product_master(id) on delete cascade,
  sku text not null,
  slot smallint not null check (slot between 1 and 15),
  variant_name text not null,
  hpp numeric,
  selling_price numeric,
  source_import_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_product_variants_workspace_product_slot unique (workspace_id, product_master_id, slot)
);

create index if not exists idx_product_variants_workspace_sku
  on public.product_variants(workspace_id, lower(sku));

create table if not exists public.product_platform_items (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  product_master_id bigint not null references public.product_master(id) on delete cascade,
  sku text not null,
  platform text not null,
  product_code text not null,
  product_name text,
  variant_slot smallint check (variant_slot is null or variant_slot between 1 and 15),
  variant_name text,
  source_import_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_product_platform_items_workspace_platform_code unique (workspace_id, platform, product_code)
);

create index if not exists idx_product_platform_items_workspace_sku
  on public.product_platform_items(workspace_id, lower(sku));
create index if not exists idx_product_platform_items_master
  on public.product_platform_items(product_master_id);
create index if not exists idx_product_platform_items_platform
  on public.product_platform_items(workspace_id, platform);

alter table public.product_variants enable row level security;
alter table public.product_platform_items enable row level security;

drop policy if exists product_variants_select on public.product_variants;
drop policy if exists product_variants_insert on public.product_variants;
drop policy if exists product_variants_update on public.product_variants;
drop policy if exists product_variants_delete on public.product_variants;
create policy product_variants_select on public.product_variants
for select using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_variants.workspace_id and wm.user_id=auth.uid())
);
create policy product_variants_insert on public.product_variants
for insert with check (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_variants.workspace_id and wm.user_id=auth.uid())
);
create policy product_variants_update on public.product_variants
for update using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_variants.workspace_id and wm.user_id=auth.uid())
) with check (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_variants.workspace_id and wm.user_id=auth.uid())
);
create policy product_variants_delete on public.product_variants
for delete using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_variants.workspace_id and wm.user_id=auth.uid())
);

drop policy if exists product_platform_items_select on public.product_platform_items;
drop policy if exists product_platform_items_insert on public.product_platform_items;
drop policy if exists product_platform_items_update on public.product_platform_items;
drop policy if exists product_platform_items_delete on public.product_platform_items;
create policy product_platform_items_select on public.product_platform_items
for select using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_platform_items.workspace_id and wm.user_id=auth.uid())
);
create policy product_platform_items_insert on public.product_platform_items
for insert with check (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_platform_items.workspace_id and wm.user_id=auth.uid())
);
create policy product_platform_items_update on public.product_platform_items
for update using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_platform_items.workspace_id and wm.user_id=auth.uid())
) with check (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_platform_items.workspace_id and wm.user_id=auth.uid())
);
create policy product_platform_items_delete on public.product_platform_items
for delete using (
  public.luma_is_admin()
  or exists(select 1 from public.workspace_members wm where wm.workspace_id=product_platform_items.workspace_id and wm.user_id=auth.uid())
);

revoke all on public.product_variants from anon;
revoke all on public.product_platform_items from anon;
grant select,insert,update,delete on public.product_variants to authenticated;
grant select,insert,update,delete on public.product_platform_items to authenticated;
grant usage,select on sequence public.product_variants_id_seq to authenticated;
grant usage,select on sequence public.product_platform_items_id_seq to authenticated;
