-- PR38: payment checkout idempotency + Lumaway Social v2.

create table if not exists public.luma_payment_checkout_intents (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('token','subscription')),
  target_key text not null,
  promo_code text not null default '',
  amount numeric not null default 0 check (amount >= 0),
  idempotency_key text not null unique,
  order_code text not null unique,
  status text not null default 'processing' check (status in ('processing','ready','failed','paid','expired')),
  provider text,
  payment_url text,
  payment_session_id text,
  payment_reference text,
  expires_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_payment_intents_lookup
  on public.luma_payment_checkout_intents(workspace_id,user_id,kind,target_key,created_at desc);

alter table public.luma_payment_checkout_intents enable row level security;
revoke all on public.luma_payment_checkout_intents from anon,authenticated;

alter table public.luma_topup_orders
  add column if not exists checkout_intent_id bigint references public.luma_payment_checkout_intents(id) on delete set null;

alter table public.luma_subscription_orders
  add column if not exists checkout_intent_id bigint references public.luma_payment_checkout_intents(id) on delete set null;

alter table public.profiles
  add column if not exists social_avatar_url text;

create unique index if not exists uq_profiles_social_alias_lower
  on public.profiles(lower(social_alias))
  where nullif(trim(social_alias),'') is not null;

alter table public.luma_community_posts
  add column if not exists image_urls jsonb not null default '[]'::jsonb,
  add column if not exists image_storage_paths jsonb not null default '[]'::jsonb;

update public.luma_community_posts
set image_urls=jsonb_build_array(image_url),
    image_storage_paths=case when image_storage_path is not null then jsonb_build_array(image_storage_path) else '[]'::jsonb end
where image_url is not null
  and coalesce(jsonb_array_length(image_urls),0)=0;

create table if not exists public.luma_community_saves (
  post_id bigint not null references public.luma_community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(post_id,user_id)
);

alter table public.luma_community_saves enable row level security;
drop policy if exists luma_community_saves_read on public.luma_community_saves;
drop policy if exists luma_community_saves_self on public.luma_community_saves;

create policy luma_community_saves_read on public.luma_community_saves
for select using (user_id=auth.uid() or public.luma_is_admin());

create policy luma_community_saves_self on public.luma_community_saves
for all using (user_id=auth.uid()) with check (user_id=auth.uid());

grant select,insert,delete on public.luma_community_saves to authenticated;

create or replace function public.luma_get_my_social_identity_v2()
returns table(
  social_alias text,
  social_avatar_key text,
  social_avatar_url text
)
language sql
security definer
set search_path to 'public','pg_temp'
as $function$
  select
    coalesce(nullif(trim(p.social_alias),''),'LumaUser'),
    coalesce(nullif(trim(p.social_avatar_key),''),'dino-emerald-happy'),
    p.social_avatar_url
  from public.profiles p
  where p.id=auth.uid();
$function$;

revoke all on function public.luma_get_my_social_identity_v2() from public,anon;
grant execute on function public.luma_get_my_social_identity_v2() to authenticated;

create or replace function public.luma_update_social_identity(
  p_alias text,
  p_avatar_url text default null
)
returns table(
  social_alias text,
  social_avatar_url text
)
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_alias text := trim(coalesce(p_alias,''));
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  if char_length(v_alias)<3 or char_length(v_alias)>30 then
    raise exception 'Nama community harus 3-30 karakter.';
  end if;
  if v_alias !~ '^[[:alnum:]_. -]+$' then
    raise exception 'Nama community hanya boleh berisi huruf, angka, spasi, titik, underscore, atau tanda minus.';
  end if;
  if not public.luma_social_text_allowed(v_alias) then
    raise exception 'Nama community tidak boleh berisi kontak atau link.';
  end if;
  if exists(select 1 from public.profiles p where lower(p.social_alias)=lower(v_alias) and p.id<>auth.uid()) then
    raise exception 'Nama community sudah digunakan.';
  end if;

  update public.profiles
  set social_alias=v_alias,
      social_avatar_url=coalesce(nullif(trim(p_avatar_url),''),social_avatar_url),
      updated_at=now()
  where id=auth.uid();

  return query
  select p.social_alias,p.social_avatar_url from public.profiles p where p.id=auth.uid();
end
$function$;

revoke all on function public.luma_update_social_identity(text,text) from public,anon;
grant execute on function public.luma_update_social_identity(text,text) to authenticated;

create or replace function public.luma_get_social_feed_v2(
  p_limit integer default 30,
  p_offset integer default 0,
  p_scope text default 'for_you'
)
returns table(
  id bigint,
  user_id uuid,
  body text,
  image_url text,
  image_urls jsonb,
  created_at timestamptz,
  social_alias text,
  social_avatar_key text,
  social_avatar_url text,
  like_count bigint,
  save_count bigint,
  liked_by_me boolean,
  saved_by_me boolean,
  subscribed_by_me boolean,
  subscriber_count bigint
)
language sql
security definer
set search_path to 'public','pg_temp'
as $function$
  select
    p.id,
    p.user_id,
    p.body,
    p.image_url,
    case
      when jsonb_typeof(p.image_urls)='array' and jsonb_array_length(p.image_urls)>0 then p.image_urls
      when p.image_url is not null then jsonb_build_array(p.image_url)
      else '[]'::jsonb
    end,
    p.created_at,
    coalesce(nullif(trim(pr.social_alias),''),'LumaUser'),
    coalesce(nullif(trim(pr.social_avatar_key),''),'dino-emerald-happy'),
    pr.social_avatar_url,
    (select count(*) from public.luma_community_likes l where l.post_id=p.id),
    (select count(*) from public.luma_community_saves sv where sv.post_id=p.id),
    exists(select 1 from public.luma_community_likes l where l.post_id=p.id and l.user_id=auth.uid()),
    exists(select 1 from public.luma_community_saves sv where sv.post_id=p.id and sv.user_id=auth.uid()),
    exists(select 1 from public.luma_community_subscriptions s where s.user_id=auth.uid() and s.subscribed_user_id=p.user_id),
    (select count(*) from public.luma_community_subscriptions s where s.subscribed_user_id=p.user_id)
  from public.luma_community_posts p
  join public.profiles pr on pr.id=p.user_id
  where p.status='published'
    and (
      lower(coalesce(p_scope,'for_you'))<>'following'
      or p.user_id=auth.uid()
      or exists(
        select 1 from public.luma_community_subscriptions s
        where s.user_id=auth.uid() and s.subscribed_user_id=p.user_id
      )
    )
  order by p.created_at desc
  limit greatest(1,least(coalesce(p_limit,30),100))
  offset greatest(coalesce(p_offset,0),0);
$function$;

revoke all on function public.luma_get_social_feed_v2(integer,integer,text) from public,anon;
grant execute on function public.luma_get_social_feed_v2(integer,integer,text) to authenticated;
