-- PR76B: Data Health Center + reusable import mapping presets

create table if not exists public.import_mapping_presets (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  data_type text not null,
  platform text not null default 'Other',
  signature text not null,
  name text not null default 'Mapping otomatis',
  mapping jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id,data_type,platform,signature)
);

create index if not exists idx_import_mapping_presets_workspace
  on public.import_mapping_presets(workspace_id,data_type,platform,updated_at desc);

alter table public.import_mapping_presets enable row level security;

drop policy if exists import_mapping_presets_select on public.import_mapping_presets;
create policy import_mapping_presets_select
on public.import_mapping_presets
for select
to authenticated
using (public.luma_has_workspace(workspace_id));

drop policy if exists import_mapping_presets_insert on public.import_mapping_presets;
create policy import_mapping_presets_insert
on public.import_mapping_presets
for insert
to authenticated
with check (
  public.luma_has_workspace(workspace_id)
  and user_id=auth.uid()
);

drop policy if exists import_mapping_presets_update on public.import_mapping_presets;
create policy import_mapping_presets_update
on public.import_mapping_presets
for update
to authenticated
using (public.luma_has_workspace(workspace_id))
with check (public.luma_has_workspace(workspace_id));

drop policy if exists import_mapping_presets_delete on public.import_mapping_presets;
create policy import_mapping_presets_delete
on public.import_mapping_presets
for delete
to authenticated
using (public.luma_has_workspace(workspace_id));

create or replace function public.luma_data_health_v1(p_workspace_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_creator_total bigint:=0;
  v_creator_missing_identity bigint:=0;
  v_creator_duplicates bigint:=0;
  v_product_total bigint:=0;
  v_product_missing_name bigint:=0;
  v_product_missing_hpp bigint:=0;
  v_product_missing_image bigint:=0;
  v_performance_total bigint:=0;
  v_performance_missing_creator bigint:=0;
  v_performance_zero_metric bigint:=0;
  v_product_performance_total bigint:=0;
  v_product_performance_unmapped bigint:=0;
  v_failed_imports bigint:=0;
  v_zero_row_imports bigint:=0;
  v_stale_listings bigint:=0;
  v_unlinked_samples bigint:=0;
  v_shipping_missing_tracking bigint:=0;
  v_latest_import timestamptz;
  v_recent_imports jsonb:='[]'::jsonb;
  v_issues jsonb:='[]'::jsonb;
  v_critical integer:=0;
  v_warning integer:=0;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  if not public.luma_has_workspace(p_workspace_id) then
    raise exception 'Workspace access denied' using errcode='42501';
  end if;

  select count(*) into v_creator_total
  from public.creators where workspace_id=p_workspace_id;

  select count(*) into v_creator_missing_identity
  from public.creators
  where workspace_id=p_workspace_id
    and nullif(trim(coalesce(name,'')),'') is null
    and nullif(trim(coalesce(username,'')),'') is null
    and nullif(trim(coalesce(affiliate_id,'')),'') is null;

  select coalesce(sum(x.cnt-1),0)::bigint into v_creator_duplicates
  from (
    select count(*)::bigint as cnt
    from public.creators
    where workspace_id=p_workspace_id
      and nullif(trim(coalesce(identity_key,'')),'') is not null
    group by lower(trim(identity_key))
    having count(*)>1
  ) x;

  select count(*) into v_product_total
  from public.product_master where workspace_id=p_workspace_id;

  select count(*) into v_product_missing_name
  from public.product_master
  where workspace_id=p_workspace_id
    and nullif(trim(coalesce(product_name,'')),'') is null;

  select count(*) into v_product_missing_hpp
  from public.product_master
  where workspace_id=p_workspace_id
    and coalesce(cost_price,0)<=0;

  select count(*) into v_product_missing_image
  from public.product_master
  where workspace_id=p_workspace_id
    and nullif(trim(coalesce(image_url,'')),'') is null;

  select count(*) into v_performance_total
  from public.sales
  where workspace_id=p_workspace_id and data_type='performance';

  select count(*) into v_performance_missing_creator
  from public.sales
  where workspace_id=p_workspace_id and data_type='performance'
    and creator_id is null;

  select count(*) into v_performance_zero_metric
  from public.sales
  where workspace_id=p_workspace_id and data_type='performance'
    and coalesce(qty,0)=0
    and coalesce(orders,0)=0
    and coalesce(gmv,0)=0
    and coalesce(commission,0)=0;

  select count(*) into v_product_performance_total
  from public.sales
  where workspace_id=p_workspace_id and data_type='product_performance';

  select count(*) into v_product_performance_unmapped
  from public.sales
  where workspace_id=p_workspace_id and data_type='product_performance'
    and (
      nullif(trim(coalesce(product_code,'')),'') is null
      or nullif(trim(coalesce(sku,'')),'') is null
    );

  select count(*) into v_failed_imports
  from public.imports
  where workspace_id=p_workspace_id
    and (
      lower(coalesce(status,'')) in ('failed','error')
      or (lower(coalesce(status,''))='processing' and imported_at<now()-interval '30 minutes')
    );

  select count(*) into v_zero_row_imports
  from public.imports
  where workspace_id=p_workspace_id
    and lower(coalesce(status,''))='success'
    and coalesce(rows_imported,0)=0;

  select max(imported_at) into v_latest_import
  from public.imports
  where workspace_id=p_workspace_id
    and lower(coalesce(status,''))='success';

  select count(*) into v_stale_listings
  from public.listings
  where workspace_id=p_workspace_id
    and coalesce(stage,'') in ('Reach Out','Follow Up','Negotiation','Sample Sent','Content In Progress')
    and coalesce(updated_at,created_at,now())<now()-interval '48 hours';

  select count(*) into v_unlinked_samples
  from public.creator_samples
  where workspace_id=p_workspace_id
    and (creator_id is null or product_master_id is null);

  select count(*) into v_shipping_missing_tracking
  from public.shipping
  where workspace_id=p_workspace_id
    and lower(coalesce(status,'')) not in ('pending','draft','cancelled','canceled')
    and nullif(trim(coalesce(tracking,'')),'') is null;

  select coalesce(jsonb_agg(to_jsonb(t) order by t.imported_at desc),'[]'::jsonb)
  into v_recent_imports
  from (
    select import_id,filename,data_type,platform,rows_imported,status,imported_at,message
    from public.imports
    where workspace_id=p_workspace_id
    order by imported_at desc
    limit 8
  ) t;

  if v_failed_imports>0 then
    v_critical:=v_critical+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','failed_imports','severity','critical','count',v_failed_imports,
      'title','Import gagal atau tertahan',
      'description','Ada import berstatus gagal/error atau masih Processing lebih dari 30 menit.',
      'section','database','action_label','Buka Import History'
    ));
  end if;

  if v_performance_missing_creator>0 then
    v_critical:=v_critical+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','performance_missing_creator','severity','critical','count',v_performance_missing_creator,
      'title','Performance belum terhubung ke creator',
      'description','Row Affiliate Performance tanpa creator_id dapat membuat Ranking Creator dan Customer 360 tidak lengkap.',
      'section','upload','action_label','Periksa Mapping Upload'
    ));
  end if;

  if v_product_performance_unmapped>0 then
    v_critical:=v_critical+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','product_performance_unmapped','severity','critical','count',v_product_performance_unmapped,
      'title','Product Performance belum terpetakan',
      'description','Ada row Product Performance tanpa Product Code atau SKU induk.',
      'section','product-master','action_label','Buka Product Master'
    ));
  end if;

  if v_creator_duplicates>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','creator_duplicates','severity','warning','count',v_creator_duplicates,
      'title','Creator terindikasi duplikat',
      'description','Identity key creator yang sama ditemukan lebih dari satu kali di workspace.',
      'section','listings','action_label','Buka Master Creator'
    ));
  end if;

  if v_product_missing_hpp>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','product_missing_hpp','severity','warning','count',v_product_missing_hpp,
      'title','Produk belum memiliki HPP',
      'description','HPP nol/kosong dapat membuat margin, ROI, dan guardrail tidak akurat.',
      'section','product-master','action_label','Lengkapi HPP'
    ));
  end if;

  if v_performance_zero_metric>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','performance_zero_metric','severity','warning','count',v_performance_zero_metric,
      'title','Row performance seluruh metrik nol',
      'description','Qty, Orders, GMV, dan Commission seluruhnya nol. Ini bisa valid, tetapi perlu dicek jika jumlahnya besar.',
      'section','database','action_label','Periksa Database'
    ));
  end if;

  if v_zero_row_imports>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','zero_row_imports','severity','warning','count',v_zero_row_imports,
      'title','Import sukses tanpa row tersimpan',
      'description','File tercatat sukses tetapi rows_imported = 0.',
      'section','database','action_label','Buka Import History'
    ));
  end if;

  if v_unlinked_samples>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','unlinked_samples','severity','warning','count',v_unlinked_samples,
      'title','Creator Samples belum terhubung penuh',
      'description','Sample belum terhubung ke creator atau Product Master.',
      'section','creator-samples','action_label','Buka Creator Samples'
    ));
  end if;

  if v_shipping_missing_tracking>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','shipping_missing_tracking','severity','warning','count',v_shipping_missing_tracking,
      'title','Pengiriman aktif tanpa nomor resi',
      'description','Status pengiriman sudah berjalan tetapi nomor tracking belum terisi.',
      'section','shipping','action_label','Lengkapi Shipping'
    ));
  end if;

  if v_stale_listings>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','stale_listings','severity','warning','count',v_stale_listings,
      'title','Listing perlu follow up',
      'description','Listing aktif tidak diperbarui lebih dari 48 jam.',
      'section','listings','action_label','Buka Listings'
    ));
  end if;

  if v_product_missing_name>0 then
    v_warning:=v_warning+1;
    v_issues:=v_issues||jsonb_build_array(jsonb_build_object(
      'key','product_missing_name','severity','warning','count',v_product_missing_name,
      'title','Nama produk belum lengkap',
      'description','Sebagian SKU belum memiliki nama produk.',
      'section','product-master','action_label','Lengkapi Produk'
    ));
  end if;

  return jsonb_build_object(
    'status',case when v_critical>0 then 'critical' when v_warning>0 then 'attention' else 'healthy' end,
    'critical_categories',v_critical,
    'warning_categories',v_warning,
    'latest_successful_import_at',v_latest_import,
    'summary',jsonb_build_object(
      'creators',v_creator_total,
      'products',v_product_total,
      'affiliate_rows',v_performance_total,
      'product_rows',v_product_performance_total
    ),
    'metrics',jsonb_build_object(
      'creator_missing_identity',v_creator_missing_identity,
      'creator_duplicates',v_creator_duplicates,
      'product_missing_name',v_product_missing_name,
      'product_missing_hpp',v_product_missing_hpp,
      'product_missing_image',v_product_missing_image,
      'performance_missing_creator',v_performance_missing_creator,
      'performance_zero_metric',v_performance_zero_metric,
      'product_performance_unmapped',v_product_performance_unmapped,
      'failed_imports',v_failed_imports,
      'zero_row_imports',v_zero_row_imports,
      'stale_listings',v_stale_listings,
      'unlinked_samples',v_unlinked_samples,
      'shipping_missing_tracking',v_shipping_missing_tracking
    ),
    'issues',v_issues,
    'recent_imports',v_recent_imports
  );
end
$$;

revoke all on function public.luma_data_health_v1(uuid) from public;
revoke all on function public.luma_data_health_v1(uuid) from anon;
grant execute on function public.luma_data_health_v1(uuid) to authenticated;
