-- PR46 Billing, Subscription, Multi-Store, Social Profile & Account foundation
-- 2026-09-25
-- This migration keeps user-facing access rules intact while adding admin-only
-- controls and store-scoped analytics.

-- ---------------------------------------------------------------------------
-- 1. Global subscription plan: 12 months
-- ---------------------------------------------------------------------------
insert into public.luma_subscription_plans(
  code,name,duration_days,price,bonus_tokens,priority_level,
  all_access,is_trial,status,sort_order,updated_at
)
values(
  'annual_510','12 Months',365,510000,2000,'high',
  true,false,'active',4,now()
)
on conflict(code) do update set
  name=excluded.name,
  duration_days=excluded.duration_days,
  price=excluded.price,
  bonus_tokens=excluded.bonus_tokens,
  priority_level=excluded.priority_level,
  all_access=excluded.all_access,
  is_trial=false,
  status='active',
  sort_order=4,
  updated_at=now();

-- ---------------------------------------------------------------------------
-- 2. Verified owner revenue
-- Fixes admin visibility for paid top-up orders and provides one canonical RPC.
-- ---------------------------------------------------------------------------
alter policy luma_topup_select
on public.luma_topup_orders
using (
  public.luma_is_admin()
  or (
    public.luma_has_workspace(workspace_id)
    and user_id=(select auth.uid())
  )
);

create or replace function public.luma_owner_verified_revenue(p_year integer)
returns table(
  month_number integer,
  subscription_revenue numeric,
  token_revenue numeric,
  total_revenue numeric
)
language plpgsql
security invoker
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is null or not public.luma_is_admin() then
    raise exception 'Owner access required' using errcode='42501';
  end if;
  if p_year < 2020 or p_year > 2100 then
    raise exception 'Invalid year' using errcode='22023';
  end if;

  return query
  with months as (
    select generate_series(1,12)::integer month_number
  ),
  subscription_paid as (
    select extract(month from paid_at)::integer month_number,
           coalesce(sum(amount),0)::numeric revenue
    from public.luma_subscription_orders
    where status='paid'
      and paid_at >= make_date(p_year,1,1)
      and paid_at < make_date(p_year+1,1,1)
    group by 1
  ),
  token_paid as (
    select extract(month from paid_at)::integer month_number,
           coalesce(sum(amount),0)::numeric revenue
    from public.luma_topup_orders
    where status='paid'
      and paid_at >= make_date(p_year,1,1)
      and paid_at < make_date(p_year+1,1,1)
    group by 1
  )
  select m.month_number,
         coalesce(s.revenue,0)::numeric,
         coalesce(t.revenue,0)::numeric,
         (coalesce(s.revenue,0)+coalesce(t.revenue,0))::numeric
  from months m
  left join subscription_paid s using(month_number)
  left join token_paid t using(month_number)
  order by m.month_number;
end
$$;

revoke all on function public.luma_owner_verified_revenue(integer) from public,anon;
grant execute on function public.luma_owner_verified_revenue(integer) to authenticated,service_role;

-- ---------------------------------------------------------------------------
-- 3. Admin-only flexible subscription extension with audit trail.
-- No notification is generated to the user.
-- ---------------------------------------------------------------------------
create table if not exists public.luma_subscription_adjustments(
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references public.luma_user_subscriptions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete set null,
  days_added integer not null check(days_added between 1 and 3650),
  reason text,
  previous_ends_at timestamptz not null,
  new_ends_at timestamptz not null,
  adjusted_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);
create index if not exists idx_luma_subscription_adjustments_user
  on public.luma_subscription_adjustments(user_id,created_at desc);
create index if not exists idx_luma_subscription_adjustments_subscription
  on public.luma_subscription_adjustments(subscription_id,created_at desc);

alter table public.luma_subscription_adjustments enable row level security;

drop policy if exists pr46_subscription_adjustments_admin_select on public.luma_subscription_adjustments;
create policy pr46_subscription_adjustments_admin_select
on public.luma_subscription_adjustments
for select to authenticated
using ((select public.luma_is_admin()));

drop policy if exists pr46_subscription_adjustments_admin_insert on public.luma_subscription_adjustments;
create policy pr46_subscription_adjustments_admin_insert
on public.luma_subscription_adjustments
for insert to authenticated
with check ((select public.luma_is_admin()) and adjusted_by=(select auth.uid()));

drop policy if exists pr46_user_subscriptions_admin_update on public.luma_user_subscriptions;
create policy pr46_user_subscriptions_admin_update
on public.luma_user_subscriptions
for update to authenticated
using ((select public.luma_is_admin()))
with check ((select public.luma_is_admin()));

create or replace function public.luma_admin_extend_subscription(
  p_subscription_id bigint,
  p_days integer,
  p_reason text default null
)
returns table(subscription_id bigint,user_id uuid,previous_ends_at timestamptz,new_ends_at timestamptz,status text)
language plpgsql
security invoker
set search_path=public,pg_temp
as $$
declare
  v_sub public.luma_user_subscriptions%rowtype;
  v_previous timestamptz;
  v_new timestamptz;
  v_status text;
begin
  if auth.uid() is null or not public.luma_is_admin() then
    raise exception 'Owner access required' using errcode='42501';
  end if;
  if p_days is null or p_days < 1 or p_days > 3650 then
    raise exception 'Days must be between 1 and 3650' using errcode='22023';
  end if;

  select * into v_sub
  from public.luma_user_subscriptions
  where id=p_subscription_id
  for update;

  if v_sub.id is null then
    raise exception 'Subscription not found' using errcode='P0002';
  end if;

  v_previous:=v_sub.ends_at;
  v_new:=greatest(v_sub.ends_at,now()) + make_interval(days=>p_days);
  v_status:=case when v_sub.status='trialing' then 'trialing' else 'active' end;

  update public.luma_user_subscriptions
  set ends_at=v_new,status=v_status,updated_at=now()
  where id=v_sub.id;

  insert into public.luma_subscription_adjustments(
    subscription_id,user_id,workspace_id,days_added,reason,
    previous_ends_at,new_ends_at,adjusted_by
  ) values(
    v_sub.id,v_sub.user_id,v_sub.workspace_id,p_days,nullif(trim(coalesce(p_reason,'')),''),
    v_previous,v_new,auth.uid()
  );

  return query select v_sub.id,v_sub.user_id,v_previous,v_new,v_status;
end
$$;

revoke all on function public.luma_admin_extend_subscription(bigint,integer,text) from public,anon;
grant execute on function public.luma_admin_extend_subscription(bigint,integer,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Community Profile: controlled RPC bypass for the self-edit lock trigger.
-- Direct profile updates remain locked.
-- ---------------------------------------------------------------------------
create or replace function public.luma_lock_social_identity()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is not null
     and auth.uid()=old.id
     and coalesce(current_setting('app.luma_social_identity_rpc',true),'0')<>'1' then
    new.social_alias:=old.social_alias;
    new.social_avatar_key:=old.social_avatar_key;
    new.social_avatar_url:=old.social_avatar_url;
  end if;
  return new;
end
$$;

create or replace function public.luma_update_social_identity(
  p_alias text,
  p_avatar_url text default null
)
returns table(social_alias text,social_avatar_url text)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_alias text:=trim(coalesce(p_alias,''));
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  if char_length(v_alias)<3 or char_length(v_alias)>30 then
    raise exception 'Nama community harus 3-30 karakter.';
  end if;
  if v_alias !~ '^[[:alnum:]_. -]+$' then
    raise exception 'Nama community hanya boleh berisi huruf, angka, spasi, titik, underscore, atau tanda minus.';
  end if;
  if not public.luma_social_text_allowed(v_alias) then
    raise exception 'Nama community tidak boleh berisi kontak atau link.';
  end if;
  if exists(
    select 1 from public.profiles p
    where lower(p.social_alias)=lower(v_alias) and p.id<>auth.uid()
  ) then
    raise exception 'Nama community sudah digunakan.';
  end if;

  perform set_config('app.luma_social_identity_rpc','1',true);

  update public.profiles
  set social_alias=v_alias,
      social_avatar_url=coalesce(nullif(trim(p_avatar_url),''),social_avatar_url),
      updated_at=now()
  where id=auth.uid();

  return query
  select p.social_alias,p.social_avatar_url
  from public.profiles p
  where p.id=auth.uid();
end
$$;

-- ---------------------------------------------------------------------------
-- 5. Email/password readiness + weekly email preference.
-- Supabase supports updateUser({password}) for an existing OAuth account.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists password_configured_at timestamptz,
  add column if not exists weekly_email_enabled boolean not null default true,
  add column if not exists weekly_email_opt_out_at timestamptz;

update public.profiles p
set password_configured_at=coalesce(p.password_configured_at,now())
from auth.users u
where u.id=p.id
  and u.encrypted_password is not null
  and length(u.encrypted_password)>0
  and p.password_configured_at is null;

create or replace function public.luma_sync_password_configured_at()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  update public.profiles
  set password_configured_at=
        case
          when new.encrypted_password is not null and length(new.encrypted_password)>0
            then coalesce(password_configured_at,now())
          else null
        end,
      updated_at=now()
  where id=new.id;
  return new;
end
$$;

revoke all on function public.luma_sync_password_configured_at() from public,anon,authenticated;

drop trigger if exists zz_luma_password_state_insert on auth.users;
create trigger zz_luma_password_state_insert
after insert on auth.users
for each row execute function public.luma_sync_password_configured_at();

drop trigger if exists zz_luma_password_state_update on auth.users;
create trigger zz_luma_password_state_update
after update of encrypted_password on auth.users
for each row
when (old.encrypted_password is distinct from new.encrypted_password)
execute function public.luma_sync_password_configured_at();

create table if not exists public.luma_weekly_email_deliveries(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  week_start date not null,
  status text not null check(status in ('sending','sent','skipped','error')),
  provider text not null default 'resend',
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,workspace_id,week_start)
);
alter table public.luma_weekly_email_deliveries enable row level security;
drop policy if exists pr46_weekly_email_admin_select on public.luma_weekly_email_deliveries;
create policy pr46_weekly_email_admin_select
on public.luma_weekly_email_deliveries
for select to authenticated
using ((select public.luma_is_admin()));
create index if not exists idx_luma_weekly_email_workspace_week
  on public.luma_weekly_email_deliveries(workspace_id,week_start desc);

-- ---------------------------------------------------------------------------
-- 6. Multi-store import metadata.
-- ---------------------------------------------------------------------------
alter table public.imports
  add column if not exists store_name text,
  add column if not exists store_id text;
create index if not exists idx_imports_workspace_store
  on public.imports(workspace_id,store_name,platform,imported_at desc);

-- Store-scoped Ads Support, while preserving all existing rows as ALL.
alter table public.affiliate_ads_support
  add column if not exists store_name text not null default 'ALL';

alter table public.affiliate_ads_support
  drop constraint if exists affiliate_ads_support_period_unique;

alter table public.affiliate_ads_support
  add constraint affiliate_ads_support_period_store_unique
  unique(workspace_id,start_date,end_date,platform,store_name);

-- ---------------------------------------------------------------------------
-- 7. Store-aware dashboard RPCs.
-- ---------------------------------------------------------------------------
create or replace function public.get_dashboard_latest_date_v2(
  p_workspace_id uuid,
  p_platform text default null,
  p_store_name text default null
)
returns date
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_date date;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  select max(s.data_date) into v_date
  from public.sales s
  where s.workspace_id=p_workspace_id
    and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
    and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name));
  return v_date;
end
$$;

create or replace function public.get_dashboard_store_options(
  p_workspace_id uuid,
  p_platform text default null
)
returns table(store_name text,store_id text,platform text,row_count bigint)
language sql
security invoker
set search_path=public,pg_temp
as $$
  select s.store_name,max(s.store_id),max(s.platform),count(*)::bigint
  from public.sales s
  where s.workspace_id=p_workspace_id
    and nullif(trim(s.store_name),'') is not null
    and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
  group by s.store_name
  order by lower(s.store_name);
$$;

create or replace function public.get_dashboard_metrics_v5(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null,
  p_store_name text default null
)
returns table(
  total_creators bigint,total_sales_records bigint,total_qty numeric,total_orders numeric,total_gmv numeric,
  total_commission numeric,total_products bigint,total_cost_product numeric,total_shipping numeric,total_ads_spend numeric,
  total_spend numeric,roi numeric,aov numeric,avg_daily_creator_sales numeric,referral_commission numeric,
  total_live_streams numeric,total_videos numeric
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  return query
  with affiliate_base as (
    select s.* from public.sales s
    where s.workspace_id=p_workspace_id and s.data_type in ('performance','sales')
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
      and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name))
  ),
  product_count as (
    select count(distinct nullif(coalesce(s.sku,s.product_name),''))::bigint products
    from public.sales s
    where s.workspace_id=p_workspace_id and s.data_type in ('product_performance','sales')
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
      and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name))
  ),
  agg as (
    select
      count(distinct creator_id) filter(where coalesce(gmv,0)<>0 or coalesce(orders,0)<>0 or coalesce(qty,0)<>0 or coalesce(commission,0)<>0)::bigint active_creators,
      count(*)::bigint rows,coalesce(sum(qty),0) qty,coalesce(sum(orders),0) orders,coalesce(sum(gmv),0) gmv,
      coalesce(sum(commission),0) commission,coalesce(sum(cost_product),0) cost_product,coalesce(sum(shipping_cost),0) shipping,
      coalesce(sum(live_count),0) live_streams,coalesce(sum(video_count),0) videos,
      count(distinct data_date) filter(where data_date is not null) days
    from affiliate_base
  ),
  ads_support as (
    select coalesce(max(a.amount),0)::numeric amount
    from public.affiliate_ads_support a
    where a.workspace_id=p_workspace_id
      and p_start_date is not null and p_end_date is not null
      and a.start_date=p_start_date and a.end_date=p_end_date
      and lower(a.platform)=lower(coalesce(nullif(p_platform,''),'ALL'))
      and lower(a.store_name)=lower(coalesce(nullif(p_store_name,''),'ALL'))
  ),
  ref as (
    select coalesce(sum(r.commission_amount),0) amount
    from public.referral_events r
    where r.workspace_id=p_workspace_id and lower(coalesce(r.status,'')) in ('confirmed','paid')
      and (p_start_date is null or r.created_at::date>=p_start_date)
      and (p_end_date is null or r.created_at::date<=p_end_date)
  )
  select
    a.active_creators,a.rows,a.qty,a.orders,a.gmv,a.commission,pc.products,a.cost_product,a.shipping,ads.amount,
    (a.cost_product+a.shipping+ads.amount+a.commission)::numeric,
    case when (a.cost_product+a.shipping+ads.amount+a.commission)>0
      then round(a.gmv/(a.cost_product+a.shipping+ads.amount+a.commission),2) else 0 end,
    case when a.orders>0 then round(a.gmv/a.orders,2) else 0 end,
    case when a.active_creators>0 and a.days>0 then round(a.gmv/a.active_creators/a.days,2) else 0 end,
    ref.amount,a.live_streams,a.videos
  from agg a cross join product_count pc cross join ads_support ads cross join ref;
end
$$;

create or replace function public.get_creator_ranking_v2(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null,
  p_store_name text default null,
  p_creator_id bigint default null,
  p_search text default null,
  p_page integer default 1,
  p_page_size integer default 50
)
returns table(
  rank bigint,creator_id bigint,creator_code text,creator_name text,username text,platform text,
  qty numeric,orders numeric,gmv numeric,commission numeric,total_rows bigint
)
language sql
security invoker
set search_path=public,pg_temp
as $$
  with ranked as (
    select s.creator_id,max(s.creator_name) sales_creator_name,max(s.username) sales_username,max(s.platform) sales_platform,
           coalesce(sum(s.qty),0) qty,coalesce(sum(s.orders),0) orders,coalesce(sum(s.gmv),0) gmv,coalesce(sum(s.commission),0) commission
    from public.sales s
    where s.workspace_id=p_workspace_id
      and s.data_type in ('performance','sales')
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
      and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name))
      and (p_creator_id is null or s.creator_id=p_creator_id)
    group by s.creator_id
  ),
  joined as (
    select r.creator_id,coalesce(c.creator_code,'') creator_code,
           coalesce(c.name,r.sales_creator_name,'') creator_name,
           coalesce(c.username,r.sales_username,'') username,
           coalesce(r.sales_platform,c.platform,'') platform,
           r.qty,r.orders,r.gmv,r.commission
    from ranked r
    left join public.creators c on c.id=r.creator_id and c.workspace_id=p_workspace_id
    where p_search is null or p_search=''
       or coalesce(c.name,r.sales_creator_name,'') ilike '%'||p_search||'%'
       or coalesce(c.username,r.sales_username,'') ilike '%'||p_search||'%'
       or coalesce(c.creator_code,'') ilike '%'||p_search||'%'
  ),
  numbered as (
    select row_number() over(order by gmv desc,orders desc,qty desc,creator_id asc) rank,* from joined
  )
  select n.rank,n.creator_id,n.creator_code,n.creator_name,n.username,n.platform,n.qty,n.orders,n.gmv,n.commission,
         count(*) over() total_rows
  from numbered n
  order by n.rank
  limit greatest(1,least(coalesce(p_page_size,50),100))
  offset greatest(0,coalesce(p_page,1)-1)*greatest(1,least(coalesce(p_page_size,50),100));
$$;

create or replace function public.get_creator_ranking_summary_v2(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null,
  p_store_name text default null
)
returns table(total_creators bigint,active_creators bigint)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  return query
  select count(distinct s.creator_id)::bigint,
         count(distinct s.creator_id) filter(
           where coalesce(s.gmv,0)<>0 or coalesce(s.orders,0)<>0 or coalesce(s.qty,0)<>0 or coalesce(s.commission,0)<>0
         )::bigint
  from public.sales s
  where s.workspace_id=p_workspace_id and s.data_type in ('performance','sales') and s.creator_id is not null
    and (p_start_date is null or s.data_date>=p_start_date)
    and (p_end_date is null or s.data_date<=p_end_date)
    and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
    and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name));
end
$$;

create or replace function public.get_product_ranking_v2(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null,
  p_store_name text default null,
  p_search text default null,
  p_page integer default 1,
  p_page_size integer default 50
)
returns table(
  rank bigint,sku text,product_name text,platform text,qty numeric,orders numeric,gmv numeric,
  commission numeric,clicks numeric,buyers numeric,new_buyers numeric,refund numeric,refund_qty numeric,
  roi numeric,total_rows bigint
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  return query
  with grouped as (
    select
      coalesce(nullif(s.sku,''),lower(coalesce(s.product_name,''))) product_key,
      max(nullif(s.sku,'')) sku,max(coalesce(nullif(s.product_name,''),pm.product_name,'')) product_name,max(s.platform) platform,
      coalesce(sum(s.qty),0) qty,coalesce(sum(s.orders),0) orders,coalesce(sum(s.gmv),0) gmv,
      coalesce(sum(s.commission),0) commission,coalesce(sum(s.clicks),0) clicks,
      coalesce(sum(s.buyers),0) buyers,coalesce(sum(s.new_buyers),0) new_buyers,
      coalesce(sum(s.refund),0) refund,coalesce(sum(s.refund_qty),0) refund_qty,
      case when coalesce(sum(s.commission),0)>0 then round(sum(s.gmv)/sum(s.commission),2) else coalesce(max(s.roi),0) end roi
    from public.sales s
    left join public.product_master pm on pm.workspace_id=s.workspace_id and pm.sku_normalized=lower(coalesce(s.sku,''))
    where s.workspace_id=p_workspace_id and s.data_type='product_performance'
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
      and (p_store_name is null or p_store_name='' or lower(coalesce(s.store_name,''))=lower(p_store_name))
    group by coalesce(nullif(s.sku,''),lower(coalesce(s.product_name,'')))
  ),
  filtered as (
    select g.* from grouped g
    where p_search is null or p_search=''
       or coalesce(g.sku,'') ilike '%'||p_search||'%'
       or coalesce(g.product_name,'') ilike '%'||p_search||'%'
  ),
  numbered as (
    select row_number() over(order by f.gmv desc,f.orders desc,f.qty desc,f.product_key asc) row_rank,f.* from filtered f
  )
  select n.row_rank,n.sku,n.product_name,n.platform,n.qty,n.orders,n.gmv,n.commission,n.clicks,n.buyers,n.new_buyers,
         n.refund,n.refund_qty,n.roi,count(*) over()
  from numbered n
  order by n.row_rank
  limit greatest(1,least(coalesce(p_page_size,50),100))
  offset greatest(0,coalesce(p_page,1)-1)*greatest(1,least(coalesce(p_page_size,50),100));
end
$$;

create or replace function public.get_store_dashboard_v2(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null,
  p_store_name text default null
)
returns table(store_name text,platform text,total_affiliates bigint,active_affiliates bigint,inactive_affiliates bigint,gmv numeric,orders numeric,qty numeric,spend numeric,roi numeric)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  return query
  with stores as (
    select coalesce(nullif(s.store_name,''),'Unassigned') store_name,max(s.platform) platform,
           count(distinct s.creator_id)::bigint total_affiliates,
           count(distinct s.creator_id) filter(where coalesce(s.gmv,0)<>0 or coalesce(s.orders,0)<>0 or coalesce(s.qty,0)<>0)::bigint active_affiliates,
           coalesce(sum(s.gmv),0) gmv,coalesce(sum(s.orders),0) orders,coalesce(sum(s.qty),0) qty,
           coalesce(sum(coalesce(s.cost_product,0)+coalesce(s.shipping_cost,0)+coalesce(s.ads_spend,0)),0) spend
    from public.sales s
    where s.workspace_id=p_workspace_id
      and s.data_type in ('performance','sales')
      and nullif(trim(s.store_name),'') is not null
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
      and (p_store_name is null or p_store_name='' or lower(s.store_name)=lower(p_store_name))
    group by s.store_name
  )
  select s.store_name,s.platform,s.total_affiliates,s.active_affiliates,
         greatest(0,s.total_affiliates-s.active_affiliates)::bigint,s.gmv,s.orders,s.qty,s.spend,
         case when s.spend>0 then round(s.gmv/s.spend,2) else 0 end
  from stores s
  order by s.gmv desc,s.store_name;
end
$$;

create or replace function public.set_affiliate_ads_support_v2(
  p_workspace_id uuid,p_start_date date,p_end_date date,p_platform text,p_store_name text,p_amount numeric,p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_id bigint;
  v_platform text:=coalesce(nullif(trim(p_platform),''),'ALL');
  v_store text:=coalesce(nullif(trim(p_store_name),''),'ALL');
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;
  if p_start_date is null or p_end_date is null or p_end_date<p_start_date then raise exception 'Periode Ads Spend Support tidak valid' using errcode='22007'; end if;
  if coalesce(p_amount,0)<0 then raise exception 'Ads Spend Support tidak boleh negatif' using errcode='22003'; end if;

  insert into public.affiliate_ads_support(workspace_id,start_date,end_date,platform,store_name,amount,notes,created_by,updated_at)
  values(p_workspace_id,p_start_date,p_end_date,v_platform,v_store,coalesce(p_amount,0),nullif(trim(p_notes),''),auth.uid(),now())
  on conflict(workspace_id,start_date,end_date,platform,store_name)
  do update set amount=excluded.amount,notes=excluded.notes,updated_at=now(),created_by=auth.uid()
  returning id into v_id;
  return v_id;
end
$$;

-- Lock down new SECURITY DEFINER RPCs to authenticated/service only.
revoke all on function public.get_dashboard_latest_date_v2(uuid,text,text) from public,anon;
grant execute on function public.get_dashboard_latest_date_v2(uuid,text,text) to authenticated,service_role;
revoke all on function public.get_creator_ranking_summary_v2(uuid,date,date,text,text) from public,anon;
grant execute on function public.get_creator_ranking_summary_v2(uuid,date,date,text,text) to authenticated,service_role;
revoke all on function public.get_product_ranking_v2(uuid,date,date,text,text,text,integer,integer) from public,anon;
grant execute on function public.get_product_ranking_v2(uuid,date,date,text,text,text,integer,integer) to authenticated,service_role;
revoke all on function public.get_store_dashboard_v2(uuid,date,date,text,text) from public,anon;
grant execute on function public.get_store_dashboard_v2(uuid,date,date,text,text) to authenticated,service_role;
revoke all on function public.get_dashboard_metrics_v5(uuid,date,date,text,text) from public,anon;
grant execute on function public.get_dashboard_metrics_v5(uuid,date,date,text,text) to authenticated,service_role;
revoke all on function public.set_affiliate_ads_support_v2(uuid,date,date,text,text,numeric,text) from public,anon;
grant execute on function public.set_affiliate_ads_support_v2(uuid,date,date,text,text,numeric,text) to authenticated,service_role;

-- Security-invoker read RPCs: authenticated only.
revoke all on function public.get_dashboard_store_options(uuid,text) from public,anon;
grant execute on function public.get_dashboard_store_options(uuid,text) to authenticated,service_role;
revoke all on function public.get_creator_ranking_v2(uuid,date,date,text,text,bigint,text,integer,integer) from public,anon;
grant execute on function public.get_creator_ranking_v2(uuid,date,date,text,text,bigint,text,integer,integer) to authenticated,service_role;


-- ---------------------------------------------------------------------------
-- 8. Full-period AI context aggregation.
-- Calculates from all rows in PostgreSQL; no client-side row sampling limits.
-- ---------------------------------------------------------------------------
create or replace function public.luma_ai_period_context(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_focus text default 'performance'
)
returns jsonb
language sql
security invoker
set search_path=public,pg_temp
as $$
with affiliate as (
  select *
  from public.sales s
  where s.workspace_id=p_workspace_id
    and s.data_type in ('performance','sales')
    and (p_start_date is null or s.data_date>=p_start_date)
    and (p_end_date is null or s.data_date<=p_end_date)
),
product as (
  select *
  from public.sales s
  where s.workspace_id=p_workspace_id
    and s.data_type='product_performance'
    and (p_start_date is null or s.data_date>=p_start_date)
    and (p_end_date is null or s.data_date<=p_end_date)
),
metric as (
  select * from product where lower(coalesce(p_focus,''))='product'
  union all
  select * from affiliate where lower(coalesce(p_focus,''))<>'product'
),
kpi as (
  select
    coalesce(sum(gmv),0)::numeric gmv,
    coalesce(sum(qty),0)::numeric qty,
    coalesce(sum(orders),0)::numeric orders,
    coalesce(sum(commission),0)::numeric commission,
    coalesce(sum(refund),0)::numeric refund,
    coalesce(sum(clicks),0)::numeric clicks,
    coalesce(sum(buyers),0)::numeric buyers,
    coalesce(sum(live_count),0)::numeric live_count,
    coalesce(sum(video_count),0)::numeric video_count,
    coalesce(sum(sample_sent),0)::numeric sample_sent
  from metric
),
creator_stats as (
  select
    coalesce(s.creator_id::text,lower(coalesce(s.platform,''))||'|'||lower(coalesce(s.username,s.creator_name,''))) creator_key,
    max(s.creator_name) creator,
    max(s.username) username,
    max(s.platform) platform,
    coalesce(sum(s.gmv),0)::numeric gmv,
    coalesce(sum(s.qty),0)::numeric qty,
    coalesce(sum(s.orders),0)::numeric orders,
    coalesce(sum(s.commission),0)::numeric commission
  from affiliate s
  where s.creator_id is not null or nullif(trim(coalesce(s.username,s.creator_name,'')),'') is not null
  group by 1
),
product_stats as (
  select
    coalesce(nullif(s.sku,''),nullif(s.product_code,''),nullif(s.product_name,'')) product_key,
    max(s.sku) sku,
    max(s.product_name) product,
    max(s.category) category,
    max(s.platform) platform,
    coalesce(sum(s.gmv),0)::numeric gmv,
    coalesce(sum(s.qty),0)::numeric qty,
    coalesce(sum(s.orders),0)::numeric orders,
    coalesce(sum(s.commission),0)::numeric commission,
    coalesce(sum(s.refund),0)::numeric refund,
    coalesce(sum(s.clicks),0)::numeric clicks
  from product s
  where coalesce(nullif(s.sku,''),nullif(s.product_code,''),nullif(s.product_name,'')) is not null
  group by 1
),
platform_stats as (
  select coalesce(nullif(platform,''),'Unknown') platform,
         coalesce(sum(gmv),0)::numeric gmv,
         coalesce(sum(qty),0)::numeric qty,
         coalesce(sum(orders),0)::numeric orders,
         coalesce(sum(commission),0)::numeric commission,
         coalesce(sum(refund),0)::numeric refund,
         coalesce(sum(clicks),0)::numeric clicks
  from metric
  group by 1
),
monthly as (
  select to_char(date_trunc('month',data_date),'YYYY-MM') period,
         coalesce(sum(gmv),0)::numeric gmv,
         coalesce(sum(qty),0)::numeric qty,
         coalesce(sum(orders),0)::numeric orders,
         coalesce(sum(commission),0)::numeric commission,
         coalesce(sum(refund),0)::numeric refund
  from metric
  where data_date is not null
  group by 1
),
store_stats as (
  select coalesce(nullif(store_name,''),'Unassigned') store_name,
         max(platform) platform,
         count(*)::bigint rows,
         coalesce(sum(gmv),0)::numeric gmv,
         coalesce(sum(orders),0)::numeric orders,
         coalesce(sum(qty),0)::numeric qty
  from affiliate
  where nullif(trim(coalesce(store_name,'')),'') is not null
  group by store_name
),
quality as (
  select
    (select count(*) from affiliate)::bigint affiliate_rows,
    (select count(*) from product)::bigint product_rows,
    (select count(*) from public.imports i
       where i.workspace_id=p_workspace_id
         and lower(coalesce(i.status,''))='success'
         and (p_start_date is null or i.end_date is null or i.end_date>=p_start_date)
         and (p_end_date is null or i.start_date is null or i.start_date<=p_end_date)
    )::bigint import_count
)
select jsonb_build_object(
  'analysis_focus',p_focus,
  'period',jsonb_build_object('start',coalesce(p_start_date::text,'ALL DATA'),'end',coalesce(p_end_date::text,'ALL DATA')),
  'kpi',(
    select jsonb_build_object(
      'gmv',k.gmv,'qty',k.qty,'orders',k.orders,'commission',k.commission,'refund',k.refund,
      'clicks',k.clicks,'buyers',k.buyers,'live_count',k.live_count,'video_count',k.video_count,'sample_sent',k.sample_sent,
      'active_creators',(select count(*) from creator_stats),
      'total_products',(select count(*) from product_stats),
      'roi',case when k.commission>0 then round(k.gmv/k.commission,4) else null end,
      'aov',case when k.orders>0 then round(k.gmv/k.orders,2) else null end
    ) from kpi k
  ),
  'platforms',coalesce((select jsonb_agg(to_jsonb(x) order by x.gmv desc) from (select * from platform_stats order by gmv desc limit 20) x),'[]'::jsonb),
  'top_creators',coalesce((select jsonb_agg(to_jsonb(x) order by x.rank) from (
      select row_number() over(order by c.gmv desc,c.orders desc,c.qty desc) rank,
             c.creator,c.username,c.platform,c.gmv,c.qty,c.orders,c.commission
      from creator_stats c order by c.gmv desc,c.orders desc,c.qty desc limit 50
    ) x),'[]'::jsonb),
  'top_products',coalesce((select jsonb_agg(to_jsonb(x) order by x.rank) from (
      select row_number() over(order by p.gmv desc,p.orders desc,p.qty desc) rank,
             p.sku,p.product,p.category,p.platform,p.gmv,p.qty,p.orders,p.commission,p.refund,p.clicks
      from product_stats p order by p.gmv desc,p.orders desc,p.qty desc limit 50
    ) x),'[]'::jsonb),
  'monthly_trend',coalesce((select jsonb_agg(to_jsonb(m) order by m.period) from monthly m),'[]'::jsonb),
  'stores',coalesce((select jsonb_agg(to_jsonb(s) order by s.gmv desc) from store_stats s),'[]'::jsonb),
  'data_quality',(
    select jsonb_build_object(
      'affiliate_rows',q.affiliate_rows,
      'product_rows',q.product_rows,
      'imports_in_period',q.import_count,
      'sampling',false,
      'complete_period_aggregation',true
    ) from quality q
  )
);
$$;

revoke all on function public.luma_ai_period_context(uuid,date,date,text) from public,anon;
grant execute on function public.luma_ai_period_context(uuid,date,date,text) to authenticated,service_role;
