-- PR31: manual Ads Spend Support + LIVE/video metrics.
create table if not exists public.affiliate_ads_support (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  platform text not null default 'ALL',
  amount numeric not null default 0 check (amount >= 0),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint affiliate_ads_support_valid_period check (end_date >= start_date),
  constraint affiliate_ads_support_period_unique unique (workspace_id,start_date,end_date,platform)
);

alter table public.affiliate_ads_support enable row level security;
revoke all on public.affiliate_ads_support from anon;
revoke all on public.affiliate_ads_support from authenticated;

create or replace function public.get_affiliate_ads_support(
  p_workspace_id uuid,
  p_start_date date,
  p_end_date date,
  p_platform text default null
)
returns numeric
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_amount numeric := 0;
  v_platform text := coalesce(nullif(trim(p_platform),''),'ALL');
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then
    raise exception 'Workspace access denied' using errcode='42501';
  end if;

  select coalesce(a.amount,0) into v_amount
  from public.affiliate_ads_support a
  where a.workspace_id=p_workspace_id
    and a.start_date=p_start_date
    and a.end_date=p_end_date
    and lower(a.platform)=lower(v_platform)
  limit 1;

  return coalesce(v_amount,0);
end
$function$;

revoke all on function public.get_affiliate_ads_support(uuid,date,date,text) from public;
revoke all on function public.get_affiliate_ads_support(uuid,date,date,text) from anon;
grant execute on function public.get_affiliate_ads_support(uuid,date,date,text) to authenticated;

create or replace function public.set_affiliate_ads_support(
  p_workspace_id uuid,
  p_start_date date,
  p_end_date date,
  p_platform text,
  p_amount numeric,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_id bigint;
  v_platform text := coalesce(nullif(trim(p_platform),''),'ALL');
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then
    raise exception 'Workspace access denied' using errcode='42501';
  end if;
  if p_start_date is null or p_end_date is null or p_end_date < p_start_date then
    raise exception 'Periode Ads Spend Support tidak valid' using errcode='22007';
  end if;
  if coalesce(p_amount,0) < 0 then
    raise exception 'Ads Spend Support tidak boleh negatif' using errcode='22003';
  end if;

  insert into public.affiliate_ads_support(workspace_id,start_date,end_date,platform,amount,notes,created_by,updated_at)
  values(p_workspace_id,p_start_date,p_end_date,v_platform,coalesce(p_amount,0),nullif(trim(p_notes),''),auth.uid(),now())
  on conflict (workspace_id,start_date,end_date,platform)
  do update set amount=excluded.amount,notes=excluded.notes,updated_at=now(),created_by=auth.uid()
  returning id into v_id;

  return v_id;
end
$function$;

revoke all on function public.set_affiliate_ads_support(uuid,date,date,text,numeric,text) from public;
revoke all on function public.set_affiliate_ads_support(uuid,date,date,text,numeric,text) from anon;
grant execute on function public.set_affiliate_ads_support(uuid,date,date,text,numeric,text) to authenticated;

create or replace function public.get_dashboard_metrics_v3(
  p_workspace_id uuid,
  p_start_date date default null,
  p_end_date date default null,
  p_platform text default null
)
returns table(
  total_creators bigint,total_sales_records bigint,total_qty numeric,total_orders numeric,total_gmv numeric,
  total_commission numeric,total_products bigint,total_cost_product numeric,total_shipping numeric,total_ads_spend numeric,
  total_spend numeric,roi numeric,aov numeric,avg_daily_creator_sales numeric,referral_commission numeric,
  total_live_streams numeric,total_videos numeric
)
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not (
    public.luma_is_admin()
    or exists(select 1 from public.workspace_members wm where wm.workspace_id=p_workspace_id and wm.user_id=auth.uid())
  ) then raise exception 'Workspace access denied' using errcode='42501'; end if;

  return query
  with affiliate_base as (
    select s.* from public.sales s
    where s.workspace_id=p_workspace_id
      and s.data_type in ('performance','sales')
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
  ),
  product_count as (
    select count(distinct nullif(coalesce(s.sku,s.product_name),''))::bigint products
    from public.sales s
    where s.workspace_id=p_workspace_id
      and s.data_type in ('product_performance','sales')
      and (p_start_date is null or s.data_date>=p_start_date)
      and (p_end_date is null or s.data_date<=p_end_date)
      and (p_platform is null or p_platform='' or lower(s.platform)=lower(p_platform))
  ),
  agg as (
    select count(distinct creator_id)::bigint creators,count(*)::bigint rows,
      coalesce(sum(qty),0) qty,coalesce(sum(orders),0) orders,coalesce(sum(gmv),0) gmv,
      coalesce(sum(commission),0) commission,coalesce(sum(cost_product),0) cost_product,
      coalesce(sum(shipping_cost),0) shipping,coalesce(sum(live_count),0) live_streams,
      coalesce(sum(video_count),0) videos,count(distinct data_date) filter(where data_date is not null) days
    from affiliate_base
  ),
  ads_support as (
    select coalesce(max(a.amount),0)::numeric amount
    from public.affiliate_ads_support a
    where a.workspace_id=p_workspace_id
      and p_start_date is not null and p_end_date is not null
      and a.start_date=p_start_date and a.end_date=p_end_date
      and lower(a.platform)=lower(coalesce(nullif(p_platform,''),'ALL'))
  ),
  ref as (
    select coalesce(sum(r.commission_amount),0) amount
    from public.referral_events r
    where r.workspace_id=p_workspace_id and lower(coalesce(r.status,'')) in ('confirmed','paid')
      and (p_start_date is null or r.created_at::date>=p_start_date)
      and (p_end_date is null or r.created_at::date<=p_end_date)
  )
  select a.creators,a.rows,a.qty,a.orders,a.gmv,a.commission,pc.products,a.cost_product,a.shipping,ads.amount,
    (a.cost_product+a.shipping+ads.amount+a.commission)::numeric,
    case when (a.cost_product+a.shipping+ads.amount+a.commission)>0 then round(a.gmv/(a.cost_product+a.shipping+ads.amount+a.commission),2) else 0 end,
    case when a.orders>0 then round(a.gmv/a.orders,2) else 0 end,
    case when a.creators>0 and a.days>0 then round(a.gmv/(a.creators*a.days),2) else 0 end,
    ref.amount,a.live_streams,a.videos
  from agg a cross join product_count pc cross join ads_support ads cross join ref;
end
$function$;

revoke all on function public.get_dashboard_metrics_v3(uuid,date,date,text) from public;
revoke all on function public.get_dashboard_metrics_v3(uuid,date,date,text) from anon;
grant execute on function public.get_dashboard_metrics_v3(uuid,date,date,text) to authenticated;
